/* UnScramble office / admin screens. */
'use strict';
NAV.admin=[['#/home','Overview'],['#/review','Review & approve'],['#/people','People'],['#/compliance','Compliance'],['#/termsadmin','Terms'],['#/invoicesadmin','Invoices'],['#/recordsadmin','Records requests'],['#/wagepoint','Wagepoint'],['#/testers','Testers'],['#/firms','Farms & other clients'],['#/farmchanges','Farm & client time changes'],['#/shiftsadmin','Shifts'],['#/feedbackadmin','Feedback'],['#/analytics','Analytics'],['#/alerts','Alerts outbox'],['#/auditlog','Audit log'],['#/privacy','Privacy & marketing'],['#/settings','Settings / reset']];
function realPeople(){return DB.users.filter(function(u){return u.type==='worker'||u.type==='employee';});}
function blockedList(){var out=[];DB.users.forEach(function(u){if(u.type==='admin'||u.type==='firm')return;var b=u.type==='sub'?companyBlockers(u).map(function(m){return {m:m};}):blockers(u,today());if(u.type==='tester')b=b.filter(function(x){return x.m.indexOf('real shift')<0;});if(b.length)out.push({u:u,b:b});});return out;}
function expiringList(){var out=[];DB.docs.forEach(function(d){if(d.status!=='approved'||latestDoc(d.userId,d.kind)!==d)return;var ex=docExpiry(d);if(!ex)return;var l=daysBetween(today(),ex);var u=user(d.userId);if(!u)return;out.push({u:u,what:d.kind==='wcb_clearance'?'WCB clearance 90-day re-check':DOCS[d.kind].label,ex:ex,left:l});});
  realPeople().forEach(function(u){var sx=safetyExpiry(u);if(sx)out.push({u:u,what:'Safety training refresh',ex:sx,left:daysBetween(today(),sx)});var p=u.profile||{};if(p.sinTemp&&p.sinExpiry)out.push({u:u,what:'Temporary SIN expiry',ex:p.sinExpiry,left:daysBetween(today(),p.sinExpiry)});});
  return out.sort(function(a,b){return a.left-b.left;});}
function colour(left){return left<=0?'s-bad':left<=30?'s-warn':'s-ok';}
VIEWS['admin:home']=function(){
  var pendDocs=DB.docs.filter(function(d){return d.status==='pending';}).length,bl=blockedList(),ex=expiringList();
  var inv=DB.invoices.filter(function(i){return !i.test;}),flags=adminFlags();
  var x='<h1>Office overview</h1><div class="grid">'+
   statCard('Uploads to review',pendDocs,'#/review')+statCard('Accounts to approve',pendingAccounts().length,'#/review')+statCard('Blocked right now',bl.length,'#/compliance')+statCard('Expiring in 30 days',ex.filter(function(e){return e.left>0&&e.left<=30;}).length,'#/compliance')+statCard('Expired',ex.filter(function(e){return e.left<=0;}).length,'#/compliance')+statCard('Invoices to approve',inv.filter(function(i){return i.status==='Submitted';}).length,'#/invoicesadmin')+statCard('Ready for Wagepoint',users('employee').filter(function(u){return u.approved&&registrationComplete(u)&&!(u.wagepoint&&u.wagepoint.added);}).length,'#/wagepoint')+statCard('New feedback',DB.feedback.filter(function(f){return f.status==='New';}).length,'#/feedbackadmin')+'</div>';
  if(flags.length)x+='<h2>Needs attention</h2><div class="card"><ul class="check">'+flags.map(function(f){return '<li><span class="pill '+f.c+'">'+esc(f.t)+'</span><div>'+f.h+'</div></li>';}).join('')+'</ul></div>';
  x+='<h2>Expiring in the next 30 days and expired</h2>'+expTable(ex.filter(function(e){return e.left<=30;}));
  x+='<h2>Blocked list (who and why)</h2>'+blockedTable(bl);
  return x;};
function statCard(l,n,href){return '<a class="card" href="'+href+'" style="text-decoration:none;color:inherit"><div class="muted small">'+esc(l)+'</div><div class="stat">'+n+'</div></a>';}
function expTable(list){return list.length?'<div class="tw"><table><tr><th>Who</th><th>Item</th><th>Date</th><th>Status</th></tr>'+list.map(function(e){return '<tr><td>'+esc(e.u.name)+'<div class="small muted">'+esc(TYPES[e.u.type])+'</div></td><td>'+esc(e.what)+'</td><td>'+esc(e.ex)+'</td><td><span class="pill '+colour(e.left)+'">'+(e.left<=0?'Expired':'In '+e.left+' days')+'</span></td></tr>';}).join('')+'</table></div>':'<p class="muted">Nothing.</p>';}
function blockedTable(bl){return bl.length?'<div class="tw"><table><tr><th>Who</th><th>Why</th></tr>'+bl.map(function(x){return '<tr><td><a href="#" data-act="person" data-id="'+x.u.id+'">'+esc(x.u.name)+'</a><div class="small muted">'+esc(TYPES[x.u.type])+'</div></td><td class="small">'+x.b.map(function(b){return esc(b.m);}).join('<br>')+'</td></tr>';}).join('')+'</table></div>':'<p class="muted">Nobody is blocked.</p>';}
function pendingAccounts(){return DB.users.filter(function(u){return (u.type==='sub'&&!u.approved)||(u.type==='employee'&&!u.approved);});}
function adminFlags(){var f=[];var pc=DB.changes.filter(function(c){return c.status==='Pending';}).length;if(pc)f.push({t:'Farm changes',c:'s-pend',h:pc+' shift time change(s) proposed by farms. <a href="#/farmchanges">Review →</a>'});
  users('sub').forEach(function(s){var i=tempInfo(s);if(i&&i.active)f.push({t:'Temporary mode',c:'s-warn',h:tempBadge(s)+' '+esc(s.company.legalName)+' – '+(companyCompliant(s)?'now compliant (you can end it and release '+money(heldAmount(s))+')':'still missing: '+esc(companyBlockersRaw(s).join(' ')))+' · held '+money(heldAmount(s))+' <a href="#/compliance">Manage →</a>'});});
  DB.invoices.forEach(function(i){if(i.detailsChanged&&!i.detailsReviewed&&!i.test)f.push({t:'Invoice details changed',c:'s-warn',h:esc(i.number)+' – business name/BN/HST differ from profile. <button class="small sec" data-act="invreviewed" data-id="'+i.id+'">Mark reviewed</button>'});});
  users('sub').forEach(function(s){var c=s.company||{};if(c.bankAcct&&!c.bankVerified)f.push({t:'Banking to verify',c:'s-warn',h:esc(c.legalName)+' changed banking. <button class="small sec" data-act="verifybank" data-id="'+s.id+'">Mark verified</button>'});if(c.licenceNotReq&&!c.licenceNotReqConfirmed)f.push({t:'Licence "not required"',c:'s-pend',h:esc(c.legalName)+' says no agency licence is needed. <button class="small sec" data-act="confirmlic" data-id="'+s.id+'">Confirm</button>'});});
  users('employee').forEach(function(u){var p=u.profile||{};if(p.bankAcct&&p.bankVerified===false)f.push({t:'Banking to verify',c:'s-warn',h:esc(u.name)+' changed direct deposit – re-verify before payroll. <button class="small sec" data-act="verifyempbank" data-id="'+u.id+'">Mark verified</button>'});if(u.wagepoint&&u.wagepoint.update&&u.wagepoint.update.length)f.push({t:'Update Wagepoint',c:'s-warn',h:esc(u.name)+' changed: '+esc(u.wagepoint.update.join(', '))+' <a href="#/wagepoint">Wagepoint →</a>'});if(p.noSin)f.push({t:'No SIN',c:'s-bad',h:esc(u.name)+' has no SIN – tell Service Canada within 6 days of start ('+esc(p.startDate||'?')+').'});
    var dp=latestDoc(u.id,'eligibility');if(dp&&dp.meta&&dp.meta.docType==='permit'&&!permitMatches(u,dp))f.push({t:'Permit employer mismatch',c:'s-warn',h:esc(u.name)});});
  users('worker').forEach(function(u){var dp=latestDoc(u.id,'eligibility');if(dp&&dp.meta&&dp.meta.docType==='permit'&&!permitMatches(u,dp))f.push({t:'Permit employer mismatch',c:'s-warn',h:esc(u.name)+': permit names "'+esc(dp.meta.permitEmployer)+'", linked employer is '+esc(employerName(u))});});
  DB.convReq.filter(function(r){return r.status==='Requested';}).forEach(function(r){var u=user(r.userId);if(u)f.push({t:'Conversion request',c:'s-test',h:esc(u.name)+' asks to become '+esc(TYPES[r.to])+' <a href="#/testers">Testers →</a>'});});
  DB.records.forEach(function(r){if(r.status==='Open'&&r.due<today())f.push({t:'Records overdue',c:'s-bad',h:esc((user(r.subId)||{}).name)+' – due '+esc(r.due)});});
  DB.privacyReq.filter(function(r){return r.status==='Open';}).forEach(function(r){f.push({t:'Privacy request',c:'s-pend',h:esc(r.name)+' – '+esc(r.kind)+' <a href="#/privacy">→</a>'});});
  return f;}
ACT.invreviewed=function(el){var i=DB.invoices.filter(function(x){return x.id===el.dataset.id;})[0];i.detailsReviewed=true;audit('Reviewed invoice detail change',i.number);save();render();};
ACT.verifybank=function(el){var s=user(el.dataset.id);s.company.bankVerified=true;audit('Verified banking',s.name);save();render();};
ACT.verifyempbank=function(el){var u=user(el.dataset.id);u.profile.bankVerified=true;audit('Verified employee banking',u.name);save();render();};
ACT.confirmlic=function(el){var s=user(el.dataset.id);s.company.licenceNotReqConfirmed=true;audit('Confirmed agency licence not required',s.name);save();render();};

/* ---------- Review & approve ---------- */
VIEWS['admin:review']=function(){var pd=DB.docs.filter(function(d){return d.status==='pending';}),pa=pendingAccounts();
  var x='<h1>Review &amp; approve</h1><h2>Registrations</h2>';
  x+=pa.length?'<div class="tw"><table><tr><th>Who</th><th>Type</th><th>Checklist</th><th></th></tr>'+pa.map(function(u){var R=requirements(u).filter(function(r){return !r.ok&&r.key!=='approved'&&r.key!=='wagepoint';});return '<tr><td><a href="#" data-act="person" data-id="'+u.id+'">'+esc(u.name)+'</a></td><td>'+typePill(u)+'</td><td class="small">'+(R.length?R.map(function(r){return esc(r.label)+': '+r.st.s;}).join('<br>'):'<span class="pill s-ok">Everything submitted</span>')+'</td><td><button class="small" data-act="approveacct" data-id="'+u.id+'">Approve registration</button></td></tr>';}).join('')+'</table></div>':'<p class="muted">No registrations waiting.</p>';
  var wc=users('worker').filter(function(w){return !w.confirmedBySub;});if(wc.length)x+='<p class="small">Subcontractor workers waiting for their employer to confirm them: '+wc.map(function(w){return esc(w.name)+' ('+esc(employerName(w))+')';}).join(', ')+'</p>';
  x+='<h2>Uploaded documents to review</h2>'+(pd.length?pd.map(function(d){var u=user(d.userId);return '<div class="card"><div class="row"><b>'+esc(DOCS[d.kind].label)+'</b><span class="small">– '+esc(u?u.name:'?')+' ('+esc(u?TYPES[u.type]:'')+')</span><span class="right small muted">uploaded '+fmtStamp(d.uploadedAt)+'</span></div><div class="small">'+metaText(d)+'</div><p><button class="small sec" data-act="viewdoc" data-id="'+d.id+'">View file</button></p><form data-form="reviewdoc"><input type="hidden" name="id" value="'+d.id+'"><div class="grid2">'+
    (DOCS[d.kind].expiry?inp('expiry',d.kind==='wcb_clearance'?'Printed expiry (if any)':'Expiry date (check it matches the document)',d.expiry,{type:'date'}):'')+(d.kind==='wcb_clearance'?inp('verifiedDate','Date verified (90-day re-check starts here)',today(),{type:'date',req:true}):'')+'</div>'+
    (d.kind==='cgl'?chk('additionalInsured','UnScramble is named as additional insured (min $2,000,000 per occurrence confirmed)',false):'')+(d.kind==='eligibility'&&u&&u.type==='worker'?'<div class="small">Employer checked originals: <b>'+(u.originalsChecked?'yes':'not yet')+'</b></div>':'')+
    '<div class="row" style="margin-top:6px"><button class="small" name="ok" value="1">Approve</button><input type="text" name="reason" placeholder="Reason if rejecting" style="max-width:260px"><button class="small danger" data-act="rejectdoc" data-id="'+d.id+'">Reject</button></div></form></div>';}).join(''):'<p class="muted">No uploads waiting.</p>');
  return x;};
function metaText(d){var m=d.meta||{},a=[];if(m.docType)a.push({citizen:'Citizen/passport',pr:'Permanent resident',permit:'Work permit'}[m.docType]);if(m.permitEmployer)a.push('Employer on permit: '+m.permitEmployer);if(m.cls)a.push(m.cls+(m.airBrake?', air brake':''));if(m.coverage)a.push('Coverage '+money(m.coverage));if(m.agreementVersion)a.push('Version '+m.agreementVersion);if(d.expiry)a.push('Expiry '+d.expiry);return esc(a.join(' · '));}
FORMS.reviewdoc=function(f,d){var doc=DB.docs.filter(function(x){return x.id===d.id;})[0],u=user(doc.userId);
  if(doc.kind==='cgl'&&!d.additionalInsured){toast('Tick the additional-insured box to approve the CGL certificate.');return;}
  if(DOCS[doc.kind].expiry===true&&!d.expiry){toast('Enter the expiry date.');return;}
  if(doc.kind==='eligibility'&&doc.meta.docType==='permit'&&!d.expiry){toast('Work permits need an expiry date.');return;}
  if(d.expiry!==undefined)doc.expiry=d.expiry;if(d.verifiedDate)doc.verifiedDate=d.verifiedDate;if(doc.kind==='cgl')doc.meta.additionalInsured=true;
  doc.status='approved';doc.reviewedBy=ME.name;doc.reviewedAt=new Date().toISOString();audit('Approved document',u.name,DOCS[doc.kind].label);notify(u.id,'Your '+DOCS[doc.kind].label+' was approved.');save();toast('Approved.');render();};
ACT.rejectdoc=function(el){var f=el.closest('form'),doc=DB.docs.filter(function(x){return x.id===el.dataset.id;})[0],u=user(doc.userId);var r=f.reason.value.trim();if(!r){toast('Type a reason for rejecting.');return;}doc.status='rejected';doc.reviewNote=r;doc.reviewedBy=ME.name;doc.reviewedAt=new Date().toISOString();audit('Rejected document',u.name,DOCS[doc.kind].label+': '+r);notify([u.id].concat(u.subId?[u.subId]:[]),'Your '+DOCS[doc.kind].label+' was not accepted: '+r+'. Please upload a new one.');save();render();};
ACT.approveacct=function(el){var u=user(el.dataset.id);if(u.type==='employee'&&!registrationComplete(u)){if(!confirmBox('appr'+u.id,'Registration is not complete yet. Approve anyway?'))return;}u.approved=true;u.approvedAt=today();audit('Approved registration',u.name);notify(u.id,'Your registration was approved by the UnScramble office.');save();toast('Approved.');render();};

/* ---------- People ---------- */
VIEWS['admin:people']=function(){var f=PAGE_STATE.pf||{type:'',hideTest:false,q:''};var list=DB.users.filter(function(u){return (!f.type||u.type===f.type)&&!(f.hideTest&&u.type==='tester')&&(!f.q||(u.name+' '+(u.username||'')+' '+(u.email||'')).toLowerCase().indexOf(f.q.toLowerCase())>=0);});
  return '<h1>People</h1><form data-form="pfilter" class="row">'+'<select name="type" style="max-width:240px"><option value="">All types</option>'+opt(Object.keys(TYPES).map(function(k){return [k,TYPES[k]];}),f.type)+'</select><input type="text" name="q" placeholder="Search name / username / email" value="'+esc(f.q)+'" style="max-width:260px">'+chk('hideTest','Hide testing accounts',f.hideTest)+'<button class="small">Filter</button></form>'+
  '<div class="tw"><table><tr><th>Name</th><th>Type</th><th>Login</th><th>Employer</th><th>Status</th><th></th></tr>'+list.map(function(u){var b=u.type==='admin'||u.type==='firm'?[]:u.type==='sub'?companyBlockers(u):blockers(u,today());return '<tr><td><b>'+esc(u.name)+'</b>'+(u.type==='tester'?' <span class="badge-test">TEST</span>':'')+(u.type==='sub'?' '+tempBadge(u):u.type==='worker'?' '+tempBadge(subOf(u)):'')+'</td><td>'+typePill(u)+'</td><td class="small">'+esc(u.username||'')+'<br>'+esc(u.email||'')+'</td><td class="small">'+(u.type==='worker'||u.type==='employee'?esc(employerName(u)):'')+'</td><td>'+(!u.active?'<span class="pill s-mut">Off</span>':u.suspended?'<span class="pill s-bad">Suspended</span>':b.length?'<span class="pill s-bad">Blocked ('+b.length+')</span>':'<span class="pill s-ok">OK</span>')+'</td><td><button class="small sec" data-act="person" data-id="'+u.id+'">Open</button></td></tr>';}).join('')+'</table></div>';};
FORMS.pfilter=function(f,d){PAGE_STATE.pf={type:d.type,q:d.q,hideTest:!!d.hideTest};render();};
ACT.person=function(el){showPerson(el.dataset.id);};
function showPerson(id){var u=user(id),p=u.profile||{},c=u.company||{};audit('Viewed person record',u.name);save();
  var x='<h2>'+esc(u.name)+' '+typePill(u)+'</h2><div class="kv"><div>Username / email</div><div>'+esc(u.username||'–')+' / '+esc(u.email||'–')+'</div><div>Phone</div><div>'+esc(u.phone||'(none)')+'</div><div>Created / last login</div><div>'+fmtStamp(u.createdAt)+' / '+(u.lastLogin?fmtStamp(u.lastLogin):'never')+'</div>'+(u.type==='worker'||u.type==='employee'?'<div>Employer</div><div>'+esc(employerName(u))+'</div>':'')+(u.convertedFrom?'<div>Converted</div><div>from Testing account on '+esc(u.convertedAt)+'</div>':'')+'</div>';
  if(u.type==='employee')x+='<h3>Payroll (restricted)</h3><div class="kv"><div>SIN</div><div>'+(p.sin?'•••••'+esc(dec(p.sin).slice(-3)):p.noSin?'<span class="pill s-bad">No SIN yet</span>':'missing')+(p.sinTemp?' <span class="pill s-warn">temporary – expires '+esc(p.sinExpiry||'?')+'</span>':'')+'</div><div>SIN requested on</div><div>'+esc(p.sinRequested||'–')+'</div><div>Date of birth</div><div>'+esc(p.dob||'–')+(p.dob&&daysBetween(p.dob,today())<18*365.25?' <span class="pill s-warn">under 18 – no CPP</span>':'')+'</div><div>Banking</div><div>'+(p.bankAcct?esc(p.bankInst)+'-'+esc(p.bankTransit)+' acct '+last(dec(p.bankAcct),4):'–')+(p.chequeApproved?' (cheque approved)':'')+'</div><div>Job / rate</div><div>'+esc(p.jobTitle||'')+' · '+(p.payRate?money(p.payRate)+'/h':'')+(Number(p.payRate)<DB.settings.minWage?' <span class="pill s-warn">below PEI min wage</span>':'')+'</div><div>TD1 claim code</div><div>'+(p.td1Amount!==''&&p.td1Amount!=null?esc(claimCode(p.td1Amount))+' ('+money(p.td1Amount)+')':'from uploaded form')+' · PEI: '+(p.td1peAmount?money(p.td1peAmount):'basic')+'</div></div>'+
   '<form data-form="emppay"><input type="hidden" name="id" value="'+u.id+'"><div class="grid2">'+sel('provEmp','Province of employment',[['PE','PEI'],['NS','NS'],['NB','NB']],p.provEmp||'PE')+inp('payRate','Hourly pay rate $ (office only)',p.payRate,{type:'number',extra:' step="0.01" min="0"'})+inp('wcbRate','WCB PEI rate / class',p.wcbRate)+inp('vacPct','Vacation %',p.vacPct||4,{type:'number'})+'</div>'+chk('chequeApproved','Approve pay by cheque instead of direct deposit',p.chequeApproved)+'<button class="small">Save payroll settings</button></form>';
  if(u.type==='sub')x+='<h3>Company</h3><div class="kv"><div>Legal / operating</div><div>'+esc(c.legalName)+' / '+esc(c.operatingName||'')+'</div><div>BN / RP / HST</div><div>'+esc(c.bn||'')+' / '+esc(c.rp||'')+' / '+esc(c.hstNotReq?'not registered':c.hst||'')+'</div><div>WCB account</div><div>'+esc(c.wcbAccount||'')+'</div><div>Banking</div><div>'+(c.bankAcct?last(dec(c.bankAcct),4)+(c.bankVerified?' (verified)':' (NOT verified)'):'–')+'</div><div>Agreement</div><div>'+agreementPill(u)+'</div><div>Main contact</div><div>'+esc((c.mainContact||{}).name||'')+' '+esc((c.mainContact||{}).email||'')+'</div><div>24/7 emergency</div><div>'+esc((c.emergency||{}).name||'')+' '+esc((c.emergency||{}).phone||'')+'</div><div>Supervisors</div><div>'+esc(c.supervisors||'')+'</div></div>'+terminateBox(u)+'<h3>14-day document pass</h3>'+tempSection(u);
  if(u.type!=='admin'&&u.type!=='firm'&&u.type!=='tester'){x+='<h3>Checklist</h3><ul class="check">'+requirements(u).map(function(r){return '<li>'+pill(r.st)+'<div class="small">'+esc(r.label)+'</div></li>';}).join('')+'</ul>';
    var ds=DB.docs.filter(function(d){return d.userId===u.id;});if(ds.length)x+='<h3>Documents</h3><div class="small">'+ds.map(function(d){return '<a href="#" data-act="viewdoc" data-id="'+d.id+'">'+esc(DOCS[d.kind].label)+'</a> – '+pill(docStatus(d))+' '+esc(d.status)+' '+metaText(d);}).join('<br>')+'</div>';}
  if(u.type==='worker'||u.type==='employee')x+='<h3>Site orientations</h3><form data-form="orient"><input type="hidden" name="id" value="'+u.id+'">'+(typeof companySites==='function'?companySites({withFirm:true}):DB.sites.filter(function(s){return s.firmId;})).map(function(s){return chk('sites[]',esc(s.code+' – '+s.name),(u.orientations||[]).indexOf(s.code)>=0,{value:s.code});}).join('')+'<button class="small sec">Save orientations</button></form>';
  x+='<h3>Actions</h3><div class="row">'+(u.type!=='admin'?'<button class="small sec" data-act="toggleactive" data-id="'+u.id+'">'+(u.active?'Switch account off':'Switch account on')+'</button>':'')+(u.type==='sub'||u.type==='worker'||u.type==='employee'?'<button class="small '+(u.suspended?'sec':'danger')+'" data-act="suspend" data-id="'+u.id+'">'+(u.suspended?'Lift suspension':'Suspend')+'</button>':'')+(u.type==='sub'||u.type==='employee'?(u.approved?'':'<button class="small" data-act="approveacct" data-id="'+u.id+'">Approve registration</button>'):'')+'</div>';
  x+='<form data-form="adminpw" class="row" style="margin-top:8px"><input type="hidden" name="id" value="'+u.id+'"><input type="text" name="pw" placeholder="New temporary password" style="max-width:220px" required><button class="small sec">Reset password</button></form>';
  modal(x);}
FORMS.emppay=function(f,d){var u=user(d.id);var p=u.profile;var ch=p.provEmp!==d.provEmp;if(d.payRate!==undefined&&String(d.payRate)!==String(p.payRate||'')){var old=p.payRate;p.payRate=Number(d.payRate)||'';audit('Office set employee pay rate',u.name,(old?money(old):'none')+' → '+money(p.payRate));flagWagepoint(u,'pay rate');notify(u.id,'The office set your hourly pay rate to '+money(p.payRate)+'.');if(Number(p.payRate)<DB.settings.minWage)toast('Note: below PEI minimum wage.');}p.provEmp=d.provEmp;p.wcbRate=d.wcbRate;p.vacPct=d.vacPct;p.chequeApproved=!!d.chequeApproved;if(ch)flagWagepoint(u,'province');audit('Office changed payroll settings',u.name);save();toast('Saved.');showPerson(u.id);};
FORMS.orient=function(f,d){var u=user(d.id);u.orientations=d.sites||[];audit('Recorded site orientations',u.name,u.orientations.join(', '));save();toast('Saved.');showPerson(u.id);};
FORMS.adminpw=function(f,d){if(d.pw.length<6){toast('At least 6 characters.');return;}var u=user(d.id);u.passHash=hashPw(d.pw);audit('Office reset password',u.name);notify(u.id,'The office reset your password.');save();toast('Password reset. Tell the person their temporary password.');};
ACT.toggleactive=function(el){var u=user(el.dataset.id);u.active=!u.active;audit(u.active?'Switched account on':'Switched account off',u.name);save();closeModal();render();};
ACT.suspend=function(el){var u=user(el.dataset.id);u.suspended=!u.suspended;audit(u.suspended?'Suspended':'Lifted suspension',u.name);notify([u.id].concat(u.subId?[u.subId]:[]),u.suspended?'Your account was suspended by the office.':'Your suspension was lifted.');save();sweepBookings();save();closeModal();render();};

/* ---------- Compliance ---------- */
function cell(d){var st=docStatus(d);var l=st.ex?daysBetween(today(),st.ex):null;var c=st.s==='Valid'?'s-ok':st.s==='Expiring soon'?'s-warn':st.s==='Pending review'?'s-pend':'s-bad';return '<span class="pill '+c+'">'+esc(st.s)+'</span>'+(st.ex?'<div class="small">'+esc(st.ex)+(l!==null&&l>0?' ('+l+'d)':'')+'</div>':'');}
VIEWS['admin:compliance']=function(){
  var x='<h1>Compliance</h1><h2>14-day document pass (subcontractors and their workers)</h2>'+users('sub').map(tempSection).join('')+users('worker').filter(function(w){return w.active&&(tempInfo(w)||!workerDocsComplete(w));}).map(tempSection).join('')+'<p class="small"><span class="pill s-ok">green Valid</span> <span class="pill s-warn">amber expiring within 30 days</span> <span class="pill s-bad">red Expired / Missing</span> <span class="pill s-pend">blue Pending review</span></p><h2>Subcontractors</h2><div class="tw"><table><tr><th>Subcontractor</th><th>WCB (as required by PEI law, and no later than the end of year 1)</th><th>CGL insurance</th><th>Auto</th><th>Agency licence</th><th>Agreement</th><th>Payment hold</th></tr>'+
  users('sub').map(function(s){var c=s.company||{},l=c.agreementEnd?daysBetween(today(),c.agreementEnd):null;return '<tr><td><a href="#" data-act="person" data-id="'+s.id+'">'+esc(c.legalName||s.name)+'</a> '+tempBadge(s)+'</td><td>'+(wcbRequired(s)?cell(latestDoc(s.id,'wcb_clearance')):'<span class="pill s-ok">Not required yet</span>'+(latestDoc(s.id,'wcb_clearance')?' '+cell(latestDoc(s.id,'wcb_clearance')):''))+'<div class="small muted">'+esc(wcbRuleText(s))+'</div><button class="small sec" data-act="wcbnow" data-id="'+s.id+'">'+(s.company&&s.company.wcbRequiredNow?'Undo "required now"':'Mark WCB required now')+'</button></td><td>'+cell(latestDoc(s.id,'cgl'))+'</td><td>'+(c.drivesWorkers?cell(latestDoc(s.id,'auto')):'<span class="small muted">n/a</span>')+'</td><td>'+(c.licenceNotReq?'<span class="pill '+(c.licenceNotReqConfirmed?'s-ok':'s-pend')+'">Not required'+(c.licenceNotReqConfirmed?' ✓':' (confirm)')+'</span>':cell(latestDoc(s.id,'agency_licence')))+'</td><td>'+agreementPill(s)+'</td><td class="small">'+esc(paymentHold(s).join('; ')||'–')+'</td></tr>';}).join('')+'</table></div>';
  x+='<h2>Workers and employees</h2><div class="tw"><table><tr><th>Name</th><th>Employer</th><th>Eligibility / permit</th><th>Driver licence</th><th>Forklift / machinery</th><th>Training refresh</th></tr>'+realPeople().map(function(u){var sx=safetyExpiry(u);return '<tr><td><a href="#" data-act="person" data-id="'+u.id+'">'+esc(u.name)+'</a></td><td class="small">'+esc(employerName(u))+'</td><td>'+(u.type==='employee'?cell(latestDoc(u.id,'eligibility')):'<span class="small muted">n/a – employer checks</span>')+'</td><td>'+(hasRole(u,'driver')?cell(latestDoc(u.id,'driver_licence')):'<span class="small muted">n/a</span>')+'</td><td>'+(hasRole(u,'forklift')||hasRole(u,'machinery')?cell(latestDoc(u.id,'forklift')):'<span class="small muted">n/a</span>')+'</td><td>'+(sx?'<span class="pill '+colour(daysBetween(today(),sx))+'">'+esc(sx)+'</span>':'<span class="pill s-bad">Missing</span>')+'</td></tr>';}).join('')+'</table></div>';
  var ex=expiringList();x+='<h2>Expiring in the next 30 days</h2>'+expTable(ex.filter(function(e){return e.left>0&&e.left<=30;}))+'<h2>Expired</h2>'+expTable(ex.filter(function(e){return e.left<=0;}))+'<h2>Blocked list</h2>'+blockedTable(blockedList());
  return x;};

/* ---------- Practice / temporary mode (office) ---------- */
function tempSection(sub){var c=sub.company||{},i=tempInfo(sub),raw=companyBlockersRaw(sub),hist=c.tempHistory||[];
  var x='<div class="card temp-card" id="temp-'+sub.id+'"><div class="row"><b>'+esc(c.legalName||sub.name)+'</b>'+(i&&i.active?tempBadge(sub):'<span class="pill '+(raw.length?'s-bad':'s-ok')+'">'+(raw.length?'Not compliant':'Compliant')+'</span>')+'</div>';
  if(raw.length)x+='<div class="small" style="margin:4px 0">Compliance issues: '+esc(raw.join(' '))+'</div>';
  if(i&&i.active){x+='<div class="small">On since '+esc(i.t.start)+' by '+esc(i.t.by)+' · Reason: <i>'+esc(i.t.reason)+'</i> · Payments on hold: <b>'+money(heldAmount(sub))+'</b></div><form data-form="tempext" class="row" style="margin-top:6px"><input type="hidden" name="id" value="'+sub.id+'"><input type="date" name="end" value="'+esc(i.t.end)+'" max="'+addDays(i.t.start,30)+'" style="max-width:170px"><button class="small sec">Change end date</button><button class="small danger" data-act="tempoff" data-id="'+sub.id+'">End temporary mode now</button></form>';}
  else x+='<form data-form="tempon" style="margin-top:6px"><input type="hidden" name="id" value="'+sub.id+'"><div class="grid2">'+inp('end','End date (required – default 14 days, max 30)',addDays(today(),14),{type:'date',req:true,extra:' min="'+today()+'" max="'+addDays(today(),30)+'"'})+inp('reason','Reason (required)','',{req:true,ph:'e.g. insurance renewal in progress, crews needed at Test Farm A'})+'</div><div class="hint">While on: their workers can work and clock crew shifts at sites; those hours are billed to the farm as normal; the subcontractor\'s own invoices/payments are held until they are compliant. Ends automatically – if still not compliant they are blocked again.</div><button class="small">Turn on Practice / temporary mode</button></form>';
  if(hist.length)x+='<details class="small"><summary>History</summary><ul>'+hist.slice().reverse().map(function(h){return '<li>'+fmtStamp(h.at)+' – '+esc(h.what)+(h.end?' (end '+esc(h.end)+')':'')+(h.reason?' – '+esc(h.reason):'')+' – '+esc(h.by)+'</li>';}).join('')+'</ul></details>';
  return x+'</div>';}
FORMS.tempon=function(f,d){var sub=user(d.id),c=sub.company;if(!d.reason){toast('A reason is required.');return;}if(!d.end||d.end<today()){toast('Choose an end date from today on.');return;}if(d.end>addDays(today(),30)){toast('Temporary mode can last 30 days at most.');return;}
  c.temp={on:true,start:today(),end:d.end,reason:d.reason,by:ME.name,at:new Date().toISOString()};(c.tempHistory=c.tempHistory||[]).push({what:'Turned on',at:c.temp.at,end:d.end,reason:d.reason,by:ME.name});
  DB.invoices.forEach(function(i){if(i.subId===sub.id&&!i.test&&i.status!=='Paid')i.heldTemp=true;});
  notify(sub.id,'UnScramble turned on Practice / temporary mode for your company until '+d.end+' ('+d.reason+'). Your crews can keep working; your invoices/payments are on hold until you are compliant.');
  audit('Turned on temporary mode',c.legalName,'until '+d.end+': '+d.reason);save();toast('Temporary mode is on until '+d.end+'.');render();};
FORMS.tempext=function(f,d){var sub=user(d.id),t=sub.company.temp;if(d.end<today()||d.end>addDays(t.start,30)){toast('End date must be between today and '+addDays(t.start,30)+' (30 days max).');return;}t.end=d.end;sub.company.tempHistory.push({what:'End date changed',at:new Date().toISOString(),end:d.end,by:ME.name});audit('Changed temporary mode end',sub.name,d.end);notify(sub.id,'Your temporary mode now ends on '+d.end+'.');save();render();};
ACT.tempoff=function(el){var sub=user(el.dataset.id),t=sub.company.temp;t.on=false;sub.company.tempHistory.push({what:'Ended early by office',at:new Date().toISOString(),end:t.end,by:ME.name});audit('Ended temporary mode',sub.name);notify(sub.id,'Temporary mode for your company was ended by the office.'+(companyCompliant(sub)?'':' You are blocked until compliant.'));sweepBookings();save();render();};

/* ---------- Terms admin ---------- */
VIEWS['admin:termsadmin']=function(){var S=DB.settings.terms;
  var x='<h1>Terms acceptance</h1><div class="tw"><table><tr><th>Terms</th><th>Current version</th><th>Published</th><th>Accepted current</th><th>Still need to accept</th></tr>';
  Object.keys(TERMS_DEF).forEach(function(k){var who=DB.users.filter(function(u){return TERMS_DEF[k].types.indexOf(u.type)>=0&&u.active;});var need=who.filter(function(u){return !acceptedCurrent(u,k);});x+='<tr><td>'+esc(TERMS_DEF[k].name)+'</td><td>'+esc(S[k].version)+'</td><td>'+esc(S[k].publishedAt)+'</td><td>'+(who.length-need.length)+'/'+who.length+'</td><td class="small">'+(need.map(function(u){return esc(u.name);}).join(', ')||'–')+'</td></tr>';});
  x+='</table></div><div class="card hl"><h2 style="margin-top:0">Publish a new version</h2><p class="small">Everyone affected is asked to accept again on their next sign-in, and is blocked from shifts until they do.</p><form data-form="publish">'+sel('key','Terms',Object.keys(TERMS_DEF).map(function(k){return [k,TERMS_DEF[k].name];}),'')+inp('version','New version number','',{req:true,ph:'e.g. 1.1'})+'<label>Text (leave as is to keep the current text)</label><textarea name="text" style="min-height:120px">'+esc(S.app_testing.text)+'</textarea><div class="hint">Tip: choose the terms first, then edit the text. For Schedule C, {EMPLOYER} is replaced with the worker\'s employer.</div><label>Existing booked shifts for people who have not accepted yet</label>'+'<label class="inline"><input type="radio" name="keep" value="keep" checked> Keep their booked shifts</label><label class="inline"><input type="radio" name="keep" value="release"> Release their booked shifts</label><button>Publish new version</button></form></div>';
  x+='<h2>All acceptances (permanent history)</h2><div class="tw"><table><tr><th>Who</th><th>Terms</th><th>Version</th><th>Date/time</th><th>Time zone</th><th>Device / IP</th></tr>'+DB.acceptances.slice().reverse().map(function(a){var u=user(a.userId);return '<tr><td>'+esc(a.userName)+(u?'<div class="small muted">'+esc(TYPES[u.type])+'</div>':'')+'</td><td>'+esc(a.name)+(a.employerName?'<div class="small muted">employer: '+esc(a.employerName)+'</div>':'')+'</td><td>'+esc(a.version)+'</td><td>'+fmtStamp(a.at)+'</td><td>'+esc(a.tz)+'</td><td class="small">'+esc(a.device)+'</td></tr>';}).join('')+'</table></div>';
  PAGE_STATE.after=function(){var f=document.querySelector('[data-form=publish]');if(!f)return;f.key.addEventListener('change',function(){f.text.value=DB.settings.terms[f.key.value].text;});};
  return x;};
FORMS.publish=function(f,d){var cur=DB.settings.terms[d.key];if(d.version===cur.version){toast('Use a new version number.');return;}
  DB.settings.termsHistory=DB.settings.termsHistory||[];DB.settings.termsHistory.push({key:d.key,version:cur.version,text:cur.text});
  DB.settings.terms[d.key]={version:d.version,publishedAt:today(),text:d.text||cur.text};
  var affected=DB.users.filter(function(u){return TERMS_DEF[d.key].types.indexOf(u.type)>=0;});
  affected.forEach(function(u){notify(u.id,'New version '+d.version+' of the '+TERMS_DEF[d.key].name+' – please sign in and accept it.');});
  if(d.keep==='release'){var n=0;DB.shifts.forEach(function(s){if(s.date<today())return;var before=s.booked.length;s.booked=s.booked.filter(function(id){return affected.every(function(u){return u.id!==id;});});n+=before-s.booked.length;});toast('Released '+n+' booking(s).');}
  audit('Published new terms version',TERMS_DEF[d.key].name,'v'+d.version+' ('+d.keep+' booked shifts)');save();render();};

/* ---------- Invoices admin ---------- */
VIEWS['admin:invoicesadmin']=function(){var f=PAGE_STATE.if||{status:'',sub:'',farm:'',from:'',to:'',test:false};
  var list=DB.invoices.filter(function(i){return (f.test?true:!i.test)&&(!f.status||i.status===f.status)&&(!f.sub||i.subId===f.sub)&&(!f.farm||(i.farms||'').toLowerCase().indexOf(f.farm.toLowerCase())>=0)&&(!f.from||i.date>=f.from)&&(!f.to||i.date<=f.to);}).sort(function(a,b){return a.date<b.date?1:-1;});
  PAGE_STATE.invList=list;var real=list.filter(function(i){return !i.test;});
  var x='<h1>Subcontractor invoices</h1><form data-form="ifilter" class="row">'+'<select name="status" style="max-width:150px"><option value="">All statuses</option>'+opt(['Submitted','Approved','Paid','Disputed'],f.status)+'</select><select name="sub" style="max-width:220px"><option value="">All subcontractors</option>'+opt(users('sub').map(function(s){return [s.id,s.company.legalName];}),f.sub)+'</select><input type="text" name="farm" placeholder="Farm" value="'+esc(f.farm)+'" style="max-width:130px"><input type="date" name="from" value="'+esc(f.from)+'" style="max-width:150px"><input type="date" name="to" value="'+esc(f.to)+'" style="max-width:150px">'+chk('test','Show TEST invoices',f.test)+'<button class="small">Filter</button><button class="small sec" data-act="invcsv">Export CSV (Excel)</button></form>';
  x+='<div class="tw"><table><tr><th>Invoice #</th><th>Subcontractor / BN / HST</th><th>Period</th><th>Subtotal</th><th>HST</th><th>Total</th><th>Holdback / set-off</th><th>Submitted</th><th>Due</th><th>Paid</th><th>Status</th><th>PDF</th><th>Actions</th></tr>'+list.map(function(i){var od=!i.test&&i.status!=='Paid'&&i.due&&i.due<today();return '<tr class="'+(od?'overdue':'')+'"><td><a href="#" data-act="showinv" data-id="'+i.id+'">'+esc(i.number)+'</a>'+(i.test?' <span class="badge-test">TEST</span>':'')+(i.detailsChanged&&!i.detailsReviewed?' <span class="pill s-warn">details changed</span>':'')+'</td><td class="small">'+esc(i.legalName)+'<br>BN '+esc(i.bn)+(i.hstNo?'<br>HST '+esc(i.hstNo):'')+'</td><td class="small">'+esc(i.periodStart)+'<br>'+esc(i.periodEnd)+'</td><td>'+money(i.subtotal)+'</td><td>'+money(i.hst)+'</td><td><b>'+money(i.total)+'</b></td><td class="small">'+(i.holdback?money(i.holdback):'–')+' / '+(i.setoff?money(i.setoff):'–')+'</td><td class="small">'+esc(i.submittedAt||'')+'</td><td class="small">'+esc(i.due||'')+(od?' <b style="color:#c0392b">OVERDUE</b>':'')+'</td><td class="small">'+esc(i.paidDate||'')+(i.paidRef?'<br>'+esc(i.paidRef):'')+'</td><td>'+(i.test?'<span class="unpaid">TEST – NEVER PAID</span>':esc(i.status))+(invoiceHeld(i)?' <span class="pill s-bad">PAYMENT ON HOLD</span> '+tempBadge(user(i.subId)):'')+'</td><td>'+(i.pdf?'<a href="#" data-act="invpdf" data-id="'+i.id+'">file</a>':'')+'</td><td>'+(i.test?'<span class="small muted">No actions – test</span>':'<button class="small" data-act="invact" data-a="approve" data-id="'+i.id+'"'+(i.status!=='Submitted'&&i.status!=='Disputed'?' disabled':'')+'>Approve</button><button class="small sec" data-act="invact" data-a="dispute" data-id="'+i.id+'"'+(i.status==='Paid'?' disabled':'')+'>Dispute</button><button class="small sec" data-act="invact" data-a="paid" data-id="'+i.id+'"'+(i.status!=='Approved'||invoiceHeld(i)?' disabled':'')+'>Mark paid</button><button class="small sec" data-act="invact" data-a="hold" data-id="'+i.id+'"'+(i.status==='Paid'?' disabled':'')+'>Holdback / set-off</button>')+'</td></tr>';}).join('')+'</table></div>';
  var sum=function(k){return real.reduce(function(a,i){return a+(i[k]||0);},0);};
  x+='<p><b>Real invoice totals (TEST invoices always excluded):</b> subtotal '+money(sum('subtotal'))+' · HST '+money(sum('hst'))+' · total '+money(sum('total'))+' · holdback '+money(sum('holdback'))+'</p>';
  return x;};
FORMS.ifilter=function(f,d){PAGE_STATE.if={status:d.status,sub:d.sub,farm:d.farm,from:d.from,to:d.to,test:!!d.test};render();};
ACT.invcsv=function(){var rows=[['Invoice #','Test','Subcontractor','BN','HST #','Period start','Period end','Subtotal','HST','Total','Holdback','Set-off','Submitted','Due','Paid date','Paid ref','Status','Farms','Work orders']];(PAGE_STATE.invList||[]).forEach(function(i){rows.push([i.number,i.test?'TEST – never paid':'',i.legalName,i.bn,i.hstNo,i.periodStart,i.periodEnd,i.subtotal,i.hst,i.total,i.holdback,i.setoff,i.submittedAt,i.due,i.paidDate,i.paidRef,i.test?'TEST':i.status,i.farms,i.workOrders]);});downloadText('unscramble-invoices-TEST-'+today()+'.csv',rows.map(csvRow).join('\n'),'text/csv');audit('Exported invoices CSV');save();};
ACT.invact=function(el){var i=DB.invoices.filter(function(x){return x.id===el.dataset.id;})[0];if(i.test){toast('TEST invoices can never be approved or paid.');return;}var a=el.dataset.a;
  if(a==='paid'&&invoiceHeld(i)){toast('Payment on hold: this subcontractor is in (or left) Practice / temporary mode and is not compliant yet.');return;}
  if(a==='approve'){i.status='Approved';i.history.push({at:new Date().toISOString(),what:'Approved',by:ME.name});notify(i.subId,'Invoice '+i.number+' was approved.');audit('Approved invoice',i.number);save();render();return;}
  var body=a==='dispute'?'<label class="req">Reason / message to the subcontractor</label><textarea name="reason" required></textarea>':a==='paid'?'<div class="grid2">'+inp('date','Paid date',today(),{type:'date',req:true})+inp('ref','Payment reference',"",{req:true})+'</div>':'<div class="grid2">'+inp('holdback','Holdback $',i.holdback||0,{type:'number',extra:' step="0.01" min="0"'})+inp('setoff','Set-off $',i.setoff||0,{type:'number',extra:' step="0.01" min="0"'})+inp('setoffNote','Set-off reason',i.setoffNote||'')+'</div>';
  modal('<h2>Invoice '+esc(i.number)+' – '+({dispute:'Dispute',paid:'Mark paid',hold:'Holdback / set-off'}[a])+'</h2><form data-form="invact"><input type="hidden" name="id" value="'+i.id+'"><input type="hidden" name="a" value="'+a+'">'+body+'<p><button>Save</button></p></form>');};
FORMS.invact=function(f,d){var i=DB.invoices.filter(function(x){return x.id===d.id;})[0];
  if(d.a==='dispute'){i.status='Disputed';i.disputeReason=d.reason;notify(i.subId,'Invoice '+i.number+' is disputed: '+d.reason);}
  if(d.a==='paid'){i.status='Paid';i.paidDate=d.date;i.paidRef=d.ref;notify(i.subId,'Invoice '+i.number+' was paid on '+d.date+' (ref '+d.ref+').');}
  if(d.a==='hold'){i.holdback=Number(d.holdback)||0;i.setoff=Number(d.setoff)||0;i.setoffNote=d.setoffNote;}
  i.history.push({at:new Date().toISOString(),what:d.a==='dispute'?'Disputed: '+d.reason:d.a==='paid'?'Paid '+d.date+' ref '+d.ref:'Holdback '+money(i.holdback)+', set-off '+money(i.setoff),by:ME.name});audit('Invoice '+d.a,i.number);save();closeModal();render();};

/* ---------- Records requests ---------- */
VIEWS['admin:recordsadmin']=function(){return '<h1>Records requests</h1><div class="card hl"><form data-form="newrec">'+sel('subId','Subcontractor',users('sub').map(function(s){return [s.id,s.company.legalName];}),'',{req:true})+'<label class="req">What do you need?</label><textarea name="text" required>Please send your payroll records, worker names and dates/hours worked for the period.</textarea><div class="hint">Due date is set to 5 business days from today ('+addBusinessDays(today(),5)+').</div><button>Send request</button></form></div><div class="tw"><table><tr><th>Subcontractor</th><th>Request</th><th>Sent</th><th>Due</th><th>Status</th><th>Files</th><th></th></tr>'+DB.records.map(function(r){var od=r.status==='Open'&&r.due<today();return '<tr class="'+(od?'overdue':'')+'"><td>'+esc((user(r.subId)||{}).name)+'</td><td class="small">'+esc(r.text)+'</td><td>'+esc(r.sentAt)+'</td><td>'+esc(r.due)+'</td><td>'+(od?'<span class="pill s-bad">OVERDUE</span>':'<span class="pill '+(r.status==='Open'?'s-pend':'s-ok')+'">'+esc(r.status)+'</span>')+'</td><td class="small">'+r.files.map(function(f,ix){return '<a href="#" data-act="recfile" data-id="'+r.id+'" data-i="'+ix+'">'+esc(f.name)+'</a>';}).join('<br>')+'</td><td>'+(r.status!=='Closed'?'<button class="small sec" data-act="closerec" data-id="'+r.id+'">Close</button>':'')+'</td></tr>';}).join('')+'</table></div>';};
FORMS.newrec=function(f,d){var r={id:uid('r'),subId:d.subId,text:d.text,sentAt:today(),due:addBusinessDays(today(),5),status:'Open',files:[]};DB.records.unshift(r);notify(d.subId,'Records request from UnScramble (due '+r.due+'): '+d.text);audit('Sent records request',(user(d.subId)||{}).name);save();toast('Request sent.');render();};
ACT.closerec=function(el){var r=DB.records.filter(function(x){return x.id===el.dataset.id;})[0];r.status='Closed';audit('Closed records request',(user(r.subId)||{}).name);save();render();};

/* ---------- Wagepoint ---------- */
function wpStatus(u){var w=u.wagepoint||{};if(w.added)return w.update&&w.update.length?'<span class="pill s-warn">Update Wagepoint: '+esc(w.update.join(', '))+'</span>':'<span class="pill s-ok">Added '+esc(w.date)+' by '+esc(w.by)+'</span>';if(u.approved&&registrationComplete(u))return '<span class="pill s-pend">Ready for Wagepoint</span>';return '<span class="pill s-mut">Registration not complete'+(u.approved?'':' / not approved')+'</span>';}
var WP_FIELDS=function(u,sens){var p=u.profile||{};return [
 ['Basic information','Legal first name',p.firstName],['Basic information','Middle name',p.middleName],['Basic information','Legal last name',p.lastName],['Basic information','Preferred name',p.preferredName],['Basic information','Personal email',u.email],['Basic information','Phone',u.phone],['Basic information','Date of birth',p.dob],['Basic information','SIN',sens?dec(p.sin):(p.sin?'•••••'+dec(p.sin).slice(-3):(p.noSin?'NO SIN YET':''))],['Basic information','Province of employment',p.provEmp],['Basic information','Payment method',p.chequeApproved?'Cheque (approved)':'Direct deposit'],['Basic information','Institution',p.bankInst],['Basic information','Transit',p.bankTransit],['Basic information','Account',sens?dec(p.bankAcct):last(dec(p.bankAcct),4)],['Basic information','Emergency contact',[p.emName,p.emRel,p.emPhone,p.emEmail].filter(Boolean).join(' / ')],
 ['Home address','Street',p.street],['Home address','City',p.city],['Home address','Province',p.prov],['Home address','Postal code',p.postal],
 ['Job details','Start (hire) date',p.startDate],['Job details','First day worked',p.firstDay],['Job details','Job title',p.jobTitle],['Job details','Department',p.dept],['Job details','Pay type','Hourly'],['Job details','Hourly rate',p.payRate],['Job details','Pay group','Bi-weekly'],['Job details','Vacation pay',(p.vacPct||4)+'% '+(p.vacMethod==='accrued'?'accrued each pay':'paid out each cheque')],['Job details','WCB PEI rate',p.wcbRate],
 ['Tax information','Federal TD1 claim amount',p.td1Amount],['Tax information','Federal claim code (estimate)',p.td1Amount!==''&&p.td1Amount!=null?claimCode(p.td1Amount):'see uploaded TD1'],['Tax information','PEI TD1PE claim amount',p.td1peAmount||'Basic'],['Tax information','Additional tax per pay',p.extraTax],
 ['Prior payrolls','Paid by UnScramble this year outside Wagepoint',p.priorPayroll]];};
VIEWS['admin:wagepoint']=function(){var emps=users('employee');
  return '<h1>Wagepoint payroll setup</h1><p class="small muted">Wagepoint has no bulk import for new people – use the copy screen to type details into Wagepoint (People › People list › Add people). Employees cannot be booked on shifts until "Added to Wagepoint" is ticked (or overridden with a note).</p><div class="row"><label class="inline"><input type="checkbox" id="wpsens"> Include sensitive fields (SIN, full bank numbers) in CSV – this is logged</label><button class="small sec" data-act="wpcsv" data-id="all">Download batch CSV (ready employees)</button></div><div class="tw"><table><tr><th>Employee</th><th>Status</th><th>Actions</th></tr>'+emps.map(function(u){var w=u.wagepoint||{};return '<tr><td><a href="#" data-act="person" data-id="'+u.id+'">'+esc(u.name)+'</a>'+(w.override?'<div class="small">Override: '+esc(w.override)+'</div>':'')+'</td><td>'+wpStatus(u)+(!w.added?'<div class="small">Payroll setup pending</div>':'')+'</td><td><button class="small sec" data-act="wpcopy" data-id="'+u.id+'">Copy screen</button><button class="small sec" data-act="wpcsv" data-id="'+u.id+'">CSV</button>'+(w.added?(w.update&&w.update.length?'<button class="small" data-act="wpupdated" data-id="'+u.id+'">Confirm updated in Wagepoint</button>':''):'<button class="small" data-act="wpadded" data-id="'+u.id+'">Tick "Added to Wagepoint"</button><button class="small sec" data-act="wpoverride" data-id="'+u.id+'">Override</button>')+'</td></tr>';}).join('')+'</table></div><p class="small muted">Delete downloaded files after use. Next payroll cut-off: '+esc(DB.settings.payrollCutoff||'–')+' (change in Settings).</p>';};
ACT.wpcsv=function(el){var sens=document.getElementById('wpsens').checked;var list=el.dataset.id==='all'?users('employee').filter(function(u){return u.approved&&registrationComplete(u)&&!(u.wagepoint&&u.wagepoint.added);}):[user(el.dataset.id)];if(!list.length){toast('No employees are ready for Wagepoint.');return;}
  var head=WP_FIELDS(list[0],false).map(function(f){return f[1];});var rows=[head].concat(list.map(function(u){return WP_FIELDS(u,sens).map(function(f){return f[2];});}));
  downloadText('wagepoint-'+(list.length>1?'batch':list[0].name.replace(/\W+/g,'-'))+'-TEST.csv',rows.map(csvRow).join('\n'),'text/csv');audit('Downloaded Wagepoint CSV'+(sens?' WITH SENSITIVE FIELDS':' (masked)'),list.map(function(u){return u.name;}).join(', '));save();};
ACT.wpcopy=function(el){var u=user(el.dataset.id);modal('<h2>Wagepoint copy screen – '+esc(u.name)+'</h2><form data-form="wpreauth" class="row"><input type="hidden" name="id" value="'+u.id+'"><input type="password" name="pw" placeholder="Re-enter your password to show SIN / bank" style="max-width:280px"><button class="small sec">Show sensitive fields</button></form><div id="wpcopy">'+wpCopyHtml(u,false)+'</div>');audit('Opened Wagepoint copy screen',u.name);save();};
function wpCopyHtml(u,sens){var last_='';return WP_FIELDS(u,sens).map(function(f){var h=f[0]!==last_?'<h3>'+esc(f[0])+'</h3>':'';last_=f[0];return h+'<div class="copyrow"><div class="k">'+esc(f[1])+'</div><div class="v">'+esc(f[2]==null?'':f[2])+'</div><button class="small sec" data-act="copy" data-v="'+esc(f[2]==null?'':f[2])+'">Copy</button></div>';}).join('');}
FORMS.wpreauth=function(f,d){if(ME.passHash!==hashPw(d.pw)){toast('Password does not match.');return;}var u=user(d.id);document.getElementById('wpcopy').innerHTML=wpCopyHtml(u,true);audit('Re-authenticated and viewed SIN/bank (Wagepoint copy)',u.name);save();};
ACT.copy=function(el){var v=el.dataset.v;function fb(){var t=document.createElement('textarea');t.value=v;document.body.appendChild(t);t.select();try{document.execCommand('copy');}catch(e){}t.remove();toast('Copied.');}
  if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(v).then(function(){toast('Copied.');},fb);}else fb();};
ACT.wpadded=function(el){var u=user(el.dataset.id);if(!(u.approved&&registrationComplete(u))&&!confirmBox('wp'+u.id,'Registration is not complete/approved.'))return;u.wagepoint={added:true,date:today(),by:ME.name,update:[]};audit('Ticked Added to Wagepoint',u.name);notify(u.id,'You were added to UnScramble payroll (Wagepoint).');save();render();};
ACT.wpupdated=function(el){var u=user(el.dataset.id);audit('Confirmed Wagepoint updated',u.name,u.wagepoint.update.join(', '));u.wagepoint.update=[];save();render();};
ACT.wpoverride=function(el){var u=user(el.dataset.id);modal('<h2>Override – allow shifts before Wagepoint</h2><form data-form="wpoverride"><input type="hidden" name="id" value="'+u.id+'"><label class="req">Note (required)</label><textarea name="note" required></textarea><button>Save override</button></form>');};
FORMS.wpoverride=function(f,d){var u=user(d.id);u.wagepoint=u.wagepoint||{};u.wagepoint.override=d.note+' ('+ME.name+', '+today()+')';audit('Wagepoint override',u.name,d.note);save();closeModal();render();};

/* ---------- Testers ---------- */
VIEWS['admin:testers']=function(){var t=users('tester'),req=DB.convReq.filter(function(r){return r.status==='Requested';});
  var x='<h1>Testing for App Development accounts</h1><p class="small muted">Testers need no documents. Their shifts, hours and invoices are TEST records – never paid and excluded from real totals, payroll, Wagepoint and firm billing.</p>';
  if(req.length)x+='<div class="alert warn"><b>Conversion requests:</b> '+req.map(function(r){var u=user(r.userId);return esc(u?u.name:'?')+' → '+esc(TYPES[r.to])+' <button class="small" data-act="convert" data-id="'+r.userId+'" data-to="'+r.to+'">Approve &amp; convert</button>';}).join(' ')+'</div>';
  x+='<div class="row"><button class="small danger" data-act="testersoff">Switch ALL testing accounts off</button></div><div class="tw"><table><tr><th>Name</th><th>Username / email</th><th>Created</th><th>Last login</th><th>Terms accepted</th><th>Data-use consent</th><th>Status</th><th>Actions</th></tr>'+t.map(function(u){var a=DB.acceptances.filter(function(x){return x.userId===u.id&&x.key==='app_testing';}).pop(),c=consentOf(u);return '<tr><td><b>'+esc(u.name)+'</b> <span class="badge-test">TEST</span></td><td class="small">'+esc(u.username||'')+'<br>'+esc(u.email||'')+'</td><td class="small">'+fmtStamp(u.createdAt)+'</td><td class="small">'+(u.lastLogin?fmtStamp(u.lastLogin):'never')+'</td><td class="small">'+(a?'v'+esc(a.version)+' ('+fmtStamp(a.at)+')':'<span class="pill s-bad">not accepted</span>')+'</td><td>'+(c&&c.choice?'Yes':'No')+'</td><td>'+(u.active?'<span class="pill s-ok">Active</span>':'<span class="pill s-mut">Off</span>')+'</td><td><button class="small sec" data-act="toggleactive" data-id="'+u.id+'">'+(u.active?'Switch off':'Switch on')+'</button><button class="small" data-act="convert" data-id="'+u.id+'" data-to="employee">Convert to Employee</button><button class="small" data-act="convert" data-id="'+u.id+'" data-to="sub">Convert to Subcontractor</button></td></tr>';}).join('')+'</table></div>';
  var conv=DB.users.filter(function(u){return u.convertedFrom==='tester';});if(conv.length)x+='<h2>Converted accounts</h2><ul>'+conv.map(function(u){return '<li>'+esc(u.name)+' → '+esc(TYPES[u.type])+' on '+esc(u.convertedAt)+' (login, details, terms history and consent kept)</li>';}).join('')+'</ul>';
  return x;};
ACT.testersoff=function(){if(!confirmBox('toff','Switch off ALL testing accounts?'))return;users('tester').forEach(function(u){u.active=false;});audit('Switched off all testing accounts');save();render();};
ACT.convert=function(el){var u=user(el.dataset.id),to=el.dataset.to;if(!confirmBox('cv'+u.id+to,'Convert '+u.name+' to a full '+TYPES[to]+' account? Login and data are kept.'))return;
  u.type=to;u.convertedFrom='tester';u.convertedAt=today();u.approved=false;
  if(to==='employee'){var nm=u.name.split(' ');u.profile=Object.assign({firstName:nm[0],lastName:nm.slice(1).join(' '),provEmp:'PE',payFreq:'Bi-weekly',vacPct:4},u.profile||{});u.wagepoint={added:false};}
  if(to==='sub'){var code=u.name.replace(/[^A-Za-z]/g,'').toUpperCase().slice(0,3)||'SUB';while(users('sub').some(function(s){return s!==u&&s.code===code;}))code=code.slice(0,2)+String.fromCharCode(65+Math.floor(Math.random()*26));u.code=code;u.company={legalName:'',email:u.email,phone:u.phone,mainContact:{name:u.name,email:u.email},emergency:{},periodStart:today()};}
  /* the user's past TEST records stay test:true (time entries, invoices); remove them from any practice shift bookings */
  DB.shifts.forEach(function(s){if(s.test)s.booked=s.booked.filter(function(i){return i!==u.id;});});
  DB.convReq.forEach(function(r){if(r.userId===u.id&&r.status==='Requested')r.status='Approved';});
  audit('Converted testing account',u.name,'to '+TYPES[to]+' – login, details, terms history and consent kept');notify(u.id,'Your testing account was converted to a full '+TYPES[to]+' account. Sign in to see the items still needed for your new role. Earlier test records stay marked TEST and are never paid.');
  save();closeModal();toast('Converted.');render();};

/* ---------- Shifts admin ---------- */
VIEWS['admin:shiftsadmin']=function(){var list=DB.shifts.slice().sort(function(a,b){return a.date<b.date?1:-1;});
  return '<h1>Shifts</h1><div class="card hl"><h3 style="margin-top:0">Create a shift</h3><form data-form="newshift"><div class="grid2">'+inp('date','Date',today(),{type:'date',req:true})+inp('title','Title','Field work',{req:true})+inp('start','Start','07:00',{type:'time'})+inp('end','End','15:30',{type:'time'})+sel('site','Site',(typeof companySites==='function'?companySites():DB.sites).map(function(s){return [s.code,s.code+' – '+s.name];}),'')+sel('kind','Who',[['crew','Subcontractor crew (subs and their workers sign up)'],['employee','Employee assignment (office books – employees do not sign up)']],'')+sel('role','Role',[['general','General'],['driver','Driver'],['forklift','Forklift'],['machinery','Machinery']],'')+sel('licClass','Driver licence class needed',[['','–'],'Class 5','DZ / Class 3','AZ / Class 1'],'')+inp('needed','Workers needed',4,{type:'number'})+'</div>'+chk('airBrake','Air brake needed (driver)',false)+chk('orientation','Site orientation required',false)+'<div class="hint">Shifts at the TEST-PRACTICE site are practice shifts for testers (never paid, never billed).</div><button>Create shift</button></form></div><div class="tw"><table><tr><th>Date</th><th>Shift</th><th>Site</th><th>Who / role</th><th>Booked</th></tr>'+list.map(function(s){return '<tr><td>'+esc(s.date)+'<div class="small">'+esc(s.start)+'–'+esc(s.end)+'</div></td><td>'+esc(s.title)+(s.test?' <span class="badge-test">TEST</span> <span class="unpaid">UNPAID</span>':'')+'</td><td class="small">'+esc(siteName(s.site))+'<br>'+esc(firmName(s.site))+'</td><td class="small">'+(s.kind==='crew'?'Subcontractor crew':'Employees')+' · '+esc(roleLabel(s))+'</td><td class="small">'+(s.booked||[]).length+'/'+s.needed+': '+(s.booked||[]).map(function(id){var u=user(id);return esc(u?u.name:'?');}).join(', ')+'</td></tr>';}).join('')+'</table></div>';};
FORMS.newshift=function(f,d){var test=d.site==='TEST-PRACTICE';DB.shifts.push({id:uid('s'),date:d.date,start:d.start,end:d.end,title:d.title,site:d.site,kind:test?'employee':d.kind,role:d.role,licClass:d.licClass,airBrake:!!d.airBrake,orientation:!!d.orientation,needed:+d.needed||1,booked:[],test:test});audit('Created shift',d.date+' '+d.site);save();toast('Shift created.');render();};

/* ---------- Feedback / analytics ---------- */
VIEWS['admin:feedbackadmin']=function(){return '<h1>Feedback inbox</h1><div class="tw"><table><tr><th>Date</th><th>From</th><th>Screen</th><th>Rating</th><th>Comment</th><th>Screenshot</th><th>Status</th></tr>'+DB.feedback.map(function(f){var u=user(f.userId);return '<tr><td class="small">'+fmtStamp(f.at)+'</td><td>'+esc(u?u.name:'?')+'</td><td class="small">'+esc(f.screen)+'</td><td>'+f.rating+'★</td><td>'+esc(f.comment)+'</td><td>'+(f.screenshot?'<a href="#" data-act="fbshot" data-id="'+f.id+'">view</a>':'')+'</td><td><select data-fb="'+f.id+'" style="max-width:130px">'+opt(['New','Reviewed','Planned','Done'],f.status)+'</select></td></tr>';}).join('')+'</table></div>';};
document.addEventListener('change',function(e){var id=e.target.dataset&&e.target.dataset.fb;if(!id)return;var f=DB.feedback.filter(function(x){return x.id===id;})[0];f.status=e.target.value;audit('Feedback status '+f.status);save();toast('Saved.');});
ACT.fbshot=function(el){var f=DB.feedback.filter(function(x){return x.id===el.dataset.id;})[0];showFile(f.screenshot.name,f.screenshot.type,f.screenshot.data,'Feedback screenshot');};
function bars(obj){var mx=Math.max.apply(null,[1].concat(Object.keys(obj).map(function(k){return obj[k];})));return Object.keys(obj).map(function(k){return '<div class="barrow"><div>'+esc(k)+'</div><div><div class="bar" style="width:'+(obj[k]/mx*100)+'%"></div></div><div>'+(Math.round(obj[k]*10)/10)+'</div></div>';}).join('')||'<p class="muted small">No data.</p>';}
function analyticsData(optIn){var testers=users('tester').concat(DB.users.filter(function(u){return u.convertedFrom;}));var ok=function(id){if(!optIn)return true;var u=user(id);var c=u&&consentOf(u);return c&&c.choice;};
  var ev=DB.events.filter(function(e){return e.test&&ok(e.u);});var t=today();
  var day={},week={};ev.forEach(function(e){if(e.d===t)day[e.u]=1;if(daysBetween(e.d,t)<7)week[e.u]=1;});
  var signups={},complete={},times=[];DB.users.forEach(function(u){if(u.type==='admin'||u.type==='firm'||(optIn&&!ok(u.id)))return;signups[TYPES[u.type]]=(signups[TYPES[u.type]]||0)+1;var done=u.type==='tester'?!missingTerms(u).length:registrationComplete(u);if(done)complete[TYPES[u.type]]=(complete[TYPES[u.type]]||0)+1;if(u.completedAt)times.push((new Date(u.completedAt)-new Date(u.createdAt))/3600000);});
  var rate={};Object.keys(signups).forEach(function(k){rate[k]=Math.round(100*(complete[k]||0)/signups[k]);});
  var screens={};ev.filter(function(e){return e.type==='screen';}).forEach(function(e){screens[e.screen]=(screens[e.screen]||0)+1;});
  var inv=ev.filter(function(e){return e.type==='invoice_submit'&&e.ms;});
  var fbd={};DB.feedback.filter(function(f){return ok(f.userId);}).forEach(function(f){var d=f.at.slice(0,10);fbd[d]=fbd[d]||[];fbd[d].push(f.rating);});var fbavg={};Object.keys(fbd).sort().forEach(function(d){fbavg[d]=fbd[d].reduce(function(a,b){return a+b;},0)/fbd[d].length;});
  return {activeDay:Object.keys(day).length,activeWeek:Object.keys(week).length,signups:signups,rate:rate,avgReg:times.length?times.reduce(function(a,b){return a+b;},0)/times.length:null,testShifts:DB.shifts.filter(function(s){return s.test;}).reduce(function(a,s){return a+s.booked.length;},0)+DB.time.filter(function(x){return x.test;}).length,testInvoices:DB.invoices.filter(function(i){return i.test;}).length,avgInv:inv.length?inv.reduce(function(a,e){return a+e.ms;},0)/inv.length/1000:null,screens:screens,errors:DB.events.filter(function(e){return e.type==='error';}).length,fbavg:fbavg};}
VIEWS['admin:analytics']=function(){var o=!!PAGE_STATE.optIn,a=analyticsData(o);PAGE_STATE.analytics=a;
  return '<h1>Usage analytics (testers)</h1><p class="small muted">Totals and charts only – no personal details. Use the opted-in filter for anything that may be used for marketing or future products. Small groups that could identify someone should be combined or left out.</p><div class="row"><label class="inline"><input type="checkbox" data-act="optin"'+(o?' checked':'')+'> Only testers who opted in to data use</label><button class="small sec" data-act="anacsv">Export aggregated CSV</button></div><div class="grid">'+statCard('Active testers today',a.activeDay,'#/analytics')+statCard('Active testers this week',a.activeWeek,'#/analytics')+statCard('Test shifts / test hours records',a.testShifts,'#/analytics')+statCard('Test invoices',a.testInvoices,'#/analytics')+statCard('Avg. time to submit an invoice',a.avgInv?Math.round(a.avgInv)+' s':'–','#/analytics')+statCard('Avg. time to complete registration',a.avgReg?Math.round(a.avgReg*10)/10+' h':'–','#/analytics')+statCard('Errors / crashes logged',a.errors,'#/analytics')+'</div><div class="grid"><div class="card"><h3>Sign-ups by role</h3>'+bars(a.signups)+'</div><div class="card"><h3>Registration completion rate by role (%)</h3>'+bars(a.rate)+'</div><div class="card"><h3>Most-used screens (testers)</h3>'+bars(a.screens)+'</div><div class="card"><h3>Feedback rating over time (avg)</h3>'+bars(a.fbavg)+'</div></div>';};
ACT.optin=function(el){PAGE_STATE.optIn=!PAGE_STATE.optIn;render();};
ACT.anacsv=function(){var a=PAGE_STATE.analytics,r=[['Metric','Value']];r.push(['Active testers today',a.activeDay],['Active testers this week',a.activeWeek],['Test shifts/hours records',a.testShifts],['Test invoices',a.testInvoices],['Avg invoice submit seconds',a.avgInv?Math.round(a.avgInv):''],['Errors',a.errors]);Object.keys(a.signups).forEach(function(k){r.push(['Sign-ups: '+k,a.signups[k]]);});Object.keys(a.rate).forEach(function(k){r.push(['Completion %: '+k,a.rate[k]]);});Object.keys(a.screens).forEach(function(k){r.push(['Screen views: '+k,a.screens[k]]);});downloadText('unscramble-tester-analytics-aggregated-TEST.csv',r.map(csvRow).join('\n'),'text/csv');audit('Exported aggregated analytics');save();};

/* ---------- Alerts outbox / audit / privacy / settings ---------- */
VIEWS['admin:alerts']=function(){DB.notes.forEach(function(n){if(n.to==='admin')n.read=true;});save();
  return '<h1>Alerts outbox (simulated)</h1><p class="small muted">In the real app these go out by email/push (SMS only if a phone was added). Admin copies go to '+ADMIN_EMAIL+'. In this test nothing is sent – they are listed here.</p><button class="small sec" data-act="runalerts">Run reminder check now</button><div class="tw" style="margin-top:8px"><table><tr><th>When</th><th>Sim. date</th><th>To</th><th>Channel</th><th>Message</th></tr>'+DB.notes.slice(0,300).map(function(n){return '<tr><td class="small">'+fmtStamp(n.at)+'</td><td class="small">'+esc(n.simDate)+'</td><td class="small">'+esc(n.toLabel)+'</td><td class="small">'+esc(n.channel)+'</td><td>'+esc(n.text)+'</td></tr>';}).join('')+'</table></div>';};
ACT.runalerts=function(){runAlerts();sweepBookings();save();toast('Reminder check done.');render();};
VIEWS['admin:auditlog']=function(){return '<h1>Audit log</h1><p class="small muted">Who uploaded, approved, viewed or changed documents and records.</p><div class="tw"><table><tr><th>When</th><th>Who</th><th>Action</th><th>About</th><th>Detail</th></tr>'+DB.audit.slice(0,400).map(function(a){return '<tr><td class="small">'+fmtStamp(a.at)+'</td><td class="small">'+esc(a.actor)+'</td><td>'+esc(a.action)+'</td><td>'+esc(a.target)+'</td><td class="small">'+esc(a.detail)+'</td></tr>';}).join('')+'</table></div>';};
VIEWS['admin:privacy']=function(){return '<h1>Privacy &amp; marketing permissions</h1><h2>Privacy requests (access / correction)</h2><div class="tw"><table><tr><th>When</th><th>Who</th><th>Type</th><th>Details</th><th>Status</th></tr>'+DB.privacyReq.map(function(r){return '<tr><td class="small">'+fmtStamp(r.at)+'</td><td>'+esc(r.name)+'</td><td>'+esc(r.kind)+'</td><td>'+esc(r.text)+'</td><td>'+(r.status==='Open'?'<button class="small sec" data-act="closepriv" data-id="'+r.id+'">Mark done</button>':'Done')+'</td></tr>';}).join('')+'</table></div>'+
  '<h2>Data-use consent records</h2><div class="tw"><table><tr><th>Who</th><th>Choice</th><th>Wording version</th><th>When</th></tr>'+DB.consents.slice().reverse().map(function(c){var u=user(c.userId);return '<tr><td>'+esc(u?u.name:'?')+'</td><td>'+(c.choice?'Yes':'No / withdrawn')+'</td><td>'+esc(c.version)+'</td><td class="small">'+fmtStamp(c.at)+' ('+esc(c.tz)+')</td></tr>';}).join('')+'</table></div>'+
  '<h2>Marketing permissions (testimonials, quotes, photos, names)</h2><p class="small muted">Needed separately, in writing, from each person before any use in marketing.</p><form data-form="mkt" class="card"><div class="grid2">'+sel('userId','Person',DB.users.filter(function(u){return u.type!=='admin'&&u.type!=='firm';}).map(function(u){return [u.id,u.name];}),'')+inp('what','What was approved','',{req:true,ph:'e.g. quote on website'})+inp('date','Date of written permission',today(),{type:'date',req:true})+'</div><button class="small">Add record</button></form><div class="tw"><table><tr><th>Person</th><th>Approved use</th><th>Date</th><th>Recorded by</th></tr>'+DB.marketing.map(function(m){return '<tr><td>'+esc((user(m.userId)||{}).name)+'</td><td>'+esc(m.what)+'</td><td>'+esc(m.date)+'</td><td>'+esc(m.by)+'</td></tr>';}).join('')+'</table></div><div class="alert info small">Before launch: the owner approves the final privacy policy and opt-in wording (PIPEDA plain-language); retention periods are set by the office.</div>';};
ACT.closepriv=function(el){var r=DB.privacyReq.filter(function(x){return x.id===el.dataset.id;})[0];r.status='Done';audit('Privacy request done',r.name);save();render();};
FORMS.mkt=function(f,d){DB.marketing.unshift({userId:d.userId,what:d.what,date:d.date,by:ME.name});audit('Recorded marketing permission',(user(d.userId)||{}).name,d.what);save();render();};
VIEWS['admin:settings']=function(){var S=DB.settings;
  return '<h1>Settings</h1><div class="card hl"><h3 style="margin-top:0">Reset test data</h3><p>Puts back the sample people and removes everything you entered (only in this browser).</p><button class="danger" data-act="resetData">Reset test data</button></div>'+
  '<div class="card"><h3 style="margin-top:0">Simulated date (to test expiry and reminders)</h3><form data-form="settings"><div class="grid2">'+inp('simDate','Pretend today is (leave empty for the real date)',S.simDate,{type:'date'})+inp('minWage','PEI minimum wage ($/h – check current rate)',S.minWage,{type:'number',extra:' step="0.01"'})+inp('payrollCutoff','Next payroll cut-off',S.payrollCutoff,{type:'date'})+sel('paymentTerms','Invoice payment terms (owner to choose)',[['net30_submit','Net 30 after a correct invoice is submitted'],['net30_farm','Net 30 after the farm pays']],S.paymentTerms)+'</div><button>Save settings</button></form></div>'+
  '<div class="card"><h3 style="margin-top:0">Data-use consent wording</h3><p class="small">Current version '+esc(S.consentVersion)+'. Publishing a new version asks everyone again (never blocks work).</p><form data-form="consentver" class="row"><input type="text" name="v" placeholder="New version e.g. 1.1" style="max-width:200px" required><button class="small sec">Publish new consent version</button></form></div>'+
  '<div class="card"><h3 style="margin-top:0">Download all test data</h3><button class="small sec" data-act="exportall">Download JSON backup (local file)</button></div>';};
FORMS.settings=function(f,d){var S=DB.settings;S.simDate=d.simDate;S.minWage=Number(d.minWage)||S.minWage;S.payrollCutoff=d.payrollCutoff;S.paymentTerms=d.paymentTerms;audit('Changed settings','',JSON.stringify(d));runAlerts();sweepBookings();save();toast('Saved.');render();};
FORMS.consentver=function(f,d){DB.settings.consentVersion=d.v;audit('Published new consent wording version',d.v);save();toast('Published.');render();};
ACT.exportall=function(){downloadText('unscramble-registration-TEST-data-'+today()+'.json',JSON.stringify(DB,null,1),'application/json');audit('Downloaded full test data backup');save();};

ACT.wcbnow=function(el){var s=user(el.dataset.id);s.company=s.company||{};s.company.wcbRequiredNow=!s.company.wcbRequiredNow;audit(s.company.wcbRequiredNow?'Marked WCB clearance required now':'Removed "WCB required now" (first-year rule applies)',s.company.legalName||s.name);
  if(s.company.wcbRequiredNow)notify(['admin',s.id],'The office marked WCB clearance as required now for '+(s.company.legalName||s.name)+'. Please upload a WCB clearance letter – workers are blocked from shifts until it is checked.');save();closeModal();render();};
