/* Client firm (farm/business) login: totals only – never worker names, nicknames or phones. */
'use strict';
NAV.firm=[['#/home','Workers, hours & billing'],['#/profile','Profile']];
var BREAK_MIN=30; /* default: 30-minute unpaid break deducted from billable hours on shifts of 5h or more */
function shortDay(d){var x=parseD(d);return ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][x.getDay()]+' '+['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][x.getMonth()]+' '+x.getDate();}
function weekStart(d){var w=parseD(d).getDay();return addDays(d,-((w+6)%7));}
/* Anonymous shift rows for a firm (never names). Approved farm changes are already applied to the time entry (original kept in t.orig). */
function firmCodes(firm){return DB.sites.filter(function(s){return s.firmId===firm.id;}).map(function(s){return s.code;});}
function firmRows(firm,from,to){var codes=firmCodes(firm),rows=[];
  DB.time.forEach(function(t){if(t.test||!t.out||t.date<from||t.date>to)return;var sh=DB.shifts.filter(function(s){return s.id===t.shiftId;})[0];if(sh&&sh.test)return;var site=sh?sh.site:t.site;if(!site||codes.indexOf(site)<0)return;var u=user(t.userId);if(!u||u.type==='tester')return;
    rows.push({key:t.key0||('t:'+t.id),date:t.date,site:site,start:t.in,end:t.out,uid:t.userId,temp:!!t.temp,changed:!!t.orig,orig:t.orig,breakMissed:!!t.breakMissed});});
  /* subcontractor crews: no clocked hours, so scheduled crew hours are used for past dates */
  DB.shifts.forEach(function(sh){if(sh.test||sh.kind!=='crew'||codes.indexOf(sh.site)<0||sh.date>today()||sh.date<from||sh.date>to)return;(sh.booked||[]).forEach(function(id){var u=user(id);if(!u||u.type==='tester')return;if(DB.time.some(function(t){return t.userId===id&&t.shiftId===sh.id&&!t.test;}))return;rows.push({key:'c:'+sh.id+':'+id,date:sh.date,site:sh.site,start:sh.start,end:sh.end,uid:id,crew:true});});});
  rows.sort(function(a,b){return a.date<b.date?-1:a.date>b.date?1:a.site<b.site?-1:a.site>b.site?1:a.start<b.start?-1:a.start>b.start?1:a.key<b.key?-1:1;});
  /* stable Worker #: the same person keeps the same number for that farm and day, on every visit and after time changes.
     Numbers are kept in DB.workerNos; first given in order of the ORIGINAL start time, then person id; someone new gets the next number. */
  var map=DB.workerNos=DB.workerNos||{},byDate={};rows.forEach(function(r){(byDate[r.date]=byDate[r.date]||[]).push(r);});
  Object.keys(byDate).forEach(function(dt){var k=firm.id+'|'+dt,m=map[k]=map[k]||{},next=Object.keys(m).reduce(function(a,id){return Math.max(a,m[id]);},0);
    byDate[dt].slice().sort(function(a,b){var x=(a.orig&&a.orig.in)||a.start,y=(b.orig&&b.orig.in)||b.start;return x<y?-1:x>y?1:a.uid<b.uid?-1:a.uid>b.uid?1:0;}).forEach(function(r){if(!m[r.uid])m[r.uid]=++next;});});
  rows.forEach(function(r){r.no=map[firm.id+'|'+r.date][r.uid];r.hours=hrs(r.start,r.end);r.bill=Math.max(0,r.hours-breakHoursFor(r.hours,!!r.breakMissed));});
  return rows;}
function firmReport(firm,from,to){
  var rows={},d=from;while(d<=to){rows[d]={date:d,workers:{},hours:0,bill:0,temp:0};d=addDays(d,1);}
  var list=firmRows(firm,from,to);
  list.forEach(function(x){var r=rows[x.date];if(!r)return;r.workers[x.uid]=1;r.hours+=x.hours;r.bill+=x.bill;if(x.temp)r.temp+=x.hours;});
  var out=Object.keys(rows).sort().map(function(k){var r=rows[k];r.n=Object.keys(r.workers).length;r.amount=Math.round(r.bill*firm.firm.billRate*100)/100;return r;});
  var tot={n:0,hours:0,bill:0,amount:0},uniq={};out.forEach(function(r){tot.hours+=r.hours;tot.bill+=r.bill;Object.keys(r.workers).forEach(function(k){uniq[k]=1;});tot.n+=r.n;});
  tot.unique=Object.keys(uniq).length;tot.amount=Math.round(tot.bill*firm.firm.billRate*100)/100;tot.hst=Math.round(tot.amount*15)/100;tot.total=Math.round((tot.amount+tot.hst)*100)/100;
  return {rows:out,tot:tot,codes:firmCodes(firm),shiftRows:list};}
function latestChange(key){var c=DB.changes.filter(function(x){return x.key===key;});return c[c.length-1]||null;}
function changeStatusHtml(c){if(!c)return '';
  if(c.status==='Pending')return '<span class="pill s-pend">Changed by farm, awaiting office review</span><div class="small">Proposed '+esc(c.propStart)+'–'+esc(c.propEnd)+plus1(c.propStart,c.propEnd)+(c.comment?' · “'+esc(c.comment)+'”':'')+'</div>';
  var lab={Approved:['s-ok','Approved by office'],Adjusted:['s-warn','Adjusted by office to '+esc(c.decStart)+'–'+esc(c.decEnd)+plus1(c.decStart,c.decEnd)],Rejected:['s-bad','Rejected by office – original time kept']}[c.status];
  return '<span class="pill '+lab[0]+'">'+lab[1]+'</span>'+(c.note?'<div class="small">Office note: '+esc(c.note)+'</div>':'');}
function firmShiftTable(firm,R,canEdit){PAGE_STATE.frRows={};
  return '<h2>Shifts at your sites</h2><p class="small muted">Workers are shown as Worker #1, #2… per day – no names or contact details. You can propose a different start or end time; the office reviews it. Only approved changes change hours and billing.</p>'+
  (R.shiftRows.length?'<div class="tw"><table><tr><th>Site</th><th>Date</th><th>Worker</th><th>Start</th><th>End</th><th>Hours</th><th>Status</th><th></th></tr>'+R.shiftRows.map(function(r){PAGE_STATE.frRows[r.key]=r;var c=latestChange(r.key),pend=c&&c.status==='Pending';
    return '<tr><td>'+esc(r.site)+(r.temp?' <span class="badge-temp">TEMPORARY</span>':'')+'</td><td>'+shortDay(r.date)+'</td><td>Worker #'+r.no+'</td><td>'+esc(r.start)+(r.orig?'<div class="small muted">was '+esc(r.orig.in)+'</div>':'')+'</td><td>'+esc(r.end)+plus1H(r.start,r.end)+(r.orig?'<div class="small muted">was '+esc(r.orig.out)+'</div>':'')+'</td><td>'+r.hours.toFixed(2)+'</td><td>'+changeStatusHtml(c)+'</td><td>'+(canEdit?'<button class="small sec" data-act="firmedit" data-key="'+esc(r.key)+'"'+(pend?' disabled':'')+'>'+(pend?'Waiting for office':'Propose change')+'</button>':'')+'</td></tr>';}).join('')+'</table></div>':'<p class="muted">No shifts in this date range.</p>');}
ACT.firmedit=function(el){var r=(PAGE_STATE.frRows||{})[el.dataset.key];if(!r)return;
  modal('<h2>Propose a time change</h2><p>'+esc(r.site)+' · '+shortDay(r.date)+' · Worker #'+r.no+'</p><p class="small">Current time: <b>'+esc(r.start)+'–'+esc(r.end)+plus1(r.start,r.end)+'</b> ('+r.hours.toFixed(2)+' h). The original time is kept until the office approves your change.</p><form data-form="firmchg"><input type="hidden" name="key" value="'+esc(r.key)+'"><div class="grid2">'+inp('start','New start time',r.start,{type:'time',req:true})+inp('end','New end time',r.end,{type:'time',req:true})+'</div><label>Comment (optional)</label><textarea name="comment" placeholder="e.g. crew left early because of rain"></textarea><p><button>Send to office for review</button></p></form>');};
FORMS.firmchg=function(f,d){var firm=ME;var r=(PAGE_STATE.frRows||{})[d.key];
  if(!r||firmCodes(firm).indexOf(r.site)<0){toast('Not allowed.');audit('Blocked firm change (not own site)',firm.name);save();return;}
  if(spanErr(d.start,d.end)){toast(spanErr(d.start,d.end));return;}
  if(d.start===r.start&&d.end===r.end){toast('Nothing changed.');return;}
  var c={id:uid('fc'),firmId:firm.id,firmName:firm.name,by:firm.name+' ('+(firm.username||firm.email)+')',key:d.key,site:r.site,date:r.date,workerNo:r.no,uid:r.uid,origStart:r.start,origEnd:r.end,propStart:d.start,propEnd:d.end,comment:d.comment,at:new Date().toISOString(),status:'Pending'};
  DB.changes.push(c);audit('Farm proposed shift time change',firm.name,r.site+' '+r.date+' Worker #'+r.no+': '+r.start+'–'+r.end+plus1(r.start,r.end)+' → '+d.start+'–'+d.end+plus1(d.start,d.end)+(d.comment?' ("'+d.comment+'")':''));
  notify('admin','Farm change to review: '+firm.name+' proposes '+d.start+'–'+d.end+plus1(d.start,d.end)+' (was '+r.start+'–'+r.end+plus1(r.start,r.end)+') for '+r.site+' on '+r.date+'.');save();closeModal();toast('Sent to the office for review.');render();};
function firmPage(firm){var st=PAGE_STATE.fr||{};var from=st.from||weekStart(today()),to=st.to||addDays(weekStart(today()),6);
  var R=firmReport(firm,from,to),rate=firm.firm.billRate;
  var x='<h1>'+esc(firm.name)+'</h1><p class="small muted">Your sites: '+R.codes.map(function(c){return esc(siteName(c));}).join(', ')+'. Totals only – worker names and contact details are never shown. Test/practice activity is never billed.</p>'+
  '<form data-form="frange" class="row card"><div><label>From</label><input type="date" name="from" value="'+from+'"></div><div><label>To</label><input type="date" name="to" value="'+to+'"></div><div style="align-self:flex-end"><button class="small">Show</button> <button class="small sec" data-act="fweek">This week</button></div></form>'+
  '<div class="tw desk-only"><table class="no-stack"><tr><th>Day</th><th style="text-align:right">Workers</th><th style="text-align:right">Hours worked</th><th style="text-align:right">Billable hours</th><th style="text-align:right">Amount (@ '+money(rate)+'/h)</th></tr>'+R.rows.map(function(r){return '<tr><td>'+shortDay(r.date)+(r.temp?' <span class="badge-temp">TEMPORARY</span>':'')+'</td><td style="text-align:right">'+r.n+'</td><td style="text-align:right">'+r.hours.toFixed(2)+'</td><td style="text-align:right">'+r.bill.toFixed(2)+'</td><td style="text-align:right">'+money(r.amount)+'</td></tr>';}).join('')+
  '<tr><th>Period total</th><th style="text-align:right">'+R.tot.n+' <span class="small">('+R.tot.unique+' different)</span></th><th style="text-align:right">'+R.tot.hours.toFixed(2)+'</th><th style="text-align:right">'+R.tot.bill.toFixed(2)+'</th><th style="text-align:right">'+money(R.tot.amount)+'</th></tr></table></div>'+
  '<div class="phone-only">'+R.rows.map(function(r){return '<div class="daycard'+(r.n?'':' empty')+'"><div class="dc-head"><b>'+shortDay(r.date)+(r.temp?' <span class="badge-temp">TEMPORARY</span>':'')+'</b><b>'+money(r.amount)+'</b></div><div class="dc-grid"><div><span>Workers</span>'+r.n+'</div><div><span>Hours worked</span>'+r.hours.toFixed(2)+'</div><div><span>Billable hours</span>'+r.bill.toFixed(2)+'</div></div></div>';}).join('')+'</div>'+
  '<div class="card totals"><h2 style="margin-top:0">Period total <span class="small muted">'+shortDay(from)+' – '+shortDay(to)+'</span></h2>'+
  '<div class="trow"><span>Workers (worker-days)</span><b>'+R.tot.n+' <span class="small muted">('+R.tot.unique+' different)</span></b></div>'+
  '<div class="trow"><span>Hours worked</span><b>'+R.tot.hours.toFixed(2)+'</b></div>'+
  '<div class="trow"><span>Billable hours</span><b>'+R.tot.bill.toFixed(2)+'</b></div>'+
  '<div class="trow"><span>Billable hours × bill rate<br><span class="small muted">'+R.tot.bill.toFixed(2)+' h × '+money(rate)+'</span></span><b>'+money(R.tot.amount)+'</b></div>'+
  '<div class="trow"><span>HST 15%</span><b>'+money(R.tot.hst)+'</b></div>'+
  '<div class="trow grand"><span>Total to pay for this period</span><b>'+money(R.tot.total)+'</b></div></div>'+
  (R.rows.some(function(r){return r.temp;})?'<p class="small"><span class="badge-temp">TEMPORARY</span> = includes hours worked by a crew under a short-term temporary arrangement approved by UnScramble. These hours are billed normally.</p>':'')+'<p class="small muted">Billable hours = hours worked minus a 30-minute unpaid break on shifts of 5 hours or more (test default – owner to confirm). Subcontractor crew hours use the scheduled shift times (subcontractors keep their own time records).</p><button class="small sec" data-act="fcsv">Download as CSV</button>';
  x+=firmShiftTable(firm,R,ME&&ME.type==='firm');PAGE_STATE.frData={firm:firm,R:R,from:from,to:to};return x;}
VIEWS['firm:home']=function(){return firmPage(ME);};
FORMS.frange=function(f,d){if(d.from>d.to){toast('"From" must be before "To".');return;}PAGE_STATE.fr={from:d.from,to:d.to};render();};
ACT.fweek=function(){PAGE_STATE.fr={};render();};
ACT.fcsv=function(){var D=PAGE_STATE.frData,rows=[['Day','Workers','Hours worked','Billable hours','Amount']];D.R.rows.forEach(function(r){rows.push([r.date,r.n,r.hours.toFixed(2),r.bill.toFixed(2),r.amount.toFixed(2)]);});rows.push(['Period total',D.R.tot.n,D.R.tot.hours.toFixed(2),D.R.tot.bill.toFixed(2),D.R.tot.amount.toFixed(2)]);rows.push(['HST 15%','','','',D.R.tot.hst.toFixed(2)]);rows.push(['Total to pay','','','',D.R.tot.total.toFixed(2)]);downloadText(D.firm.name.replace(/\W+/g,'-')+'-'+D.from+'-to-'+D.to+'-TEST.csv',rows.map(csvRow).join('\n'),'text/csv');};

/* Admin: firm logins, bill rates, sites */
VIEWS['admin:firms']=function(){var firms=(typeof companyFirms==='function'?companyFirms():users('firm'));
  return '<h1>Client firms (farms / businesses)</h1><p class="small muted">Each firm gets its own login and sees only totals for its own sites – never worker names, nicknames or phones. Use fake names in this test (e.g. "Test Farm C").</p><div class="tw"><table><tr><th>Firm</th><th>Login</th><th>Bill rate</th><th>Sites</th><th>Status</th><th></th></tr>'+firms.map(function(f){return '<tr><td><b>'+esc(f.name)+'</b></td><td class="small">'+esc(f.username||'')+'<br>'+esc(f.email||'')+'</td><td><form data-form="firmrate" class="row"><input type="hidden" name="id" value="'+f.id+'"><input type="number" step="0.01" min="0" name="rate" value="'+f.firm.billRate+'" style="max-width:100px"><button class="small sec">Set</button></form></td><td class="small">'+DB.sites.filter(function(s){return s.firmId===f.id;}).map(function(s){return esc(s.code+' – '+s.name);}).join('<br>')+'<form data-form="addsite" class="row" style="margin-top:4px"><input type="hidden" name="id" value="'+f.id+'"><input type="text" name="code" placeholder="Code e.g. TFA-03" style="max-width:120px" required><input type="text" name="name" placeholder="Site name" style="max-width:140px" required><button class="small sec">Add site</button></form></td><td>'+(f.active?'<span class="pill s-ok">Active</span>':'<span class="pill s-mut">Off</span>')+'</td><td><button class="small sec" data-act="firmview" data-id="'+f.id+'">See their page</button><button class="small sec" data-act="toggleactive" data-id="'+f.id+'">'+(f.active?'Switch off':'Switch on')+'</button><button class="small sec" data-act="person" data-id="'+f.id+'">Reset password</button></td></tr>';}).join('')+'</table></div>'+
  '<div class="card hl"><h3 style="margin-top:0">Create a firm login</h3><form data-form="newfirm"><div class="grid2">'+inp('name','Firm name (fake in this test)','',{req:true,ph:'Test Farm C'})+inp('username','Username','',{req:true})+inp('email','Email (optional)','',{type:'email'})+inp('pw','Temporary password','',{req:true})+inp('rate','Bill rate ($ per billable hour)','',{type:'number',req:true,extra:' step="0.01" min="0"'})+inp('code','First site code','',{req:true,ph:'TFC-01'})+inp('site','First site name','',{req:true,ph:'Main Field'})+'</div><button>Create firm login</button></form></div>';};
FORMS.newfirm=function(f,d){if(loginTaken(d.username,d.email)){toast('Username/email already used.');return;}if(d.pw.length<6){toast('Password at least 6 characters.');return;}if(DB.sites.some(function(s){return s.code.toLowerCase()===d.code.toLowerCase();})){toast('Site code already used.');return;}
  var u={id:uid('u'),type:'firm',name:d.name,username:d.username,email:d.email,phone:'',passHash:hashPw(d.pw),active:true,approved:true,createdAt:new Date().toISOString(),profile:{},roles:[],orientations:[],firm:{billRate:Number(d.rate)||0}};if(typeof tagCompany==='function'){tagCompany(u);}DB.users.push(u);DB.sites.push(typeof tagCompany==='function'?tagCompany({code:d.code.toUpperCase(),name:d.site,firmId:u.id}):{code:d.code.toUpperCase(),name:d.site,firmId:u.id});audit('Created firm login',d.name,'rate '+money(d.rate));save();toast('Firm login created.');render();};
FORMS.firmrate=function(f,d){var u=user(d.id);var old=u.firm.billRate;u.firm.billRate=Number(d.rate)||0;audit('Changed firm bill rate',u.name,money(old)+' → '+money(u.firm.billRate));save();toast('Bill rate saved.');render();};
FORMS.addsite=function(f,d){if(DB.sites.some(function(s){return s.code.toLowerCase()===d.code.toLowerCase();})){toast('Site code already used.');return;}DB.sites.push(typeof tagCompany==='function'?tagCompany({code:d.code.toUpperCase(),name:d.name,firmId:d.id}):{code:d.code.toUpperCase(),name:d.name,firmId:d.id});audit('Added site',(user(d.id)||{}).name,d.code);save();render();};
ACT.firmview=function(el){var f=user(el.dataset.id);modal('<div class="alert info small">Office preview of what '+esc(f.name)+' sees.</div>'+firmPage(f).replace(/<form data-form="frange"[\s\S]*?<\/form>/,""));};

/* Office: Farm changes review */
VIEWS['admin:farmchanges']=function(){var f=PAGE_STATE.fcf||'Pending';var list=DB.changes.filter(function(c){return f==='All'||c.status===f;}).slice().reverse();
  return '<h1>Farm changes</h1><p class="small muted">Shift time changes proposed by client firms. Only approved (or adjusted) changes affect hours, pay and billing. Every decision is written to the audit log and the farm sees the outcome and your note.</p><div class="row">'+['Pending','Approved','Adjusted','Rejected','All'].map(function(s){return '<button class="small '+(s===f?'':'sec')+'" data-act="fcfilter" data-s="'+s+'">'+s+' ('+(s==='All'?DB.changes.length:DB.changes.filter(function(c){return c.status===s;}).length)+')</button>';}).join('')+'</div>'+
  (list.length?'<div class="tw" style="margin-top:8px"><table><tr><th>Farm / who / when</th><th>Site · date</th><th>Worker (office only)</th><th>Original</th><th>Proposed</th><th>Farm comment</th><th>Decision</th></tr>'+list.map(function(c){var u=user(c.uid);return '<tr><td><b>'+esc(c.firmName)+'</b><div class="small">'+esc(c.by)+'<br>'+fmtStamp(c.at)+'</div></td><td>'+esc(c.site)+'<br>'+esc(c.date)+'</td><td class="small">'+esc(u?u.name:'?')+'<br>(farm sees Worker #'+c.workerNo+')</td><td>'+esc(c.origStart)+'–'+esc(c.origEnd)+plus1(c.origStart,c.origEnd)+'<div class="small">'+hrs(c.origStart,c.origEnd).toFixed(2)+' h</div></td><td><b>'+esc(c.propStart)+'–'+esc(c.propEnd)+plus1(c.propStart,c.propEnd)+'</b><div class="small">'+hrs(c.propStart,c.propEnd).toFixed(2)+' h</div></td><td class="small">'+esc(c.comment||'–')+'</td><td>'+(c.status==='Pending'?'<form data-form="fcnone" class="fcform" data-id="'+c.id+'"><div class="row"><input type="time" name="start" value="'+esc(c.propStart)+'" style="max-width:120px"><input type="time" name="end" value="'+esc(c.propEnd)+'" style="max-width:120px"></div><textarea name="note" placeholder="Reply note to the farm (required to reject or adjust)" style="min-height:50px"></textarea><div class="row"><button class="small" data-act="fcdec" data-d="Approved" data-id="'+c.id+'">Approve</button><button class="small sec" data-act="fcdec" data-d="Adjusted" data-id="'+c.id+'">Adjust (use times above)</button><button class="small danger" data-act="fcdec" data-d="Rejected" data-id="'+c.id+'">Reject</button></div></form>':changeStatusHtml(c)+'<div class="small muted">'+esc(c.decidedBy||'')+' · '+fmtStamp(c.decidedAt)+'</div>')+'</td></tr>';}).join('')+'</table></div>':'<p class="muted" style="margin-top:8px">Nothing here.</p>');};
ACT.fcfilter=function(el){PAGE_STATE.fcf=el.dataset.s;render();};
FORMS.fcnone=function(){};
ACT.fcdec=function(el){var c=DB.changes.filter(function(x){return x.id===el.dataset.id;})[0];if(!c||c.status!=='Pending')return;var f=el.closest('form'),dec=el.dataset.d,note=f.note.value.trim(),st=f.start.value,en=f.end.value;
  if((dec==='Rejected'||dec==='Adjusted')&&!note){toast('Please write a reply note for the farm.');return;}
  if(dec==='Adjusted'){if(spanErr(st,en)){toast(spanErr(st,en));return;}if(st===c.propStart&&en===c.propEnd){toast('Times are the same as proposed – use Approve, or change the times.');return;}}
  if(dec==='Approved'){st=c.propStart;en=c.propEnd;}
  if(dec!=='Rejected')applyFarmChange(c,st,en);
  c.status=dec;c.note=note;c.decStart=dec==='Rejected'?'':st;c.decEnd=dec==='Rejected'?'':en;c.decidedBy=ME.name;c.decidedAt=new Date().toISOString();
  audit('Farm change '+dec.toLowerCase(),c.firmName,c.site+' '+c.date+' Worker #'+c.workerNo+': original '+c.origStart+'–'+c.origEnd+', proposed '+c.propStart+'–'+c.propEnd+(dec!=='Rejected'?', applied '+st+'–'+en:'')+(note?' · note: '+note:''));
  notify(c.firmId,'Your change for '+c.site+' on '+c.date+' (Worker #'+c.workerNo+') was '+dec.toLowerCase()+(dec==='Adjusted'?' to '+st+'–'+en:'')+' by the office.'+(note?' Note: '+note:''));
  var u=user(c.uid);if(u&&dec!=='Rejected')notify(u.id,'Your hours on '+c.date+' were updated to '+st+'–'+en+' after a farm change approved by the office.');
  save();toast('Decision saved.');render();};
function applyFarmChange(c,st,en){var t;
  if(c.key.indexOf('t:')===0)t=DB.time.filter(function(x){return x.id===c.key.slice(2);})[0];
  else t=DB.time.filter(function(x){return x.key0===c.key;})[0];
  if(!t&&c.key.indexOf('c:')===0){var p=c.key.split(':');var sh=DB.shifts.filter(function(s){return s.id===p[1];})[0];t={id:uid('t'),userId:p[2],shiftId:p[1],date:c.date,in:sh.start,out:sh.end,test:false,key0:c.key,fromSchedule:true};DB.time.push(t);}
  if(!t)return;if(!t.orig)t.orig={in:t.in,out:t.out};t.in=st;t.out=en;t.changeId=c.id;}
