/* Subcontractor screens + invoicing portal (also used by testers in TEST mode). */
'use strict';
NAV.sub=[['#/home','Dashboard'],['#/company','Company details'],['#/docs','Company documents'],['#/workers','My workers'],['#/workerhours',"Workers' hours"],['#/crews','Crew assignments'],['#/invoices','Invoices'],['#/records','Records requests'],['#/alerts','Alerts'],['#/terms','Agreements & terms'],['#/profile','Profile']];
function holdBanner(s){var h=paymentHold(s),amt=heldAmount(s);return h.length?'<div class="alert bad"><b>PAYMENT HOLD:</b> UnScramble may withhold payment until this is fixed: '+esc(h.join('; '))+'.'+(amt?'<div style="margin-top:6px;font-size:16px"><b>Amount on hold: '+money(amt)+'</b></div>':'')+'</div>':'';}
function tempBox(s){var i=tempInfo(s);if(!i||!i.active)return '';var miss=companyBlockersRaw(s);return '<div class="alert warn temp-box">'+tempBadge(s)+'<div style="margin-top:6px"><b>Practice / temporary mode</b> was turned on by the UnScramble office on '+esc(i.t.start)+' because: <i>'+esc(i.t.reason)+'</i>.</div><div>Your crews can keep working and clocking shifts at sites until <b>'+esc(i.t.end)+'</b> (<b>'+(i.left===0?'last day':i.left+' day'+(i.left===1?'':'s')+' left')+'</b>). Your own invoices and payments are <b>on hold</b> until you are fully compliant.</div>'+(miss.length?'<div style="margin-top:6px"><b>Fix before '+esc(i.t.end)+' or you and your workers will be blocked again:</b><ul style="margin:4px 0 0 16px;padding:0">'+miss.map(function(m){return '<li>'+esc(m)+'</li>';}).join('')+'</ul></div>':'<div><b>You are now compliant.</b> The office can end temporary mode and release held payments.</div>')+'</div>';}
VIEWS['sub:home']=function(){var s=ME,due=invoiceDue(s),ws=users('worker').filter(function(w){return w.subId===s.id;});
  var cb=companyBlockers(s);
  var x='<h1>'+esc(s.company.legalName||s.name)+'</h1>'+tempBox(s)+holdBanner(s);
  if(cb.length)x+='<div class="alert bad"><b>ALL of your workers are blocked from crews right now:</b><ul style="margin:4px 0 0 16px;padding:0">'+cb.map(function(b){return '<li>'+esc(b)+'</li>';}).join('')+'</ul></div>';
  if(due.overdue)x+='<div class="alert warn"><b>Your invoice is due</b> for '+due.periodStart+' to '+due.periodEnd+' ('+due.daysLate+' days ago). <a href="#/invoices">Submit invoice →</a>'+(due.daysLate>45?' <b>Invoices more than 60 days late are not payable.</b>':'')+'</div>';
  x+='<div class="grid"><div class="card"><div class="muted small">Workers</div><div class="stat">'+ws.length+'</div><div class="small">'+ws.filter(function(w){return !w.confirmedBySub;}).length+' waiting for your confirmation</div></div><div class="card"><div class="muted small">Open records requests</div><div class="stat">'+DB.records.filter(function(r){return r.subId===s.id&&r.status==='Open';}).length+'</div></div><div class="card"><div class="muted small">Current 30-day period</div><div style="font-weight:600">'+due.periodStart+' → '+due.periodEnd+'</div></div></div>';
  return x+'<h2>Company checklist</h2>'+checklistHtml(s);};
VIEWS['sub:company']=function(){var s=ME,c=s.company||{},mc=c.mainContact||{},em=c.emergency||{};
  var x='<h1>Company details</h1><form data-form="company">';
  x+='<fieldset><legend>Business</legend><div class="grid2">'+inp('legalName','Legal business name',c.legalName,{req:true,hint:'Must match CRA and WCB records.'})+inp('operatingName','Operating name',c.operatingName,{req:true})+inp('address','Business address',c.address,{req:true})+inp('email','Business email',c.email,{type:'email',req:true})+inp('phone','Phone (optional)',c.phone,{type:'tel'})+'</div></fieldset>';
  x+='<fieldset><legend>Tax and WCB numbers</legend><div class="grid2">'+inp('bn','CRA Business Number (9 digits)',c.bn,{req:true,ph:'123456789'})+inp('rp','Payroll account (RP) number',c.rp,{req:true,ph:'123456789RP0001'})+inp('hst','GST/HST number (BN + RT0001)',c.hst,{ph:'123456789RT0001',hint:'Used on invoices (HST 15%).'})+inp('wcbAccount','WCB PEI account number',c.wcbAccount,{req:true})+'</div>'+chk('hstNotReq','Not registered for GST/HST (you may upload proof that registration is not required)',c.hstNotReq)+'</fieldset>';
  x+='<fieldset><legend>Licences and agreement</legend>'+chk('drivesWorkers','We drive workers / operate vehicles (auto liability certificate needed before any driver shift)',c.drivesWorkers)+chk('licenceNotReq','A temporary help agency / recruiter licence is NOT required for us (the office confirms)',c.licenceNotReq)+(c.licenceNotReq?'<div class="small">'+(c.licenceNotReqConfirmed?'<span class="pill s-ok">Office confirmed</span>':'<span class="pill s-pend">Waiting for office confirmation</span>')+'</div>':'')+'<div class="alert info small" style="margin-top:8px"><b>Master Labour Contract Agreement: '+(c.termination?'terminated (effective '+esc(c.termination.effective)+')':'Auto-renews')+'.</b> There is no end date. Either side can end it on written notice; UnScramble can end it immediately for cause. Accept it and Schedule A on the <a href="#/terms">Agreements</a> page.</div></fieldset>';
  x+='<fieldset><legend>Banking for payment (finance/admin only)</legend><div class="grid2">'+inp('bankInst','Institution (3 digits)',c.bankInst)+inp('bankTransit','Transit (5 digits)',c.bankTransit)+inp('bankAcct','Account number','',{ph:c.bankAcct?'On file: '+last(dec(c.bankAcct),4)+' – type to replace':'',hint:'Only the last 4 digits are ever shown. Changes are re-verified by the office before the next payment. Upload a void cheque or bank letter in Documents.'})+'</div>'+(c.bankAcct?'<div class="small">'+(c.bankVerified?'<span class="pill s-ok">Verified by office</span>':'<span class="pill s-pend">Waiting for office verification</span>')+'</div>':'')+'</fieldset>';
  x+='<fieldset><legend>Main contact</legend><div class="grid2">'+inp('mcName','Name',mc.name,{req:true})+inp('mcRole','Role',mc.role,{req:true})+inp('mcEmail','Email',mc.email,{type:'email',req:true})+inp('mcPhone','Phone (optional)',mc.phone,{type:'tel'})+'</div></fieldset>';
  x+='<fieldset><legend>24/7 emergency contact and on-site supervisors</legend><div class="grid2">'+inp('emName','24/7 emergency contact name',em.name,{req:true})+inp('emPhone','24/7 emergency phone',em.phone,{type:'tel',req:true})+'</div><label class="req">On-site supervisor(s)</label><textarea name="supervisors" required>'+esc(c.supervisors||'')+'</textarea><div class="hint">At least one supervisor is needed for crews of 5 or more.</div></fieldset>';
  return x+'<button>Save company details</button></form>';};
FORMS.company=function(f,d){var s=ME,c=s.company=s.company||{},e=[];
  if(!/^\d{9}$/.test(d.bn))e.push('Business Number must be exactly 9 digits.');
  if(!new RegExp('^'+d.bn+'RP\\d{4}$').test(d.rp))e.push('RP number must be your BN followed by RP and 4 digits (e.g. '+d.bn+'RP0001).');
  if(!d.hstNotReq&&!new RegExp('^'+d.bn+'RT\\d{4}$').test(d.hst))e.push('GST/HST number must be your BN followed by RT0001 (or tick "not registered").');
  if(d.bankInst&&!/^\d{3}$/.test(d.bankInst))e.push('Institution must be 3 digits.');if(d.bankTransit&&!/^\d{5}$/.test(d.bankTransit))e.push('Transit must be 5 digits.');if(d.bankAcct&&!/^\d{5,12}$/.test(digits(d.bankAcct)))e.push('Account number must be 5–12 digits.');
  if(e.length){toast(e.join(' '));return;}
  var bankChanged=(d.bankAcct&&c.bankAcct)||(c.bankInst&&d.bankInst!==c.bankInst)||(c.bankTransit&&d.bankTransit!==c.bankTransit);
  ['legalName','operatingName','address','email','phone','bn','rp','hst','wcbAccount','bankInst','bankTransit','supervisors'].forEach(function(k){c[k]=d[k];});
  if(c.licenceNotReq!==!!d.licenceNotReq)c.licenceNotReqConfirmed=false;
  c.hstNotReq=!!d.hstNotReq;c.drivesWorkers=!!d.drivesWorkers;c.licenceNotReq=!!d.licenceNotReq;
  if(d.bankAcct){c.bankAcct=enc(digits(d.bankAcct));}
  if(bankChanged||(d.bankAcct&&!c.bankVerified)){c.bankVerified=false;notify('admin','Banking details changed for '+c.legalName+' – re-verify before the next payment (fraud protection).');audit('Changed banking',c.legalName);}
  c.mainContact={name:d.mcName,role:d.mcRole,email:d.mcEmail,phone:d.mcPhone};c.emergency={name:d.emName,phone:d.emPhone};
  s.name=c.legalName;audit('Updated company details',c.legalName);save();toast('Saved.');go('#/home');};
VIEWS['sub:docs']=function(){return '<h1>Company documents</h1>'+tempBox(ME)+holdBanner(ME)+'<p class="small muted">The office reviews each upload before it counts as Valid. WCB clearance is not required during your first year with UnScramble; after that it is required and re-checked every 90 days. '+esc(wcbRuleText(ME))+'</p>'+docsPage(ME);};
VIEWS['sub:workers']=function(){var s=ME,ws=users('worker').filter(function(w){return w.subId===s.id;});
  var x='<h1>My workers</h1><p class="small muted">You only see your own workers. You are their employer: you keep their SIN, time and payroll records.</p><div class="tw"><table><tr><th>Worker</th><th>Status</th><th>Confirm</th><th>Checked originals</th><th>SIN collected by you</th><th>Documents</th></tr>';
  ws.forEach(function(w){var bl=blockers(w,today());var el=latestDoc(w.id,'eligibility');
    x+='<tr><td><b>'+esc(w.name)+'</b><div class="small muted">'+esc(w.username||w.email)+'</div>'+((w.roles||[]).length?'<div class="small">'+esc(w.roles.join(', '))+'</div>':'')+'</td><td>'+(bl.length?'<span class="pill s-bad">Blocked</span><div class="small">'+esc(bl.slice(0,3).map(function(b){return b.m;}).join(' · '))+(bl.length>3?' …':'')+'</div>':'<span class="pill s-ok">Can be placed on crews</span>')+'</td>'+
    '<td><button class="small '+(w.confirmedBySub?'sec':'')+'" data-act="subflag" data-f="confirmedBySub" data-id="'+w.id+'">'+(w.confirmedBySub?'✓ Confirmed':'Confirm worker')+'</button></td>'+
    '<td><button class="small '+(w.originalsChecked?'sec':'')+'" data-act="subflag" data-f="originalsChecked" data-id="'+w.id+'">'+(w.originalsChecked?'✓ Checked':'I checked originals')+'</button></td>'+
    '<td><button class="small '+(w.sinCollectedBySub?'sec':'')+'" data-act="subflag" data-f="sinCollectedBySub" data-id="'+w.id+'">'+(w.sinCollectedBySub?'✓ Collected':'Employer confirms SIN collected')+'</button></td>'+
    '<td class="small">'+['eligibility','driver_licence','forklift'].map(function(k){var d=latestDoc(w.id,k);if(!d&&k!=='eligibility')return '';var st=docStatus(d);return esc(k==='eligibility'?'Eligibility':DOCS[k].label)+': '+pill(st)+(d?' <a href="#" data-act="viewdoc" data-id="'+d.id+'">view</a>':'')+(d&&d.meta&&d.meta.docType==='permit'&&!permitMatches(w,d)?' <span class="pill s-warn">permit employer mismatch</span>':'');}).filter(Boolean).join('<br>')+'</td></tr>';});
  x+='</table></div><div class="card"><h3 style="margin-top:0">Add a worker</h3><p class="small">Creates a login for your worker. They sign in, accept Schedule C and upload their own documents. Phone is optional.</p><form data-form="addworker"><div class="grid2">'+inp('name','Legal name',"",{req:true})+inp('username','Username','',{})+inp('email','Email (optional if username)','',{type:'email'})+inp('pw','Temporary password','',{req:true})+'</div><button>Add worker</button></form></div>';
  return x;};
ACT.subflag=function(el){var w=user(el.dataset.id);if(!w||w.subId!==ME.id)return;w[el.dataset.f]=!w[el.dataset.f];if(el.dataset.f==='confirmedBySub')w.approved=w.confirmedBySub;audit('Subcontractor set '+el.dataset.f+'='+w[el.dataset.f],w.name);save();render();};
FORMS.addworker=function(f,d){if(!d.username&&!d.email){toast('Username or email needed.');return;}if(loginTaken(d.username,d.email)){toast('Username/email already used.');return;}if(d.pw.length<6){toast('Password at least 6 characters.');return;}
  var w={id:uid('u'),type:'worker',name:d.name,username:d.username,email:d.email,phone:'',passHash:hashPw(d.pw),active:true,suspended:false,createdAt:new Date().toISOString(),subId:ME.id,confirmedBySub:true,approved:true,profile:{},roles:[],orientations:[]};DB.users.push(w);audit('Added worker',w.name,'by '+ME.name);notify(w.id,'Welcome! Your employer '+employerName(w)+' created your account. Please sign in, accept Schedule C and upload your documents.');save();toast('Worker added.');render();};
VIEWS['sub:crews']=function(){var s=ME,ws=users('worker').filter(function(w){return w.subId===s.id;}),list=DB.shifts.filter(function(x){return x.kind==='crew'&&!x.test&&x.date>=today();}).sort(function(a,b){return a.date<b.date?-1:1;});
  var cb=companyBlockers(s);var x='<h1>Crew assignments</h1><p class="small muted">Place your workers on client crews. Only workers who are fully valid (and whose company documents are valid) for that date can be listed. You do not record hours in the app.</p>'+(cb.length?'<div class="alert bad"><b>Your company is blocked:</b> '+esc(cb.join(' '))+'</div>':'');
  list.forEach(function(sh){x+='<div class="card"><div class="row"><b>'+esc(sh.date)+' · '+esc(sh.start)+'–'+esc(sh.end)+'</b><span class="right pill s-mut">'+esc(roleLabel(sh))+'</span></div><div>'+esc(sh.title)+' – '+esc(siteName(sh.site))+'</div><div class="small muted">Crew size needed: '+sh.needed+(sh.orientation?' · site orientation required':'')+'</div><form data-form="crew"><input type="hidden" name="sid" value="'+sh.id+'">'+
    ws.map(function(w){var bl=blockers(w,sh.date,sh),on=(sh.booked||[]).indexOf(w.id)>=0;return '<label class="inline"><input type="checkbox" name="w[]" value="'+w.id+'"'+(on?' checked':'')+(bl.length&&!on?' disabled':'')+'> <span><b>'+esc(w.name)+'</b> '+(bl.length?'<span class="small" style="color:#c0392b">– blocked: '+esc(bl[0].m)+'</span>':'<span class="pill s-ok">OK for this date</span>')+'</span></label>';}).join('')+
    '<button class="small">Save crew</button></form></div>';});
  return x+(list.length?'':'<p class="muted">No upcoming crew requests.</p>');};
FORMS.crew=function(f,d){var sh=DB.shifts.filter(function(x){return x.id===d.sid;})[0];var chosen=d.w||[];
  var mine=users('worker').filter(function(w){return w.subId===ME.id;}).map(function(w){return w.id;});
  var bad=chosen.filter(function(id){return blockers(user(id),sh.date,sh).length;});if(bad.length){toast(user(bad[0]).name+' is blocked for this date.');return;}
  var others=(sh.booked||[]).filter(function(id){return mine.indexOf(id)<0;});
  if(chosen.length>=5&&!(ME.company.supervisors||'').trim()){toast('Crews of 5 or more need at least one on-site supervisor (Company details).');return;}
  if(others.length+chosen.length>sh.needed){toast('Only '+sh.needed+' workers needed.');return;}
  sh.booked=others.concat(chosen);audit('Crew updated',ME.name,sh.date+' '+sh.site+': '+chosen.length+' worker(s)');save();toast('Crew saved.');render();};

/* ---------- Invoicing portal ---------- */
function invNextNumber(u){var pre=u.type==='tester'?'TEST-'+String(u.username||u.name).replace(/[^A-Za-z0-9]/g,'').toUpperCase().slice(0,6):u.code;var n=DB.invoices.filter(function(i){return i.subId===u.id;}).length+1,num;do{num=pre+'-'+('00'+n).slice(-3);n++;}while(DB.invoices.some(function(i){return i.number===num;}));return num;}
function expectedPay(i){if(i.test)return 'Never – TEST invoice';if(i.status==='Paid')return 'Paid '+i.paidDate;if(DB.settings.paymentTerms==='net30_farm')return 'Net 30 after the farm pays (office sets date)';return i.due||'';}
function invoiceList(u){var mine=DB.invoices.filter(function(i){return i.subId===u.id;}).sort(function(a,b){return a.date<b.date?1:-1;});
  return '<div class="tw"><table><tr><th>Invoice #</th><th>Period</th><th>Subtotal</th><th>HST 15%</th><th>Total</th><th>Status</th><th>Expected payment</th></tr>'+mine.map(function(i){return '<tr><td><a href="#" data-act="showinv" data-id="'+i.id+'">'+esc(i.number)+'</a>'+(i.test?' <span class="badge-test">TEST</span>':'')+'</td><td>'+esc(i.periodStart)+' → '+esc(i.periodEnd)+'</td><td>'+money(i.subtotal)+'</td><td>'+money(i.hst)+'</td><td><b>'+money(i.total)+'</b></td><td>'+(i.test?'<span class="unpaid">TEST – NEVER PAID</span>':'<span class="pill '+({Submitted:'s-pend',Approved:'s-ok',Paid:'s-ok',Disputed:'s-bad'}[i.status])+'">'+esc(i.status)+'</span>')+(invoiceHeld(i)?' <span class="pill s-bad">PAYMENT ON HOLD</span>':'')+(i.disputeReason?'<div class="small">Disputed: '+esc(i.disputeReason)+'</div>':'')+'</td><td class="small">'+esc(expectedPay(i))+'</td></tr>';}).join('')+'</table></div>';}
VIEWS['sub:invoices']=VIEWS['tester:invoices']=function(){var u=ME,test=u.type==='tester',c=test?{legalName:u.name+' (TEST)',bn:'000000000',hst:'',address:'(test)'}:u.company,due=test?{periodStart:addDays(today(),-29),periodEnd:today()}:invoiceDue(u);
  PAGE_STATE.invStart=Date.now();
  var x='<h1>'+(test?'Test invoices <span class="badge-test">TEST</span>':'Invoices')+'</h1>'+(test?'<div class="alert warn">Testing only: anything you submit here is a <b>TEST invoice – never approved for payment and never paid</b>.</div>':holdBanner(u));
  if(!test&&!(c.bankAcct||latestDoc(u.id,'bank_letter')))x+='<div class="alert bad">Add banking details (Company details) before your first invoice.</div>';
  if(!test&&due.overdue)x+='<div class="alert warn">Your invoice for '+due.periodStart+' to '+due.periodEnd+' is due.'+(due.daysLate>45?' Invoices more than 60 days late are not payable under the agreement.':'')+'</div>';
  if(!test&&tempActive(u))x+='<div class="alert warn">'+tempBadge(u)+' You can still submit invoices, but they are <b>held</b> (not paid) until you are fully compliant.</div>';
  x+='<div class="card hl"><h2 style="margin-top:0">New invoice (one every 30 days)</h2><form data-form="invoice"><div class="grid2">'+inp('number','Invoice number',invNextNumber(u),{req:true,hint:'Format: [subcontractor code]-### (owner to confirm).'})+inp('date','Invoice date',today(),{type:'date',req:true})+inp('periodStart','Period start',due.periodStart,{type:'date',req:true})+inp('periodEnd','Period end',due.periodEnd,{type:'date',req:true})+'</div>'+
  '<fieldset><legend>Business details – please check every time</legend><div class="grid2">'+inp('legalName','Legal business name',c.legalName,{req:true})+inp('bn','CRA Business Number',c.bn,{req:true})+inp('hstNo','HST number (if different)',c.hst)+'</div><div class="small muted">Address: '+esc(c.address||'')+(c.bankAcct?' · Pay to account '+last(dec(c.bankAcct),4):'')+'</div></fieldset>'+
  '<div class="grid2">'+inp('subtotal','Invoice amount (subtotal, before HST) $','',{type:'number',req:true,extra:' step="0.01" min="0.01" data-calc="inv"'})+'<div><label>15% PEI HST / Total</label><div id="invcalc" style="padding:9px 0;font-weight:600">HST $0.00 · Total $0.00</div></div>'+inp('farms','Farm(s)/client(s) covered (optional)','',{ph:'e.g. Test Farm A'})+inp('workOrders','Work order(s) (optional)','',{ph:'USDC-[client]-###'})+'</div><label>Note (optional)</label><textarea name="note"></textarea><label>Attach your own invoice PDF (optional)</label><input type="file" name="pdf" accept="application/pdf,image/*">'+
  '<p class="small muted">No hours are entered here. UnScramble may ask for supporting records through Records requests.</p>'+chk('confirm','<b>I confirm these details are correct.</b>',false,{req:true})+'<button>Review invoice</button></form></div><h2>My invoices</h2>'+invoiceList(u);
  return x;};
CALC.inv=function(el){var v=Number(el.value)||0,h=Math.round(v*15)/100;document.getElementById('invcalc').textContent='HST '+money(h)+' · Total '+money(v+h);};
FORMS.invoice=function(f,d){var u=ME,test=u.type==='tester';if(!d.confirm){toast('Please tick "I confirm these details are correct".');return;}
  var sub=Math.round(Number(d.subtotal)*100)/100;if(!(sub>0)){toast('Enter the invoice amount.');return;}
  if(!/^\d{9}$/.test(d.bn)){toast('Business Number must be 9 digits.');return;}
  if(DB.invoices.some(function(i){return i.number===d.number;})){toast('That invoice number is already used.');return;}
  var c=test?{}:u.company,changed=!test&&(d.legalName!==c.legalName||d.bn!==c.bn||(d.hstNo||'')!==(c.hst||''));
  readUpload(f.pdf.files[0],function(file){
    var hst=Math.round(sub*15)/100;var inv={id:uid('i'),subId:u.id,number:d.number,date:d.date,periodStart:d.periodStart,periodEnd:d.periodEnd,legalName:d.legalName,bn:d.bn,hstNo:d.hstNo,subtotal:sub,hst:hst,total:Math.round((sub+hst)*100)/100,farms:d.farms,workOrders:d.workOrders,note:d.note,pdf:file,confirmed:true,detailsChanged:changed,holdback:0,setoff:0,test:test,status:'Submitted',history:[]};
    PAGE_STATE.pendingInv=inv;
    modal('<h2>Review invoice '+esc(inv.number)+(test?' <span class="badge-test">TEST</span>':'')+'</h2>'+invoiceDetail(inv)+(changed?'<div class="alert warn small">You changed business details from your profile – the office will review the change.</div>':'')+'<p><button class="gold" data-act="invsubmit">Submit invoice</button> <button class="sec" data-act="closeModal">Go back</button></p><p class="small muted">Once submitted, the invoice is locked.</p>');});};
function invoiceDetail(i){var s=user(i.subId)||{},c=s.company||{};var net=i.total-(i.holdback||0)-(i.setoff||0);
  return (i.test?'<div class="alert warn"><b>TEST INVOICE – never approved for payment and never paid.</b></div>':'')+'<div class="kv"><div>Invoice #</div><div><b>'+esc(i.number)+'</b></div><div>Invoice date</div><div>'+esc(i.date)+'</div><div>Period</div><div>'+esc(i.periodStart)+' → '+esc(i.periodEnd)+'</div><div>Legal business name</div><div>'+esc(i.legalName)+'</div><div>Business Number</div><div>'+esc(i.bn)+'</div>'+(i.hstNo&&i.hstNo.indexOf(i.bn)!==0||i.hstNo&&i.hstNo!==i.bn?'<div>HST number</div><div>'+esc(i.hstNo)+'</div>':'')+'<div>Address</div><div>'+esc(c.address||'')+'</div><div>Pay to</div><div>'+(c.bankAcct?'Account '+last(dec(c.bankAcct),4):'–')+'</div>'+(i.farms?'<div>Farm(s)/client(s)</div><div>'+esc(i.farms)+'</div>':'')+(i.workOrders?'<div>Work order(s)</div><div>'+esc(i.workOrders)+'</div>':'')+(i.note?'<div>Note</div><div>'+esc(i.note)+'</div>':'')+'</div>'+
  '<div class="tw" style="margin-top:10px"><table><tr><td>Amount (subtotal)</td><td style="text-align:right">'+money(i.subtotal)+'</td></tr><tr><td>HST 15%</td><td style="text-align:right">'+money(i.hst)+'</td></tr><tr><th>Total</th><th style="text-align:right">'+money(i.total)+'</th></tr>'+(i.holdback?'<tr><td>Holdback</td><td style="text-align:right">−'+money(i.holdback)+'</td></tr>':'')+(i.setoff?'<tr><td>Set-off'+(i.setoffNote?' ('+esc(i.setoffNote)+')':'')+'</td><td style="text-align:right">−'+money(i.setoff)+'</td></tr>':'')+((i.holdback||i.setoff)?'<tr><th>Net payment</th><th style="text-align:right">'+money(net)+'</th></tr>':'')+'</table></div>'+(i.pdf?'<p><a href="#" data-act="invpdf" data-id="'+i.id+'">Attached file: '+esc(i.pdf.name)+'</a></p>':'');}
ACT.invsubmit=function(){var inv=PAGE_STATE.pendingInv;if(!inv)return;if(!inv.test&&tempActive(ME))inv.heldTemp=true;inv.submittedAt=today();inv.due=inv.test?'':(DB.settings.paymentTerms==='net30_submit'?addDays(today(),30):'');inv.history.push({at:new Date().toISOString(),what:'Submitted',by:ME.name});DB.invoices.push(inv);
  DB.events.push({u:ME.id,role:ME.type,test:inv.test,type:'invoice_submit',ms:Date.now()-(PAGE_STATE.invStart||Date.now()),screen:'#/invoices',at:new Date().toISOString(),d:today()});
  audit('Submitted '+(inv.test?'TEST ':'')+'invoice',ME.name,inv.number+' '+money(inv.total));if(!inv.test)notify('admin','Invoice '+inv.number+' submitted by '+inv.legalName+': '+money(inv.total)+(inv.detailsChanged?' (business details changed – review)':''));
  PAGE_STATE.pendingInv=null;save();closeModal();toast('Invoice submitted.');render();};
ACT.showinv=function(el){var i=DB.invoices.filter(function(x){return x.id===el.dataset.id;})[0];if(!i||(ME.type!=='admin'&&i.subId!==ME.id))return;modal('<h2>Invoice '+esc(i.number)+'</h2><p>Status: <b>'+esc(i.test?'TEST – never paid':i.status)+'</b> · Expected payment: '+esc(expectedPay(i))+'</p>'+invoiceDetail(i)+'<h3>History</h3><ul class="small">'+(i.history||[]).map(function(h){return '<li>'+fmtStamp(h.at)+' – '+esc(h.what)+' ('+esc(h.by)+')</li>';}).join('')+'</ul>');};
ACT.invpdf=function(el){var i=DB.invoices.filter(function(x){return x.id===el.dataset.id;})[0]||PAGE_STATE.pendingInv;if(i&&i.pdf)showFile(i.pdf.name,i.pdf.type,i.pdf.data,'Invoice attachment');};
VIEWS['sub:records']=function(){var mine=DB.records.filter(function(r){return r.subId===ME.id;});
  return '<h1>Records requests</h1><p class="small muted">UnScramble may ask for your time and payroll records. Please upload them within 5 business days.</p>'+holdBanner(ME)+(mine.map(function(r){var od=r.status==='Open'&&r.due<today();return '<div class="card'+(od?' hl':'')+'"><div class="row"><b>Requested '+esc(r.sentAt)+'</b><span class="pill '+(od?'s-bad':r.status==='Open'?'s-pend':'s-ok')+'">'+(od?'OVERDUE':esc(r.status))+'</span><span class="right small">Due '+esc(r.due)+'</span></div><p>'+esc(r.text)+'</p>'+(r.files.length?'<div class="small">Files: '+r.files.map(function(f,ix){return '<a href="#" data-act="recfile" data-id="'+r.id+'" data-i="'+ix+'">'+esc(f.name)+'</a>';}).join(', ')+'</div>':'')+(r.status!=='Closed'?'<form data-form="recup"><input type="hidden" name="rid" value="'+r.id+'"><input type="file" name="files" multiple required><button class="small">Upload files</button></form>':'')+'</div>';}).join('')||'<p class="muted">No requests.</p>');};
FORMS.recup=function(f,d){var r=DB.records.filter(function(x){return x.id===d.rid;})[0];var files=[].slice.call(f.files.files),n=files.length;if(!n)return;files.forEach(function(file){readUpload(file,function(x){if(x)r.files.push({name:x.name,type:x.type,data:x.data,at:new Date().toISOString()});if(--n===0){r.status='Submitted';audit('Uploaded records',ME.name,r.text);notify('admin','Records uploaded by '+ME.name+' for request of '+r.sentAt);if(save()){toast('Uploaded.');render();}}});});};
ACT.recfile=function(el){var r=DB.records.filter(function(x){return x.id===el.dataset.id;})[0];var f=r.files[+el.dataset.i];audit('Viewed records file',(user(r.subId)||{}).name,f.name);save();showFile(f.name,f.type,f.data,'Records');};
