/* v2-billing.js – OWNER DECISION: subcontractor invoices are NOT built from hours. Every 30 days the sub submits ONE total amount
   with business name and BN/HST number; no hours. HST 15% only when an HST number is given. Holdback % (Schedule A, default 10%)
   taken off each invoice, released after season reconciliation with logged office deductions. Pay held during a 14-day pass.
   Office can put an invoice "on hold" with a reason (e.g. unsettled farm change). Workers' hours page for subs (view only). TEST ONLY. */
'use strict';
function unpaidBreak(h,t){return h>=5&&!(t&&t.breakMissed)?BREAK_MIN/60:0;}

/* ---------- Subcontractor: workers' hours (view only – never used for invoices) ---------- */
function subRows(sub,from,to){var ws=users('worker').filter(function(w){return w.subId===sub.id;}).map(function(w){return w.id;}),rows=[];
  DB.time.forEach(function(t){if(t.test||!t.out||t.date<from||t.date>to)return;if(ws.indexOf(t.userId)<0)return;var sh=DB.shifts.filter(function(s){return s.id===t.shiftId;})[0];if(sh&&sh.test)return;
    rows.push({key:t.key0||('t:'+t.id),date:t.date,site:t.site||(sh&&sh.site),start:t.in,end:t.out,uid:t.userId,temp:!!t.temp,breakMissed:!!t.breakMissed});});
  DB.shifts.forEach(function(sh){if(sh.test||sh.kind!=='crew'||sh.date>today()||sh.date<from||sh.date>to)return;(sh.booked||[]).forEach(function(id){if(ws.indexOf(id)<0)return;if(DB.time.some(function(t){return t.userId===id&&t.shiftId===sh.id&&!t.test;}))return;rows.push({key:'c:'+sh.id+':'+id,date:sh.date,site:sh.site,start:sh.start,end:sh.end,uid:id,crew:true});});});
  rows.forEach(function(r){r.hours=hrs(r.start,r.end);r.paid=r.hours-unpaidBreak(r.hours,r);var c=latestChange(r.key);r.change=c;r.held=!!(c&&c.status==='Pending');});
  return rows.sort(function(a,b){return a.date<b.date?-1:a.date>b.date?1:a.uid<b.uid?-1:1;});}
VIEWS['sub:workerhours']=function(){var st=PAGE_STATE.wh||{},to=st.to||today(),from=st.from||addDays(to,-29);var rows=subRows(ME,from,to);
  var per={};rows.forEach(function(r){var p=per[r.uid]=per[r.uid]||{days:{},hours:0,paid:0,held:0};p.days[r.date]=1;p.hours+=r.hours;if(r.held)p.held+=r.paid;else p.paid+=r.paid;});
  var tot={hours:0,paid:0,held:0,days:0};Object.keys(per).forEach(function(k){tot.hours+=per[k].hours;tot.paid+=per[k].paid;tot.held+=per[k].held;tot.days+=Object.keys(per[k].days).length;});
  return '<h1>Workers\' hours</h1><p class="small muted">Hours completed by your workers (clocked in the app, or scheduled crew hours where nobody clocked). Paid hours = worked minus a 30-minute unpaid break on shifts of 5 h or more (not deducted when the worker ticked "Break missed or interrupted"). For your own payroll and records only – <b>your invoice is one total amount and never pulls these hours</b>. Farm bill rates are never shown.</p>'+
  '<form data-form="whrange" class="row card"><div><label>From</label><input type="date" name="from" value="'+from+'"></div><div><label>To</label><input type="date" name="to" value="'+to+'"></div><div style="align-self:flex-end"><button class="small">Show</button></div></form>'+
  '<h2>Per worker</h2><div class="tw"><table id="whper"><tr><th>Worker</th><th>Days</th><th>Hours worked</th><th>Paid hours</th><th>Farm change pending</th></tr>'+Object.keys(per).map(function(k){var p=per[k];return '<tr><td><b>'+esc(user(k).name)+'</b></td><td>'+Object.keys(p.days).length+'</td><td>'+p.hours.toFixed(2)+'</td><td>'+p.paid.toFixed(2)+'</td><td>'+(p.held?'<span class="pill s-pend">'+p.held.toFixed(2)+'</span>':'–')+'</td></tr>';}).join('')+'<tr><th>Period total</th><th>'+tot.days+'</th><th id="whtot">'+tot.hours.toFixed(2)+'</th><th id="whpaid">'+tot.paid.toFixed(2)+'</th><th>'+tot.held.toFixed(2)+'</th></tr></table></div>'+
  '<h2>By day and site</h2><div class="tw"><table><tr><th>Day</th><th>Site</th><th>Worker</th><th>Start – finish</th><th>Hours</th><th>Status</th></tr>'+rows.map(function(r){return '<tr><td>'+shortDay(r.date)+'</td><td>'+esc(r.site)+'</td><td>'+esc(user(r.uid).name)+(r.temp?' <span class="badge-temp">PASS</span>':'')+'</td><td>'+esc(r.start)+' – '+esc(r.end)+plus1(r.start,r.end)+(r.crew?'<div class="small muted">scheduled crew hours</div>':'')+(r.breakMissed?'<div class="small"><span class="pill s-warn">Break missed – not deducted</span></div>':'')+'</td><td>'+r.hours.toFixed(2)+'</td><td>'+(r.held?'<span class="pill s-pend">Farm change pending</span>':r.change&&r.change.status!=='Rejected'?'<span class="pill s-ok">Farm change '+esc(r.change.status.toLowerCase())+'</span>':'<span class="pill s-ok">OK</span>')+'</td></tr>';}).join('')+'</table></div>';};
FORMS.whrange=function(f,d){if(d.from>d.to){toast('"From" must be before "To".');return;}PAGE_STATE.wh={from:d.from,to:d.to};render();};
(function(){var ow=VIEWS['sub:workers'];VIEWS['sub:workers']=function(){var x=ow();var ws=users('worker').filter(function(w){return w.subId===ME.id;});
  return x+'<div class="card" id="workerrates"><h3 style="margin-top:0">Pay rate you pay each worker (optional)</h3><p class="small">Only that worker sees it (in their Menu). UnScramble never shows farm bill rates to you or your workers.</p>'+ws.map(function(w){return '<form data-form="workerrate" class="row"><input type="hidden" name="id" value="'+w.id+'"><span style="min-width:150px"><b>'+esc(w.name)+'</b></span><input type="number" step="0.01" min="0" name="rate" value="'+esc(w.payRate||'')+'" placeholder="$ / hour" style="max-width:120px"><button class="small sec">Save</button></form>';}).join('')+'</div>';};})();
FORMS.workerrate=function(f,d){var w=user(d.id);if(!w||w.subId!==ME.id){toast('Not allowed.');return;}w.payRate=Number(d.rate)||'';audit('Subcontractor set worker pay rate',w.name,w.payRate?money(w.payRate):'cleared');save();toast('Saved.');render();};

/* ---------- Invoice: one monthly total, no hours ---------- */
function hstFor(sub,hstNo){return String(hstNo||'').trim()?Math.round(sub*15)/100:0;}
(function(){var ov=VIEWS['sub:invoices'];VIEWS['sub:invoices']=VIEWS['tester:invoices']=function(){var x=ov(),a=SA();
  x=x.replace("inp('hstNo'","").replace(/HST number \(if different\)/,'HST number (leave empty if you have none – then no HST is charged)').replace('name="hstNo"','name="hstNo" data-calc="inv"');
  if(ME.type==='sub'){var hb=holdbackSummary(ME);x=x.replace('<h2 style="margin-top:0">New invoice (one every 30 days)</h2>','<h2 style="margin-top:0">New invoice (one every 30 days)</h2><p class="small">Enter <b>one total amount</b> for the month. Your legal business name, Business Number and HST number appear on the invoice – <b>no hours are listed</b> (your workers\' hours are on the Workers\' hours page). HST 15% is added only if you give an HST number. Holdback: <b>'+a.holdbackPct+'%</b> of the amount (before HST), released after the season reconciliation. Payment: '+esc(PAYTERMS[a.paymentTerms])+'.</p>');
    x=x.replace('<h2>My invoices</h2>','<div class="card" id="holdbackcard"><h3 style="margin-top:0">Holdback</h3><p>Currently held: <b>'+money(hb.held)+'</b> ('+a.holdbackPct+'% of each invoice amount). '+esc(a.holdbackRelease)+'</p>'+(hb.deductions.length?'<div class="small">Office deductions (logged): '+hb.deductions.map(function(d){return money(d.amount)+' – '+esc(d.reason)+' ('+esc(d.by)+', '+esc(d.at.slice(0,10))+')';}).join('; ')+'</div>':'')+(hb.releases.length?'<div class="small">Released: '+hb.releases.map(function(r){return money(r.released)+' on '+esc(r.at.slice(0,10))+(r.deductions?' (after '+money(r.deductions)+' deductions)':'');}).join('; ')+'</div>':'')+'</div><h2>My invoices</h2>');}
  return x;};})();
CALC.inv=function(el){var f=el.form||document;var v=Number((f.querySelector('[name=subtotal]')||{}).value)||0,hn=(f.querySelector('[name=hstNo]')||{}).value||'',h=hstFor(v,hn);var o=document.getElementById('invcalc');if(o)o.textContent=(hn.trim()?'HST '+money(h):'No HST (no HST number)')+' · Total '+money(v+h);};
FORMS.invoice=function(f,d){var u=ME,test=u.type==='tester';if(!d.confirm){toast('Please tick "I confirm these details are correct".');return;}
  var sub=Math.round(Number(d.subtotal)*100)/100;if(!(sub>0)){toast('Enter the invoice amount.');return;}
  if(!d.legalName){toast('Enter your legal business name.');return;}if(!/^\d{9}$/.test(d.bn)){toast('Business Number must be 9 digits.');return;}
  var hn=String(d.hstNo||'').trim();if(hn&&!/^\d{9}RT\d{4}$/.test(hn)){toast('HST number must look like 123456789RT0001 (or leave it empty).');return;}
  if(DB.invoices.some(function(i){return i.number===d.number;})){toast('That invoice number is already used.');return;}
  var c=test?{}:u.company,changed=!test&&(d.legalName!==c.legalName||d.bn!==c.bn||hn!==((c.hstNotReq?'':c.hst)||''));
  readUpload(f.pdf.files[0],function(file){var hst=hstFor(sub,hn),a=SA();
    var inv={id:uid('i'),subId:u.id,number:d.number,date:d.date,periodStart:d.periodStart,periodEnd:d.periodEnd,legalName:d.legalName,bn:d.bn,hstNo:hn,subtotal:sub,hst:hst,total:Math.round((sub+hst)*100)/100,farms:d.farms,workOrders:d.workOrders,note:d.note,pdf:file,confirmed:true,detailsChanged:changed,
      holdbackPct:test?0:a.holdbackPct,holdback:test?0:Math.round(sub*a.holdbackPct)/100,setoff:0,test:test,status:'Submitted',history:[],noHours:true};
    PAGE_STATE.pendingInv=inv;
    modal('<h2>Review invoice '+esc(inv.number)+(test?' <span class="badge-test">TEST</span>':'')+'</h2>'+invoiceDetail(inv)+(changed?'<div class="alert warn small">You changed business details from your profile – the office will review the change.</div>':'')+'<p><button class="gold" data-act="invsubmit">Submit invoice</button> <button class="sec" data-act="closeModal">Go back</button></p><p class="small muted">Once submitted, the invoice is locked.</p>');});};
/* pay held during a pass: the sub or any of its workers on a pass at submit time */
(function(){var os=ACT.invsubmit;ACT.invsubmit=function(el){var inv=PAGE_STATE.pendingInv;if(inv&&!inv.test){var pw=users('worker').filter(function(w){return w.subId===ME.id&&tempActive(w);}).map(function(w){return w.id;});if(pw.length){inv.heldTemp=true;inv.heldWorkers=pw;}}
  os(el);if(inv&&!inv.test){inv.due=SA().paymentTerms==='net30_receipt'?addDays(today(),30):'';save();}};})();
invoiceHeld=function(i){if(i.test||i.status==='Paid')return false;if(i.officeHold)return true;if(!i.heldTemp)return false;var s=user(i.subId);if(!s)return false;if(!companyCompliant(s))return true;return (i.heldWorkers||[]).some(function(id){var w=user(id);return w&&!workerDocsComplete(w);});};
heldInvoices=function(s){return DB.invoices.filter(function(i){return i.subId===s.id&&!i.test&&(i.heldTemp||i.officeHold)&&i.status!=='Paid';});};
function holdReason(i){if(i.officeHold)return 'On hold (office): '+i.officeHold.reason;return 'Held – 14-day document pass (released when documents are complete)';}
expectedPay=function(i){if(i.test)return 'Never – TEST invoice';if(i.status==='Paid')return 'Paid '+i.paidDate;if(invoiceHeld(i))return holdReason(i);if(!i.due)return 'Net 30 after the farm pays (office sets date)';return i.due+' (net 30 from receipt)';};
(function(){var oi=invoiceDetail;invoiceDetail=function(i){var x=oi(i);
  x=x.replace('<tr><td>HST 15%</td>','<tr><td>HST 15%'+(i.hstNo?'':' – <span class="small">not charged: no HST number</span>')+'</td>');
  x=x.replace('<tr><td>Holdback</td>','<tr><td>Holdback'+(i.holdbackPct?' '+i.holdbackPct+'% of amount (released after season reconciliation)':'')+'</td>');
  x+='<p class="small muted">One total amount – no hours are listed on this invoice.</p>';
  if(i.officeHold)x+='<div class="alert bad small"><b>On hold (office):</b> '+esc(i.officeHold.reason)+' – '+esc(i.officeHold.by)+', '+esc(i.officeHold.at.slice(0,10))+'</div>';
  else if(invoiceHeld(i))x+='<div class="alert warn small"><b>Pay held during 14-day pass</b> – released when documents are complete.</div>';
  return x;};})();
(function(){var op=paymentHold;paymentHold=function(s){var r=op(s);DB.invoices.forEach(function(i){if(i.subId===s.id&&i.officeHold&&!i.test&&i.status!=='Paid')r.push('invoice '+i.number+' on hold by the office: '+i.officeHold.reason);});return r;};})();

/* ---------- Office: put an invoice on hold with a reason (e.g. tied to an unsettled farm change) ---------- */
(function(){var oa=VIEWS['admin:invoicesadmin'];VIEWS['admin:invoicesadmin']=function(){var x=oa(),a=SA();
  var open=DB.invoices.filter(function(i){return !i.test&&i.status!=='Paid';});
  x+='<h2>Payment holds</h2><p class="small muted">Put an invoice on hold with a reason, e.g. while a farm change tied to it is unsettled. Holds during a 14-day pass are automatic.</p><div class="tw"><table id="holdtable"><tr><th>Invoice</th><th>Subcontractor</th><th>Total</th><th>Hold</th><th></th></tr>'+open.map(function(i){return '<tr><td>'+esc(i.number)+'</td><td>'+esc(i.legalName)+'</td><td>'+money(i.total)+'</td><td class="small">'+(invoiceHeld(i)?'<span class="pill s-bad">On hold</span> '+esc(holdReason(i)):'–')+'</td><td>'+(i.officeHold?'<button class="small sec" data-act="invunhold" data-id="'+i.id+'">Release hold</button>':'<form data-form="invhold" class="row"><input type="hidden" name="id" value="'+i.id+'"><input type="text" name="reason" placeholder="Reason (required)" style="max-width:220px" required><button class="small sec">Put on hold</button></form>')+'</td></tr>';}).join('')+'</table></div>';
  x+='<h2>Holdback – season reconciliation</h2><p class="small muted">Holdback is '+a.holdbackPct+'% of each invoice amount (Schedule A). Release it after the end-of-season reconciliation. Every deduction is logged with a reason.</p><div class="tw"><table id="hbtable"><tr><th>Subcontractor</th><th>Holdback held</th><th>Deductions (logged)</th><th>Add deduction</th><th>Release</th></tr>'+users('sub').map(function(s){var h=holdbackSummary(s),ded=h.deductions.reduce(function(t,d){return t+d.amount;},0);
    return '<tr><td>'+esc(s.company.legalName||s.name)+'</td><td><b>'+money(h.held)+'</b></td><td class="small">'+(h.deductions.map(function(d){return money(d.amount)+' – '+esc(d.reason)+' ('+esc(d.by)+')';}).join('<br>')||'–')+'</td><td><form data-form="holdded" class="row"><input type="hidden" name="id" value="'+s.id+'"><input type="number" name="amount" step="0.01" min="0.01" placeholder="$" style="max-width:90px" required><input type="text" name="reason" placeholder="Reason (required)" style="max-width:170px" required><button class="small sec">Deduct</button></form></td><td>'+(h.held>0?'<button class="small" data-act="holdrel" data-id="'+s.id+'">Release '+money(Math.max(0,h.held-ded))+'</button>':'–')+'</td></tr>';}).join('')+'</table></div>';
  return x;};})();
FORMS.invhold=function(f,d){var i=DB.invoices.filter(function(x){return x.id===d.id;})[0];if(!i||i.test){toast('Not allowed.');return;}if(!d.reason){toast('A reason is required.');return;}
  i.officeHold={reason:d.reason,by:ME.name,at:new Date().toISOString()};i.history.push({at:i.officeHold.at,what:'Put on hold: '+d.reason,by:ME.name});audit('Invoice put on hold',i.number,d.reason);notify(i.subId,'Invoice '+i.number+' is on hold: '+d.reason);save();toast('Invoice on hold.');render();};
ACT.invunhold=function(el){var i=DB.invoices.filter(function(x){return x.id===el.dataset.id;})[0];if(!i||!i.officeHold)return;var r=i.officeHold.reason;delete i.officeHold;i.history.push({at:new Date().toISOString(),what:'Hold released (was: '+r+')',by:ME.name});audit('Invoice hold released',i.number,r);notify(i.subId,'The hold on invoice '+i.number+' was released.');save();render();};
(function(){var oa=ACT.invact;ACT.invact=function(el){var i=DB.invoices.filter(function(x){return x.id===el.dataset.id;})[0];if(i&&el.dataset.a==='paid'&&invoiceHeld(i)){toast('Payment on hold: '+holdReason(i));return;}return oa(el);};})();

/* ---------- Holdback summary / deductions / release ---------- */
function holdbackSummary(s){var inv=DB.invoices.filter(function(i){return i.subId===s.id&&!i.test&&!i.holdbackReleased;});return {held:Math.round(inv.reduce(function(a,i){return a+(i.holdback||0);},0)*100)/100,invoices:inv,deductions:DB.deductions.filter(function(d){return d.subId===s.id&&!d.applied;}),releases:DB.holdbackReleases.filter(function(r){return r.subId===s.id;})};}
FORMS.holdded=function(f,d){var s=user(d.id),amt=Math.round(Number(d.amount)*100)/100;if(!(amt>0)||!d.reason){toast('Enter an amount and a reason.');return;}var h=holdbackSummary(s),ded=h.deductions.reduce(function(t,x){return t+x.amount;},0);if(amt+ded>h.held){toast('Deductions would be more than the holdback held.');return;}
  DB.deductions.push({id:uid('dd'),subId:s.id,amount:amt,reason:d.reason,by:ME.name,at:new Date().toISOString()});audit('Holdback deduction',s.company.legalName,money(amt)+': '+d.reason);notify(s.id,'UnScramble logged a holdback deduction of '+money(amt)+': '+d.reason);save();toast('Deduction logged.');render();};
ACT.holdrel=function(el){var s=user(el.dataset.id),h=holdbackSummary(s);if(!confirmBox('hr'+s.id,'Release the holdback for '+s.company.legalName+' after season reconciliation?'))return;var ded=h.deductions.reduce(function(a,d){return a+d.amount;},0),rel=Math.round((h.held-ded)*100)/100;
  h.invoices.forEach(function(i){i.holdbackReleased=true;i.history.push({at:new Date().toISOString(),what:'Holdback released (season reconciliation)',by:ME.name});});h.deductions.forEach(function(d){d.applied=true;});
  DB.holdbackReleases.push({id:uid('hr'),subId:s.id,held:h.held,deductions:ded,released:rel,by:ME.name,at:new Date().toISOString()});audit('Released holdback (season reconciliation)',s.company.legalName,'held '+money(h.held)+', deductions '+money(ded)+', released '+money(rel));notify(s.id,'Your holdback was released after the season reconciliation: '+money(rel)+(ded?' (after '+money(ded)+' of logged deductions)':'')+'.');save();toast('Released '+money(rel)+'.');render();};
