/* v2-crew.js – SUB CREW CLOCKING + safety gear on Project Assignments. TEST ONLY.
   - A subcontractor marks one or more of its workers as "crew lead".
   - On a booked crew shift, the crew lead opens "Clock my crew": the sub's workers on that shift, bulk "Clock in all" / "Clock out all",
     per-worker adjust (quarter-hour times), break taken yes/no.
   - These hours feed CLIENT BILLING only (5-hour daily minimum, break deducted only if taken, client may propose edits within 7 days,
     office approval final). The subcontractor's pay is NOT calculated from them – the sub still invoices one lump total with no hours.
   - Office sees each entry flagged "Clocked by crew lead <name>".
   - Every client Project Assignment (shift booking) needs "Safety gear supplied by: Client / UnScramble / Sub", shown to the sub and the crew lead. */
'use strict';
var GEAR_OPTS=['Client','UnScramble','Subcontractor'];
function gearText(sh){var g=sh&&sh.safetyGear==='Sub'?'Subcontractor':sh&&sh.safetyGear;return 'Safety gear (PPE) supplied by: '+(g||'not set');}
/* office shift form: required safety-gear field */
(function(){var os=VIEWS['admin:shiftsadmin'];if(!os)return;VIEWS['admin:shiftsadmin']=function(){return os().replace(/(<form data-form="newshift"><div class="grid2">)/,'$1<div><label class="req">Safety gear (PPE) supplied by:</label><select name="safetyGear" required><option value="">Choose…</option>'+GEAR_OPTS.map(function(g){return '<option value="'+g+'">'+g+'</option>';}).join('')+'</select></div>');};})();
(function(){var on=FORMS.newshift;FORMS.newshift=function(f,d){var test=d.site==='TEST-PRACTICE';if(!test&&GEAR_OPTS.indexOf(d.safetyGear)<0){toast('Choose who supplies the safety gear (PPE): Client, UnScramble or Subcontractor.');return;}var n=DB.shifts.length;on(f,d);if(DB.shifts.length>n){DB.shifts[DB.shifts.length-1].safetyGear=test?'UnScramble':d.safetyGear;save();render();}};})();
/* shown to the sub on its crew assignments page */
(function(){var oc=VIEWS['sub:crews'];VIEWS['sub:crews']=function(){var x=oc();DB.shifts.forEach(function(sh){x=x.replace('<input type="hidden" name="sid" value="'+sh.id+'">','<input type="hidden" name="sid" value="'+sh.id+'"><div class="small gearline"><b>'+esc(gearText(sh))+'</b>'+crewLeadsOn(sh)+'</div>');});return x;};})();
function crewLeadsOn(sh){var l=(sh.booked||[]).map(user).filter(function(u){return u&&u.crewLead;});return l.length?' · Crew lead: '+l.map(function(u){return esc(u.name);}).join(', '):'';}

/* sub marks crew leads */
ACT.crewlead=function(el){var w=user(el.dataset.id);if(!w||w.type!=='worker'||(ME.type!=='admin'&&w.subId!==ME.id)){toast('Not allowed.');return;}w.crewLead=!w.crewLead;audit((w.crewLead?'Made':'Removed')+' crew lead',w.name,'by '+ME.name);if(w.crewLead)notify(w.id,'You are now a crew lead. Use "Clock my crew" on your crew shifts.');save();render();};
(function(){var ow=VIEWS['sub:workers'];VIEWS['sub:workers']=function(){var x=ow(),ws=users('worker').filter(function(w){return w.subId===ME.id;});
  return x+'<div class="card" id="crewleads"><h3 style="margin-top:0">Crew leads</h3><p class="small">A crew lead clocks your crew in and out on client shifts. Those hours are used to bill the farm or other client only – your own invoice to UnScramble stays one total amount with no hours.</p>'+ws.map(function(w){return '<div class="row"><span style="min-width:170px"><b>'+esc(w.name)+'</b></span><button class="small '+(w.crewLead?'':'sec')+'" data-act="crewlead" data-id="'+w.id+'">'+(w.crewLead?'Crew lead ✓ (remove)':'Make crew lead')+'</button></div>';}).join('')+'</div>';};})();

/* crew lead screen */
function leadShifts(u){var days=(typeof CREW_FIX_DAYS==='number'?CREW_FIX_DAYS:7);return DB.shifts.filter(function(s){return s.kind==='crew'&&!s.test&&(s.booked||[]).indexOf(u.id)>=0&&s.date>=addDays(today(),-days)&&s.date<=today();}).sort(function(a,b){return a.date<b.date?1:-1;});}
function crewOf(u,sh){return (sh.booked||[]).map(user).filter(function(w){return w&&w.type==='worker'&&w.subId===u.subId;});}
function crewEntry(w,sh){return DB.time.filter(function(t){return t.userId===w.id&&t.shiftId===sh.id&&!t.test;})[0]||null;}
function hmMs(date,hm){var p=parseD(date);p.setHours(+hm.slice(0,2),+hm.slice(3,5),0,0);return p.getTime();}
VIEWS['worker:crew']=function(){var u=ME;if(!u.crewLead)return '<h1>Clock my crew</h1><p class="muted">Only crew leads (set by your employer) can clock a crew.</p>';var shs=leadShifts(u);PAGE_STATE.crewSid=PAGE_STATE.crewSid&&shs.some(function(s){return s.id===PAGE_STATE.crewSid;})?PAGE_STATE.crewSid:(shs[0]&&shs[0].id);var sh=shs.filter(function(s){return s.id===PAGE_STATE.crewSid;})[0];
  if(!sh)return '<h1>Clock my crew</h1><p class="muted">You have no crew shift today.</p>';var crew=crewOf(u,sh);
  var x='<h1>Clock my crew</h1>'+(shs.length>1?'<div class="row">'+shs.map(function(s){return '<button class="small '+(s.id===sh.id?'btn-indigo':'btn-indigo-outline')+'" data-act="crewpick" data-id="'+s.id+'">'+esc(s.date+' '+s.site)+'</button>';}).join(' ')+'</div>':'')+
  '<div class="card"><b>'+esc(sh.title)+'</b> – '+esc(siteName(sh.site))+'<div class="small">'+esc(sh.date)+' · scheduled '+esc(sh.start)+'–'+esc(sh.end)+'</div><div class="small gearline"><b>'+esc(gearText(sh))+'</b></div><div class="small muted">These times are used to bill the client only (5-hour daily minimum per worker; the 30-minute break is deducted only if it was taken). The client can propose changes within 7 days; the office decision is final.</div></div>'+
  '<div class="card" id="crewbulk">'+quarterPicker('qCrewIn','Start time for everyone not clocked in yet')+'<button class="btn-indigo" data-act="crewinall" id="crewInAll">Clock in all</button></div>'+
  '<div class="tw"><table id="crewtable"><tr><th>Worker</th><th>In</th><th>Out</th><th>Break taken?</th><th></th></tr>'+crew.map(function(w){var t=crewEntry(w,sh);return '<tr data-w="'+esc(w.username||w.id)+'"><td><b>'+esc(w.name)+'</b>'+(w.id===u.id?' <span class="small muted">(you)</span>':'')+'<div class="small">'+(t?(t.out?'<span class="pill s-ok">Out '+esc(t.out)+'</span>':'<span class="pill s-pend">In since '+esc(t.in)+'</span>'):'<span class="pill s-mut">Not in</span>')+'</div></td>'+
    '<td><input form="ca_'+w.id+'" type="time" step="900" name="in" value="'+esc(t?t.in:'')+'" aria-label="In time for '+esc(w.name)+'"></td><td><input form="ca_'+w.id+'" type="time" step="900" name="out" value="'+esc(t&&t.out?t.out:'')+'" aria-label="Out time for '+esc(w.name)+'">'+(t&&t.out?plus1H(t.in,t.out):'')+'</td><td><label class="inline"><input form="ca_'+w.id+'" type="checkbox" name="breakTaken" value="1"'+(!t||!t.breakMissed?' checked':'')+'> <span>Yes</span></label></td><td><form id="ca_'+w.id+'" data-form="crewadj"><input type="hidden" name="sid" value="'+sh.id+'"><input type="hidden" name="wid" value="'+w.id+'"><button class="small btn-indigo-outline">Save</button></form></td></tr>';}).join('')+'</table></div>'+
  '<div class="card" id="crewbulkout">'+quarterPicker('qCrewOut','Finish time for everyone still clocked in',crew.map(function(w){var t=crewEntry(w,sh);return t&&!t.out?hmMs(sh.date,t.in):0;}).reduce(function(a,b){return Math.max(a,b);},0)||null)+'<label class="inline"><input type="checkbox" id="crewBreakAll" checked> <span>Everyone took their 30-minute break</span></label><br><button class="btn-gold" data-act="crewoutall" id="crewOutAll">Clock out all</button></div>';
  return x;};
ACT.crewpick=function(el){PAGE_STATE.crewSid=el.dataset.id;render();};
function crewGuard(sid){var u=ME;if(!u||u.type!=='worker'||!u.crewLead){toast('Only crew leads can clock a crew.');return null;}var sh=DB.shifts.filter(function(s){return s.id===sid;})[0];if(!sh||leadShifts(u).indexOf(sh)<0){toast('Not your crew shift.');return null;}return sh;}
function newCrewEntry(w,sh,hm){var t={id:uid('t'),userId:w.id,site:sh.site,shiftId:sh.id,role:jobRoleOf(w),date:sh.date,in:hm,out:'',clock:true,crewClock:true,clockedBy:ME.id,clockedByName:ME.name,realIn:new Date().toISOString(),test:false,subId:w.subId,note:''};DB.time.push(t);return t;}
ACT.crewinall=function(){var sh=crewGuard(PAGE_STATE.crewSid);if(!sh)return;var q=qVal('qCrewIn');if(!q){toast('Pick the start time.');return;}var hm=hmOf(q),n=0;
  crewOf(ME,sh).forEach(function(w){if(crewEntry(w,sh)||openEntry(w))return;var ne=newCrewEntry(w,sh,hm);ne.date=isoLocal(new Date(q));n++;});audit('Crew lead clocked in crew',ME.name,sh.site+' '+sh.date+' '+hm+' ('+n+' workers)');save();toast(n+' clocked in at '+hm+'.');render();};
ACT.crewoutall=function(){var sh=crewGuard(PAGE_STATE.crewSid);if(!sh)return;var q=qVal('qCrewOut');if(!q){toast('Pick the finish time.');return;}var hm=hmOf(q),bt=document.getElementById('crewBreakAll').checked,n=0;
  crewOf(ME,sh).forEach(function(w){var t=crewEntry(w,sh);if(!t||t.out||!t.crewClock)return;if(spanErr(t.in,hm))return;t.out=hm;t.breakMissed=!bt;t.clockedOutBy=ME.name;t.realOut=new Date().toISOString();n++;});
  audit('Crew lead clocked out crew',ME.name,sh.site+' '+sh.date+' '+hm+' ('+n+' workers, break '+(bt?'taken':'not taken')+')');if(!bt)notify(['admin'].concat(ME.subId?[ME.subId]:[]),'Crew lead '+ME.name+' reported no break taken for the crew at '+sh.site+' on '+sh.date+'. No break deducted – billable.');save();toast(n+' clocked out at '+hm+'.');render();};
FORMS.crewadj=function(f,d){var sh=crewGuard(d.sid);if(!sh)return;var w=user(d.wid);if(!w||crewOf(ME,sh).indexOf(w)<0){toast('Not on your crew.');return;}
  var q=function(v){return /^\d{2}:\d{2}$/.test(v||'')&&(+v.slice(3))%15===0;};if(!q(d['in'])){toast('Pick a start time on the quarter hour (:00, :15, :30, :45).');return;}if(d.out&&spanErr(d['in'],d.out)){toast(spanErr(d['in'],d.out));return;}if(overlapsAny(w.id,sh.date,d['in'],d.out||null,(crewEntry(w,sh)||{}).id)){toast('Those times overlap another entry for '+w.name+'.');return;}if(d.out&&(!q(d.out))){toast('Finish time must be on the quarter hour and after the start.');return;}
  var t=crewEntry(w,sh);if(!t){if(openEntry(w)){toast(w.name+' is already clocked in on their own phone.');return;}t=newCrewEntry(w,sh,d['in']);}else if(!t.crewClock){toast(w.name+' clocked themselves – ask the office to adjust.');return;}
  var before=t.in+'–'+(t.out||'')+plus1(t.in,t.out);t.in=d['in'];t.out=d.out||'';t.breakMissed=!d.breakTaken;t.clockedBy=t.clockedBy||ME.id;t.clockedByName=t.clockedByName||ME.name;t.adjustedBy=ME.name;
  audit('Crew lead adjusted time',w.name,sh.site+' '+sh.date+': '+before+' → '+t.in+'–'+(t.out||'')+plus1(t.in,t.out)+(t.breakMissed?' (no break)':''));save();toast('Saved for '+w.name+'.');render();};
NAV.worker=NAV.worker.concat([['#/crew','Clock my crew']]);
(function(){var om=menuView;menuView=function(){var x=om();if(!ME.crewLead)return x;return x.replace('<div class="menu-list">','<div class="menu-list"><a class="menu-item" href="#/crew"><span class="mi" aria-hidden="true">👥</span><span class="mt"><b>Clock my crew</b><small>Crew lead</small></span><span class="chev" aria-hidden="true">›</span></a>');};})();
(function(){var oc=clockView;clockView=function(){var x=oc();if(!ME.crewLead||!leadShifts(ME).length)return x;return '<a class="btn btn-gold" href="#/crew" id="crewbanner" style="display:block;margin-bottom:10px">👥 Clock my crew</a>'+x;};})();

/* office: flagged entries */
(function(){var of=VIEWS['admin:farmchanges'];VIEWS['admin:farmchanges']=function(){var l=DB.time.filter(function(t){return t.crewClock&&!t.test;}).slice(-60).reverse();
  return of()+'<h2>Crew-lead clock entries</h2><p class="small muted">Hours clocked by a subcontractor\'s crew lead. Used to bill the farm or other client only (not for the subcontractor\'s pay).</p><div class="tw"><table id="crewentries"><tr><th>Worker</th><th>Site · date</th><th>In–Out</th><th>Break</th><th>Flag</th></tr>'+(l.map(function(t){var w=user(t.userId);return '<tr><td>'+esc(w?w.name:'?')+'<div class="small muted">'+esc(w?employerName(w):'')+'</div></td><td>'+esc(t.site)+' · '+esc(t.date)+'</td><td>'+esc(t.in)+'–'+esc(t.out||'…')+'</td><td>'+(t.breakMissed?'Not taken':'Taken')+'</td><td><span class="pill s-warn crewflag">Clocked by crew lead '+esc(t.clockedByName)+'</span>'+(t.adjustedBy?'<div class="small">adjusted by '+esc(t.adjustedBy)+'</div>':'')+'</td></tr>';}).join('')||'<tr><td colspan="5" class="muted">None yet.</td></tr>')+'</table></div>';};})();
(function(){var op=ACT.person;ACT.person=function(el){op(el);var u=user(el.dataset.id);if(!u)return;var l=DB.time.filter(function(t){return t.userId===u.id&&t.crewClock;});var m=document.querySelector('#modal .modal');if(m&&l.length)m.insertAdjacentHTML('beforeend','<h3>Crew-lead clock entries</h3><ul class="small">'+l.slice(-10).map(function(t){return '<li>'+esc(t.date+' '+t.site+' '+t.in+'–'+(t.out||'…'))+' – <b>Clocked by crew lead '+esc(t.clockedByName)+'</b></li>';}).join('')+'</ul>');};})();

/* seed: crewleadA (subco, works at firmA) + 3 sample crew workers on today's crew shift at TFA-01 */
function seedCrew(db){db.shifts.forEach(function(s){if(!s.safetyGear)s.safetyGear=s.test?'UnScramble':'Client';});if(db.users.some(function(u){return u.username==='crewleadA';}))return;
  var w1=db.users.filter(function(u){return u.username==='worker1';})[0];if(!w1)return;var made=[];
  [['crewleadA','Lee Crewlead',true],['crew1','Ari Crewsample',false],['crew2','Bea Crewsample',false],['crew3','Cy Crewsample',false]].forEach(function(c){var u=JSON.parse(JSON.stringify(w1));u.id=uid('u');u.username=c[0];u.name=c[1];u.email=c[0]+'@example.com';u.jobRole='field';u.roles=[];u.crewLead=c[2];u.lastLogin=null;delete u.temp;delete u.tempHistory;
    if(u.profile){u.profile.firstName=c[1].split(' ')[0];u.profile.lastName=c[1].split(' ')[1];}db.users.push(u);made.push(u);
    (db.acceptances||[]).filter(function(a){return a.userId===w1.id;}).forEach(function(a){var b=JSON.parse(JSON.stringify(a));b.id=uid('a');b.userId=u.id;db.acceptances.push(b);});
    (db.quizAttempts||[]).filter(function(a){return a.userId===w1.id&&a.pass;}).forEach(function(a){var b=JSON.parse(JSON.stringify(a));b.id=uid('qa');b.userId=u.id;db.quizAttempts.push(b);});
    (db.consents||[]).filter(function(a){return a.userId===w1.id;}).forEach(function(a){var b=JSON.parse(JSON.stringify(a));b.userId=u.id;db.consents.push(b);});});
  db.shifts.push({id:uid('s'),date:today(),start:'07:00',end:'15:00',title:'Harvest crew (crew lead clocks)',site:'TFA-01',kind:'crew',role:'general',needed:4,booked:made.map(function(u){return u.id;}),orientation:false,test:false,safetyGear:'Client'});}
(function(){var os=seedV2;seedV2=function(db,o){os(db,o);seedCrew(db);};})();
(function(){var ol=load;load=function(){ol();if(DB&&!DB.users.some(function(u){return u.username==='crewleadA';})){seedCrew(DB);save();}};})();
ROLE_ONLY.crewinall=['worker'];ROLE_ONLY.crewoutall=['worker'];ROLE_ONLY.crewadj=['worker'];ROLE_ONLY.crewpick=['worker'];ROLE_ONLY.crewlead=['sub','admin'];
