/* v2-clock.js – UnScramble clock (writes DB.time → reg_time_entries). The only US clock; no Shift Tracker redirect. */
'use strict';
var QMS=900000;
function hmOf(ms){var d=new Date(ms);return pad(d.getHours())+':'+pad(d.getMinutes());}
function msOfHM(hm){var p=hm.split(':'),d=new Date();d.setHours(+p[0],+p[1],0,0);return d.getTime();}
/* the 4 quarter-hour times nearest to now, within ±1 hour (finish times must be after the start) */
function quarterOpts(after,base){var now=base||Date.now(),q0=Math.round(now/QMS)*QMS,c=[];for(var k=-4;k<=4;k++){var t=q0+k*QMS;if(Math.abs(t-now)<=3600000&&(!after||t>after))c.push(t);}
  if(!c.length&&after)c=[Math.ceil((after+1)/QMS)*QMS];
  var four=c.sort(function(a,b){return Math.abs(a-now)-Math.abs(b-now);}).slice(0,4).sort(function(a,b){return a-b;});
  /* pre-select the nearest PAST quarter hour (never a time that has not happened yet) */
  var fl=Math.floor(now/QMS)*QMS;var pre=four.indexOf(fl)>=0?fl:four.indexOf(q0)>=0?q0:four.reduce(function(best,t){return Math.abs(t-now)<Math.abs(best-now)?t:best;},four[0]);return {four:four,pre:pre};}
function qName(t){return ({0:'full hour',15:'quarter past',30:'half past',45:'quarter to'})[new Date(t).getMinutes()]||'';}
function quarterPicker(id,label,after,base){var q=quarterOpts(after,base);return '<div class="qpick-box"><div class="label">'+esc(label)+' <span class="req-star">*</span></div><div class="qpick" id="'+id+'" role="radiogroup" aria-label="'+esc(label)+'">'+q.four.map(function(t){return '<button type="button" role="radio" class="qopt'+(t===q.pre?' sel':'')+'" aria-checked="'+(t===q.pre)+'" data-act="qopt" data-t="'+t+'"><b>'+hmOf(t)+'</b></button>';}).join('')+'</div><div class="muted small">Times are rounded to the quarter hour. Your real clock time is saved too.</div></div>';}
ACT.qopt=function(el){[].forEach.call(el.parentNode.querySelectorAll('.qopt'),function(x){x.classList.toggle('sel',x===el);x.setAttribute('aria-checked',String(x===el));});if(el.parentNode.id==='qIn')clockInLabel();};
/* sticky clock-in button shows the chosen site and start time, e.g. "Clock in at HTP250 · 07:00" */
function clockInLabel(){var b=document.getElementById('clockinBtn');if(!b)return;var t=qVal('qIn');if(PAGE_STATE.site){b.disabled=false;b.textContent='Clock in at '+PAGE_STATE.site+(t?' · '+hmOf(t):'');}else{b.disabled=true;b.textContent='Pick a site to clock in'+(t?' · '+hmOf(t):'');}}
function qVal(id){var x=document.querySelector('#'+id+' .qopt.sel');return x?+x.dataset.t:null;}
function fmtDur(h){var m=Math.max(0,Math.round(h*60));return Math.floor(m/60)+'h '+pad(m%60)+'m';}
function openEntry(u){return DB.time.filter(function(t){return t.userId===u.id&&t.clock&&!t.out&&!t.test;})[0]||null;}
function readyForClock(u){return u.accountApproved!==false&&blockers(u,today()).length===0;}
function clockSites(){return (typeof companySites==='function'?companySites({withFirm:true}):DB.sites.filter(function(s){return s.firmId;}));}
function siteTile(s){return '<button type="button" class="site-tile" data-act="picksite" data-code="'+esc(s.code)+'">'+esc(s.code)+'<small class="tile-co">'+esc(s.name)+'</small></button>';}
ACT.picksite=function(el){PAGE_STATE.site=el.dataset.code;[].forEach.call(document.querySelectorAll('.site-tile'),function(x){x.classList.toggle('sel',x.dataset.code===PAGE_STATE.site);});clockInLabel();};
var PRIVACY_TXT='📍 <b>Privacy:</b> your phone location is checked <b>once, when you tap Clock in</b>, to confirm you are at the site (simulated in this test). It is not tracked during your shift or after you clock out.';
function passBoxFor(u){return u.type==='worker'?(tempActive(u)?tempBox(u):tempBox(subOf(u))):'';}
function clockView(){var u=ME,open=openEntry(u),now=Date.now(),nm=esc(((u.profile&&u.profile.preferredName)||u.name).split(' ')[0]);
  if(open){var started=open.realIn?new Date(open.realIn).getTime():msOfHM(open.in),el=(now-started)/3600000;
    return '<h1 class="h1">Hi, '+nm+'</h1>'+passBoxFor(u)+'<div class="card clock-card on"><div class="status-pill on">● On shift</div><div class="site-big">'+esc(open.site)+'</div><div class="since">Started at <b>'+esc(open.in)+'</b></div><div class="elapsed" data-elapsed="'+started+'">'+fmtDur(el)+'</div>'+
    (el>14?'<div class="alert warn small">You have been clocked in for over 14 hours. Did you forget to clock out?</div>':'')+(open.note?'<div class="small">📝 '+esc(open.note)+'</div>':'')+
    '<div class="crew-box"><div class="crew-q">How many workers were at '+esc(open.site)+' this shift? <span class="req-star">*</span></div><div class="muted small">Count everyone working there with you, including yourself (1–50).</div><div class="stepper"><button type="button" class="step" data-act="crewstep" data-d="-1" aria-label="One less">−</button><input id="crew" type="number" inputmode="numeric" min="1" max="50" placeholder="?" aria-label="Workers on site"><button type="button" class="step" data-act="crewstep" data-d="1" aria-label="One more">+</button></div></div>'+
    quarterPicker('qOut','What time did you finish?',open.inMs||msOfHM(open.in))+
    '<label class="inline breakbox"><input type="checkbox" id="breakMissed"> <span><b>I did not get my break</b><br><small class="muted">Tick this if your break was missed or cut short. You will be paid for it, and the office is told.</small></span></label>'+
    '<label class="field outnote"><span>Clock-out note (optional)</span><textarea id="outNote" maxlength="120" rows="2" placeholder="e.g. finished early, supplies low, gate left open"></textarea><small class="muted">Saved when you clock out. You can\'t change it afterwards.</small></label>'+
    '<button class="btn danger huge" data-act="clockout2" id="clockoutBtn" disabled>Enter workers on site to clock out</button></div>';}
  var mine=DB.time.filter(function(t){return t.userId===u.id&&t.site;}).sort(function(a,b){return a.date<b.date?1:-1;});var recent=[];mine.forEach(function(t){if(recent.indexOf(t.site)<0&&recent.length<3)recent.push(t.site);});
  var sites=clockSites(),bySite=function(c){return sites.filter(function(s){return s.code===c;})[0];};PAGE_STATE.site=null;
  return '<h1 class="h1">Hi, '+nm+'</h1>'+passBoxFor(u)+'<div class="card clock-card"><div class="row-between"><div class="status-pill">○ Off shift</div><div class="muted">'+esc(shortDay(today()))+'</div></div><div class="bigclock" data-live-clock>'+hmOf(now)+'</div>'+
  quarterPicker('qIn','What time did you start?')+
  '<div class="label">Which site are you at? <span class="req-star">*</span></div>'+(recent.filter(bySite).length?'<div class="sub">Your recent sites</div><div class="tiles recent">'+recent.filter(bySite).map(function(c){return siteTile(bySite(c));}).join('')+'</div>':'')+
  '<input class="site-search" id="siteSearch" autocapitalize="characters" autocomplete="off" aria-label="Search site code" placeholder="Type a site code (e.g. TFA-01)…"><div class="tiles all" id="allTiles">'+sites.map(siteTile).join('')+'</div><div class="muted small">Site not listed? Ask your driver or contact the office.</div>'+
  '<div class="label">Location check</div><div class="privacy small">'+PRIVACY_TXT+'</div><label class="field"><span>Notes (optional)</span><textarea id="notes" maxlength="120" rows="2" placeholder="e.g. ride partner"></textarea></label>'+
  '<div class="sticky-cta"><button class="btn primary huge" id="clockinBtn" data-act="clockin2" disabled>Pick a site to clock in</button></div></div>';}
document.addEventListener('input',function(e){if(e.target.id==='siteSearch'){var v=e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g,'');[].forEach.call(document.querySelectorAll('#allTiles .site-tile'),function(t){t.style.display=!v||t.dataset.code.indexOf(v)>=0?'':'none';});}if(e.target.id==='crew')crewChanged();});
function crewChanged(){var i=document.getElementById('crew'),b=document.getElementById('clockoutBtn');if(!i||!b)return;var ok=/^\d+$/.test(i.value)&&+i.value>=1&&+i.value<=50;b.disabled=!ok;b.textContent=ok?'Clock out':'Enter workers on site to clock out';}
ACT.crewstep=function(el){var i=document.getElementById('crew');var c=parseInt(i.value,10);i.value=isNaN(c)?1:Math.min(50,Math.max(1,c+(+el.dataset.d)));crewChanged();};
ACT.clockin2=function(){var u=ME,site=PAGE_STATE.site;if(!site){toast('Pick a site first.');return;}if(openEntry(u)){toast('You are already clocked in.');return;}
  if(!readyForClock(u)){toast('You can\'t clock in yet. Your checklist shows why.');go('#/checklist');return;}
  var chosen=qVal('qIn')||Date.now(),sh=DB.shifts.filter(function(s){return s.date===today()&&s.site===site&&(s.booked||[]).indexOf(u.id)>=0&&!s.test;})[0];
  if(sh){var bl=blockers(u,today(),sh);if(bl.length){toast(bl[0].m);return;}}
  var note=((document.getElementById('notes')||{}).value||'').trim();
  DB.time.push({id:uid('t'),userId:u.id,site:site,shiftId:sh?sh.id:null,role:sh?sh.role:jobRoleOf(u),date:today(),in:hmOf(chosen),inMs:chosen,realIn:new Date().toISOString(),out:'',clock:true,test:false,temp:u.type==='worker'&&(tempActive(subOf(u))||tempActive(u)),subId:u.subId||null,note:note,loc:'Location check-in (simulated)'});
  audit('Clocked in',u.name,site+' at '+hmOf(chosen));save();toast('Clocked in ✓');render();};
ACT.clockout2=function(){var u=ME,t=openEntry(u);if(!t)return;var crew=+(document.getElementById('crew')||{}).value;if(!(crew>=1&&crew<=50)){toast('Enter the number of workers on site (1–50).');return;}var fin=qVal('qOut');if(!fin){toast('Pick the time you finished.');return;}
  var note=((document.getElementById('outNote')||{}).value||'').trim(),bm=!!(document.getElementById('breakMissed')||{}).checked;PAGE_STATE.co={fin:fin,crew:crew,note:note,bm:bm};
  modal('<h2>Clock out now?</h2><p>Finish time: <b>'+hmOf(fin)+'</b> <span class="muted small">(real time '+hmOf(Date.now())+' is saved too)</span><br>Workers on site: <b>'+crew+'</b>'+(bm?'<br><b>Break missed or interrupted</b> – no break deducted; the office is told.':'')+(note?'<br>Note: “'+esc(note)+'” <span class="muted small">(can\'t be changed later)</span>':'')+'</p><div class="row-end"><button class="btn sec" data-act="closeModal">Cancel</button><button class="btn danger" data-act="clockoutyes">Clock out</button></div>');};
ACT.clockoutyes=function(){var u=ME,t=openEntry(u),c=PAGE_STATE.co;if(!t||!c)return;var co=clockOutHM(t,c.fin);t.out=co.out;if(co.capped){t.capped=true;notify('admin',u.name+' clocked out more than '+MAX_SHIFT_H+' hours after starting – capped at '+MAX_SHIFT_H+' h, please check.');}t.realOut=new Date().toISOString();t.crew=c.crew;t.outNote=c.note;
  if(c.bm){t.breakMissed=true;notify(['admin'].concat(u.subId?[u.subId]:[]),'Break missed or interrupted: '+u.name+' at '+t.site+' on '+t.date+' ('+t.in+'–'+t.out+plus1(t.in,t.out)+'). No break deducted – paid and billable.');}
  audit('Clocked out',u.name,t.site+' '+t.in+'–'+t.out+plus1(t.in,t.out)+(c.bm?' – break missed/interrupted (flagged)':''));save();closeModal();toast('Clocked out ✓');render();};
setInterval(function(){var c=document.querySelector('[data-live-clock]');if(c)c.textContent=hmOf(Date.now());var e=document.querySelector('[data-elapsed]');if(e)e.textContent=fmtDur((Date.now()-(+e.dataset.elapsed))/3600000);},20000);

/* My shifts: Worked / Break / hrs; crew sign-up for subcontractor workers; employees are assigned by the office */
function myShiftsView(){var u=ME,mine=DB.time.filter(function(t){return t.userId===u.id&&!t.test;}).sort(function(a,b){return a.date<b.date?1:a.date>b.date?-1:a.in<b.in?1:-1;});var tot=0;
  var x='<h1 class="h1">My shifts</h1>'+(mine.length?'<div class="tw"><table><tr><th>Day</th><th>Site</th><th>Start – finish</th><th>Worked</th><th>Break</th><th>Hrs</th></tr>'+mine.map(function(t){var sh=DB.shifts.filter(function(s){return s.id===t.shiftId;})[0];var site=t.site||(sh&&sh.site)||'';var w=t.out?hrs(t.in,t.out):0,br=unpaidBreak(w,t);if(t.out)tot+=w-br;var c=latestChange(t.key0||('t:'+t.id));
    return '<tr><td>'+shortDay(t.date)+'</td><td>'+esc(site)+'</td><td>'+esc(t.in)+' – '+(t.out?esc(t.out)+plus1H(t.in,t.out):'<span class="pill s-ok">on shift</span>')+(t.orig?'<div class="small muted">changed from '+esc(t.orig.in)+'–'+esc(t.orig.out)+' (farm change approved by office)</div>':'')+(c&&c.status==='Pending'?'<div class="small"><span class="pill s-pend">Farm change pending</span></div>':'')+'</td><td>'+(t.out?fmtDur(w):'–')+'</td><td>'+(t.breakMissed?'<span class="pill s-warn">missed – paid</span>':br?fmtDur(br):'–')+'</td><td><b>'+(t.out?(w-br).toFixed(2):'–')+'</b></td></tr>';}).join('')+'</table></div><p>Total: <b>'+tot.toFixed(2)+' hrs</b></p>':'<p class="muted">No shifts yet. When you clock in, your shifts show up here.</p>');
  if(u.type==='worker'){var mineSh=DB.shifts.filter(function(s){return s.kind==='crew'&&!s.test&&s.date>=today()&&(s.booked||[]).indexOf(u.id)>=0;});var open=DB.shifts.filter(function(s){return s.kind==='crew'&&!s.test&&s.date>=today()&&(s.booked||[]).indexOf(u.id)<0;}).sort(function(a,b){return a.date<b.date?-1:1;});
    x+='<h2>My crew assignments</h2>'+(mineSh.map(function(s){return shiftCard(s,u,'view');}).join('')||'<p class="muted small">You are not on a crew yet. Your employer can place you on one, or you can sign up below.</p>')+'<h2>Crew shifts you can sign up for</h2><p class="small muted">Your employer ('+esc(employerName(u))+') can also place you on crews.</p>'+(open.map(function(s){return shiftCard(s,u,'signup');}).join('')||'<p class="muted small">No open crew shifts right now.</p>');}
  if(u.type==='employee'){var asg=DB.shifts.filter(function(s){return s.kind==='employee'&&!s.test&&s.date>=today()&&(s.booked||[]).indexOf(u.id)>=0;});x+='<h2>Upcoming assignments</h2><p class="small muted">Company employees do not sign up for shifts – the office assigns them.</p>'+(asg.map(function(s){return '<div class="card small"><b>'+esc(s.date)+' · '+esc(s.start)+'–'+esc(s.end)+'</b> – '+esc(s.title)+' ('+esc(s.site)+')</div>';}).join('')||'<p class="muted small">None.</p>');}
  return x;}

/* Menu */
function myPayRate(u){if(u.type==='employee')return Number((u.profile||{}).payRate)>0?money(u.profile.payRate)+' / hour (set by the UnScramble office)':'Not set yet (the office sets it)';if(u.type==='worker')return u.payRate?money(u.payRate)+' / hour (set by your employer, '+esc(employerName(u))+')':'Set by your employer ('+esc(employerName(u))+')';return '';}
function menuView(){var u=ME,R=requirements(u),todo=R.filter(function(r){return !r.ok&&r.st.s!=='Optional';}).length,unread=DB.notes.filter(function(n){return n.to===u.id&&!n.read;}).length;
  var it=[['#/checklist','✓','Registration checklist',todo?todo+' item(s) to finish':'All complete'],['#/register','👤',u.type==='employee'?'Registration & payroll':'My details','Job role: '+JOB_ROLES[jobRoleOf(u)].label],['#/docs','📄','My documents',''],['#/terms','✍','Agreements & terms',missingTerms(u).length?'Action needed':''],['#/safety','⛑','Safety training',''],['#/availability','📅','Availability',''],['#/alerts','🔔','Alerts',unread?unread+' new':''],['#/profile','◉','Profile & password','']];
  return '<h1 class="h1">Menu</h1><div class="card small"><b>'+esc(u.name)+'</b> · '+esc(TYPES[u.type])+'<br>My pay rate: <b>'+myPayRate(u)+'</b></div><div class="menu-list">'+it.map(function(i){return '<a class="menu-item" href="'+i[0]+'"><span class="mi" aria-hidden="true">'+i[1]+'</span><span class="mt"><b>'+esc(i[2])+'</b>'+(i[3]?'<small>'+esc(i[3])+'</small>':'')+'</span><span class="chev" aria-hidden="true">›</span></a>';}).join('')+'</div><button class="sec" data-act="logout" style="margin-top:12px;width:100%">Sign out</button>';}

/* routes for employees and subcontractor workers */
NAV.worker=[['#/home','Clock'],['#/shifts','My shifts'],['#/menu','Menu'],['#/checklist','Registration checklist'],['#/register','My details'],['#/docs','My documents'],['#/safety','Safety training'],['#/availability','Availability'],['#/alerts','Alerts'],['#/terms','Agreements & terms'],['#/profile','Profile']];
NAV.employee=[['#/home','Clock'],['#/shifts','My shifts'],['#/menu','Menu'],['#/checklist','Registration checklist'],['#/register','Registration & payroll'],['#/docs','Documents'],['#/safety','Safety training'],['#/availability','Availability'],['#/alerts','Alerts'],['#/terms','Agreements & terms'],['#/profile','Profile']];
(function(){var oh=VIEWS['worker:home'];function checklistPage(){var u=ME;var lock=clockLockHtml(u);return lock+(u.type==='worker'&&tempActive(u)?tempBox(u):'')+oh();}
  VIEWS['worker:home']=VIEWS['employee:home']=function(){return readyForClock(ME)?clockView():checklistPage();};
  VIEWS['worker:checklist']=VIEWS['employee:checklist']=checklistPage;
  VIEWS['worker:shifts']=VIEWS['employee:shifts']=myShiftsView;VIEWS['worker:menu']=VIEWS['employee:menu']=menuView;
  VIEWS['worker:docs']=function(){var d=docsPage(ME);return '<h1>My documents</h1>'+(docKindsFor(ME).length?'<p class="small muted">Upload a photo, or type in the details. The office checks them.</p>':'')+(d||'<div class="msg-empty" id="docsempty"><b>No documents needed for your job.</b> Nothing to do here. If your job changes, update it in My details.</div>');};})();
/* Why can't I clock in? One plain reason, never a misleading "all set" */
function clockLockHtml(u){if(readyForClock(u))return '';
  var hard=(typeof clockHardBlockers==='function'?clockHardBlockers(u):blockers(u,today())).map(function(b){return b.m;}),has=function(re){return hard.some(function(m){return re.test(m);});},why;
  if(u.accountApproved===false)why='The office has not checked your account yet. Once it is approved, you can clock in.';
  else if(has(/^This account is/))why='Your account is switched off or on hold. Please contact the office.';
  else if(has(/^You have not accepted/))why='Please accept your agreements first. <a href="#/terms">Open agreements →</a>';
  else if(has(/^(Employer: |Not linked to an employer|Your employer )/))return '<div class="alert warn cantclock" id="cantclock"><b>Your employer\'s papers are not finished yet.</b><span class="why">Until they are, you can\'t be booked on crew shifts. There is nothing for you to fix – please ask your employer, or contact the office.</span></div>';
  else why='Please finish the items marked below, then you can clock in.';
  return '<div class="alert warn cantclock" id="cantclock"><b>⏱ You can\'t clock in yet.</b><span class="why">'+why+'</span></div>';}
var _layoutV1=layout;
layout=function(content){var u=ME;if(!u||(u.type!=='worker'&&u.type!=='employee')||gateNav(u))return _layoutV1(content);
  var h=location.hash.split('?')[0]||'#/home',act=h==='#/shifts'?'shifts':(h==='#/home'||h==='#/')?'clock':'menu';var ini=u.name.split(' ').map(function(x){return x[0];}).join('').slice(0,2).toUpperCase();
  return '<div class="testbar"><span>TEST VERSION – local only.</span> Fake data, stored only in this browser. Nothing is sent anywhere.'+(DB.settings.simDate?' &nbsp;<span>Simulated date: '+DB.settings.simDate+'</span>':'')+'</div>'+
  '<div class="emp"><header class="topbar"><a href="#/home" class="emp-brand"><img src="assets/unscramble-logo.svg" alt="UnScramble" class="emp-logo"><span class="emp-app">UnScramble</span></a><div class="topbar-r">'+(u.type==='worker'?(tempBadge(u)||tempBadge(subOf(u))):'')+'<a class="avatar" href="#/menu" title="'+esc(u.name)+' – menu" aria-label="Menu">'+esc(ini)+'</a></div></header>'+
  '<main class="emp-main" id="main">'+content+'</main><nav class="tabbar" aria-label="Main"><a href="#/home" class="'+(act==='clock'?'on':'')+'"><span class="ti" aria-hidden="true">⏱</span>Clock</a><a href="#/shifts" class="'+(act==='shifts'?'on':'')+'"><span class="ti" aria-hidden="true">☰</span>My shifts</a><a href="#/menu" class="'+(act==='menu'?'on':'')+'"><span class="ti" aria-hidden="true">≡</span>Menu</a></nav>'+
  '<footer class="emp-foot">UnScramble – The HR Company Inc.</footer></div>';};

/* office sees missed-break flags on the person screen */
(function(){var op=ACT.person;if(!op)return;ACT.person=function(el){op(el);var u=user(el.dataset.id),m=document.querySelector('#modal .modal');if(!u||!m)return;var f=DB.time.filter(function(t){return t.userId===u.id&&t.breakMissed;});if(f.length)m.insertAdjacentHTML('beforeend','<h3>Break missed or interrupted (flagged)</h3><ul class="small">'+f.map(function(t){return '<li>'+esc(t.date)+' '+esc(t.site)+' '+esc(t.in)+'–'+esc(t.out)+plus1(t.in,t.out)+' – not deducted (paid and billable)</li>';}).join('')+'</ul>');};})();
