/* v2-docs.js – type document details instead of uploading (subs + workers), "I confirm these details are true",
   originals may be requested within 5 business days; office Documents screen with status, expiry, pass days left, reminders. TEST ONLY. */
'use strict';
docsPage=function(u){var manualOk=u.type==='sub'||u.type==='worker';var x='';
  if(u.type==='worker')x+='<div class="alert info small">You only add what your job role needs ('+esc(JOB_ROLES[jobRoleOf(u)].label)+'). Proof of eligibility to work is checked and kept by your employer ('+esc(employerName(u))+') – you do not upload it here.</div>';
  if(!docKindsFor(u).length)return x+'<p class="muted">No documents are needed for your job role. If your job changes, update your role in My details.</p>';
  docKindsFor(u).forEach(function(k){var ds=docState(u,k),d=ds.d,st=ds.st,hist=docsOf(u.id,k);
    x+='<div class="card" id="doc-'+k+'"><div class="row"><b>'+esc(DOCS[k].label)+'</b>'+pill(st)+(st.ex&&st.s!=='On 14-day pass'?'<span class="small muted">expiry/due '+esc(st.ex)+'</span>':'')+'</div>';
    if(k==='wcb_clearance'&&u.type==='sub')x+='<div class="small muted">'+esc(wcbRuleText(u))+'</div>';
    if(st.note)x+='<div class="small" style="color:#c0392b">'+esc(st.note)+'</div>';
    if(st.s==='Expired'||st.s==='Expiring soon')x+='<div class="small">'+esc(fixMsg(k,st,d))+'</div>';
    if(hist.length)x+='<div class="small" style="margin:6px 0">'+hist.slice(0,3).map(function(h){return '<a href="#" data-act="viewdoc" data-id="'+h.id+'">'+esc(h.manual?'Typed details'+(h.meta&&h.meta.number?' (no. '+h.meta.number+')':''):h.fileName)+'</a> <span class="muted">('+esc(PILL_LABEL[docStatus(h).s]||h.status)+', '+(h.manual?'entered ':'uploaded ')+fmtStamp(h.uploadedAt)+')</span>'+(h.originalsRequested?' <span class="pill s-warn">Originals requested – due '+esc(h.originalsRequested.due)+'</span>':'');}).join('<br>')+'</div>';
    x+='<details><summary class="small" style="cursor:pointer;color:var(--p2)">'+(d?'Upload a new one':'Upload a file')+'</summary><form data-form="upload"><input type="hidden" name="kind" value="'+k+'"><input type="hidden" name="uid" value="'+u.id+'"><div class="grid2">'+docMetaFields(k)+'<div><label class="req">File (photo or PDF, max 1.5 MB)</label><input type="file" name="file" accept="image/*,application/pdf" required></div></div><button>Upload</button></form></details>';
    if(manualOk&&k!=='agreement'&&k!=='bank_letter'){var mf=docMetaFields(k);x+='<details class="manual" id="manual-'+k+'"><summary class="small" style="cursor:pointer;color:var(--p2)">Type the details instead (no upload)</summary><form data-form="manualdoc"><input type="hidden" name="kind" value="'+k+'"><input type="hidden" name="uid" value="'+u.id+'"><div class="grid2">'+inp('number','Document / policy / licence number','',{req:true})+inp('issuer','Issued by (e.g. WCB PEI, insurer, province)','',{req:true})+mf+(DOCS[k].expiry&&mf.indexOf('name="expiry"')<0?inp('expiry','Expiry date','',{type:'date',req:DOCS[k].expiry===true}):'')+'</div>'+chk('confirmTrue','<b>I confirm these details are true.</b>',false,{req:true})+'<div class="hint">UnScramble may ask to see the originals within 5 business days.</div><button>Save details</button></form></details>';}
    x+='</div>';});
  return x;};
FORMS.manualdoc=function(f,d){var u=user(d.uid);if(!u||(u.id!==ME.id&&ME.type!=='admin')){toast('Not allowed.');return;}
  if(!d.confirmTrue){toast('Please tick "I confirm these details are true".');return;}if(!d.number||!d.issuer){toast('Enter the number and who issued it.');return;}
  if(DOCS[d.kind].expiry===true&&!d.expiry){toast('Enter the expiry date.');return;}
  if(d.kind==='cgl'&&d.coverage!==undefined&&Number(d.coverage)<2000000){toast('Coverage must be at least $2,000,000 per occurrence.');return;}
  var meta={number:d.number,issuer:d.issuer};['docType','permitEmployer','cls','coverage','agreementVersion','addlInsured'].forEach(function(k){if(d[k])meta[k]=d[k];});meta.airBrake=!!d.airBrake;
  DB.docs.push({id:uid('d'),userId:u.id,kind:d.kind,status:'pending',manual:true,confirmedTrue:true,fileName:'(typed details – no file)',fileType:'',fileData:null,expiry:d.expiry||'',meta:meta,uploadedAt:new Date().toISOString(),uploadedBy:ME.name});
  audit('Entered document details manually (confirmed true)',u.name,DOCS[d.kind].label+' no. '+d.number);notify('admin','Typed document details to review: '+DOCS[d.kind].label+' – '+u.name+' (no file; originals may be requested within 5 business days)');
  save();toast('Saved – waiting for office review. Originals may be requested within 5 business days.');render();};
(function(){var ov=ACT.viewdoc;ACT.viewdoc=function(el){var d=DB.docs.filter(function(x){return x.id===el.dataset.id;})[0];if(!d)return;if(!d.manual)return ov(el);if(!canSeeDoc(d)){toast('You do not have access to this document.');return;}var u=user(d.userId);audit('Viewed document',u?u.name:'',DOCS[d.kind].label+' (typed details)');save();
  modal('<h2>'+esc(DOCS[d.kind].label)+' – '+esc(u?u.name:'')+'</h2><div class="alert info small">Typed in manually – no file uploaded. The person ticked "I confirm these details are true". UnScramble may ask for originals within 5 business days.</div><div class="kv"><div>Number</div><div>'+esc(d.meta.number||'')+'</div><div>Issued by</div><div>'+esc(d.meta.issuer||'')+'</div>'+(d.expiry?'<div>Expiry</div><div>'+esc(d.expiry)+'</div>':'')+'<div>Status</div><div>'+pill(docStatus(d))+'</div><div>Entered</div><div>'+fmtStamp(d.uploadedAt)+' by '+esc(d.uploadedBy)+'</div><div>Originals</div><div>'+(d.originalsRequested?'Requested '+esc(d.originalsRequested.at)+' – due '+esc(d.originalsRequested.due):'Not requested')+'</div></div>'+(ME.type==='admin'&&!d.originalsRequested?'<p><button class="small sec" data-act="reqorig" data-id="'+d.id+'">Request originals (due in 5 business days)</button></p>':''));};})();
ACT.reqorig=function(el){var d=DB.docs.filter(function(x){return x.id===el.dataset.id;})[0],u=user(d.userId);d.originalsRequested={at:today(),due:addBusinessDays(today(),5),by:ME.name};audit('Requested original document',u.name,DOCS[d.kind].label+' – due '+d.originalsRequested.due);notify([u.id].concat(u.subId?[u.subId]:[]),'UnScramble asks to see the original '+DOCS[d.kind].label+' within 5 business days (by '+d.originalsRequested.due+').');save();closeModal();toast('Originals requested.');render();};
(function(){var om=metaText;metaText=function(d){var s=om(d),m=d.meta||{};var pre=d.manual?'TYPED DETAILS (no file) · no. '+(m.number||'')+' · issued by '+(m.issuer||''):'';return esc(pre)+(pre&&s?' · ':'')+s;};})();
canSeeDoc=function(d){if(!ME)return false;if(ME.type==='admin'||d.userId===ME.id)return true;var u=user(d.userId);return ME.type==='sub'&&u&&u.subId===ME.id&&['driver_abstract','forklift'].indexOf(d.kind)>=0;};

/* Office "Documents" screen */
NAV.admin.splice(4,0,['#/documents','Documents']);
function docRows(){var rows=[];
  users('sub').concat(users('worker')).forEach(function(u){if(!u.active)return;var i=tempInfo(u),ks=docKindsFor(u).filter(function(k){return k!=='agreement'&&k!=='hst_proof';});
    ks.forEach(function(k){var ds=docState(u,k),d=ds.d;var ex=d&&d.status==='approved'?docExpiry(d):null,left=ex?daysBetween(today(),ex):null;rows.push({u:u,k:k,ds:ds,d:d,ex:ex,left:left,pass:i&&i.active?i:null});});
    if(!ks.length)rows.push({u:u,k:null,ds:{st:{s:'Nothing required for role',c:'s-mut'}},d:null,ex:null,left:null,pass:i&&i.active?i:null});});
  return rows;}
VIEWS['admin:documents']=function(){var rows=docRows(),f=PAGE_STATE.docf||'all';
  var test={all:function(){return true;},pass:function(r){return r.ds.st.s==='On 14-day pass';},pending:function(r){return r.ds.st.s==='Pending review';},problem:function(r){return ['Missing','Expired'].indexOf(r.ds.st.s)>=0;},soon:function(r){return r.left!==null&&r.left<=30;}};
  var my=PAGE_STATE.minYears,srt=PAGE_STATE.yearSort;var shown=rows.filter(test[f]||test.all).filter(function(r){return my===undefined||my===''||(r.u.type==='worker'&&validYears(r.u.forkliftYears)&&r.u.forkliftYears>=+my);});if(srt||(my!==undefined&&my!==''))shown.sort(function(a,b){var ya=validYears(a.u.forkliftYears)?a.u.forkliftYears:-1,yb=validYears(b.u.forkliftYears)?b.u.forkliftYears:-1;return yb-ya;});
  return '<h1>Documents</h1><p class="small muted">Every subcontractor and subcontractor worker, each document\'s status, expiry date and any 14-day pass. Reminders go to the person (and the subcontractor for workers) 30, <b>14</b>, 7 and 1 days before expiry. Statuses: Complete / Pending / On 14-day pass (or Missing / Expired).</p>'+
  '<div class="row">'+[['all','All'],['pass','On 14-day pass'],['pending','Pending'],['problem','Missing / expired'],['soon','Expiring in 30 days']].map(function(b){return '<button class="small '+(f===b[0]?'':'sec')+'" data-act="docfilter" data-f="'+b[0]+'">'+b[1]+' ('+rows.filter(test[b[0]]).length+')</button>';}).join('')+'</div>'+
  '<form data-form="docyears" class="row" style="margin-top:8px"><label for="minYears" style="margin:0">Forklift experience: at least</label><input id="minYears" type="number" name="minYears" min="0" step="1" value="'+esc(my===undefined?'':my)+'" style="max-width:90px"><span class="small">years</span>'+chk('yearSort','Sort by years (most first)',!!srt)+'<button class="small sec">Apply</button></form>'+
  '<div class="tw" style="margin-top:8px"><table id="doctable"><tr><th>Who</th><th>Forklift yrs</th><th>Document</th><th>Status</th><th>How</th><th>Expiry</th><th>Days left</th><th>14-day pass</th><th>Reminder</th><th></th></tr>'+shown.map(function(r){var u=r.u,d=r.d,s=r.ds.st.s;
    return '<tr><td><a href="#" data-act="person" data-id="'+u.id+'">'+esc(u.type==='sub'?(u.company.legalName||u.name):u.name)+'</a><div class="small muted">'+esc(TYPES[u.type])+(u.subId?' · '+esc(employerName(u)):'')+(u.type==='worker'?' · '+esc(JOB_ROLES[jobRoleOf(u)].label):'')+'</div></td><td class="yrs">'+(validYears(u.forkliftYears)?u.forkliftYears:'–')+'</td><td>'+(r.k?esc(DOCS[r.k].label):'<span class="muted">–</span>')+'</td><td>'+pill(r.ds.st)+'</td><td class="small">'+(d?(d.manual?'<a href="#" data-act="viewdoc" data-id="'+d.id+'">Typed details</a>'+(d.originalsRequested?'<br><span class="pill s-warn">originals due '+esc(d.originalsRequested.due)+'</span>':''):'Uploaded file'):'–')+'</td><td class="small">'+esc(r.ex||'–')+'</td><td>'+(r.left===null?'–':'<span class="pill '+colour(r.left)+'">'+(r.left<=0?'Expired':r.left+' d')+'</span>')+'</td><td class="small">'+(r.pass?'<b>'+r.pass.left+' day'+(r.pass.left===1?'':'s')+' left</b><br>ends '+esc(r.pass.t.end)+(r.pass.t.extensions?'<br>'+r.pass.t.extensions+' extension(s)':''):'–')+'</td><td class="small">'+(r.left!==null&&r.left>0&&r.left<=14?'14-day reminder sent':r.left!==null&&r.left>14?'at 14 days: '+esc(addDays(r.ex,-14)):'–')+'</td><td>'+(['Missing','Expired','Pending review','On 14-day pass'].indexOf(s)>=0?'<button class="small sec" data-act="passmodal" data-id="'+u.id+'">'+(r.pass?'Extend pass':'14-day pass')+'</button>':'')+(d&&d.status==='pending'?' <a class="small" href="#/review">Review</a>':'')+'</td></tr>';}).join('')+'</table></div>';};
ACT.docfilter=function(el){PAGE_STATE.docf=el.dataset.f;render();};
FORMS.docyears=function(f,d){if(d.minYears!==''&&!validYears(d.minYears)){toast('Enter a whole number of years.');return;}PAGE_STATE.minYears=d.minYears;PAGE_STATE.yearSort=!!d.yearSort;render();};
