/* v2-farm.js – Farm (client firm) signs the Independent Contractor Service Agreement in the app before its first shift can be booked.
   Text from the Sep 2025 draft (Drive), real names replaced with placeholders. Typed signature, name + title, authority tick,
   version + date/time + time zone recorded, print / save-as-PDF copy. Office sees status per farm and can publish a new version (re-prompt). TEST ONLY. */
'use strict';
var FIRM_AGR_NAME='Independent Contractor Service Agreement';
var FIRM_AGR_LABEL='Version: Sep 2025 draft, pending owner confirmation';
var FIRM_AGR_NOTE='NO-HIRE AND CONVERSION FEE: 12-month no-hire – for 12 months after a worker last works for the farm or other client through UnScramble, the client will not hire or engage, directly or indirectly, any UnScramble worker, any subcontractor of UnScramble, or any of a subcontractor\'s workers. Conversion fee per worker: $0 (amount set in Office > Settings).';
function firmAgreementText(farmName){var F=farmName||'[Farm legal name]';return [
'INDEPENDENT CONTRACTOR SERVICES AGREEMENT','('+FIRM_AGR_LABEL+'. Names are placeholders in this test app.)','',
'BETWEEN: '+F+', a body corporate, duly incorporated in accordance with the laws of Prince Edward Island (the "Company");',
'AND: UnScramble The HR Company Inc., a body corporate, duly incorporated in accordance with the laws of Prince Edward Island (the "Contractor").','',
'WHEREAS the Company intends to retain the Contractor to assist with providing workers for the Company (the "Project"); AND WHEREAS the parties wish to set out the terms and conditions upon which the Contractor will be retained by the Company for the purposes of the Project; NOW THEREFORE in consideration of the premises, the mutual agreements and covenants as contained in this Agreement, the parties agree as follows:','',
'1. Engagement of Services. The Company will issue Project Assignments to the Contractor, in the form set out in Appendix "A" (the "Project Assignments"), which will be subject to the terms of this Agreement. The Contractor will, to the best of its ability, render the services and complete the deliverables set forth in any Project Assignment. The Contractor shall: (a) perform all services in a timely and professional manner; (b) provide updates to the Company as set forth in the Project Assignments; (c) follow all the legal requirements to subcontract or otherwise delegate any of its obligations under this Agreement; and (d) abide by the Company\'s Confidentiality Policies and Non-Disclosure principles at all material times.',
'2. Rights Granted. The Company grants to the Contractor, and the Contractor accepts, the exclusive rights to provide workers for the Company in the territory of Prince Edward Island, Canada (the "Territory"), and the Company shall not appoint any other company of similar nature in the Territory, except as herein provided. The Company shall directly hire its own employees.',
'3. Compensation. (1) The Company will pay the Contractor an hourly fee for each of the Contractor\'s workers provided to the Company (the "Workers") as set forth in the Project Assignments (the "Hourly Fee"). The Company will be invoiced monthly (the "Invoice"). The Invoice is payable within thirty (30) days of the Company receiving it (the "Payment Deadline"). Interest of two percent (2%) per month (24% annually) is payable on any invoice not paid on or before the Payment Deadline. (2) The Company will deduct a maximum of thirty (30) minutes for an unpaid break in a single day for each Worker on any day the Workers work for the Company. (3) The Company will pay the Hourly Fee for at least five (5) hours a day (the "Minimum Hours") for each Worker on any day the Workers work for the Company, even if not scheduled for the Minimum Hours. (4) In addition, the Company will pay an annual fee as set forth in the Project Assignments (the "Annual Fee"); the Annual Fee is not payable if the total hours worked by the Workers for the Company is above [___] hours a year (the "Minimum Annual Hours").',
'4. Independent Contractor Relationship. The Contractor\'s relationship with the Company is that of an independent contractor; nothing in this Agreement creates a partnership, joint venture or employer-employee relationship. The Contractor may make representations, contracts or commitments on behalf of the Company solely within the scope of this Agreement and the Project. The Contractor accepts exclusive liability for complying with all applicable federal, provincial or municipal laws as they relate to fees paid to it, and will indemnify the Company against any such taxes or contributions, including penalties and interest.',
'5. Contractor Representations and Warranties. The Contractor represents and warrants that: (a) it is responsible for the recruiting, hiring, compensation, human resources and payroll of the Workers; the Workers are employed by the Contractor, not the Company; (b) it has full right and power to enter into and perform this Agreement without the consent of any third party; and (c) if the Company permits the Workers to use its equipment, tools or facilities, such permission is gratuitous and the Contractor is responsible for any injury to any person (including death) or damage to property arising out of that use.',
'6. Company Representations and Warranties. The Company represents and warrants that: (a) it will take all necessary precautions to prevent injury to any persons or damage to property, is responsible for the health and safety of the Workers while working at its facilities, and will provide appropriate personal protective equipment as required under occupational health and safety law; (b) it will not discuss compensation with the Workers, its employees or anyone else provided by the Contractor; (c) it will abide by all legislation, including the Employment Standards Act, RSPEI 1988, c E-6.2, regarding breaks (meal and rest); and (d) it will not hire any of the Workers, directly or indirectly, until one (1) year after the Worker has terminated their employment with the Contractor.',
'7. Indemnification and Insurance. The Contractor will indemnify and hold harmless the Company, its officers, directors, employees, sublicensees, customers and agents from all claims, losses, liabilities, damages, expenses and costs (including legal fees) resulting from a breach or alleged breach of any representation or warranty of the Contractor. The Company may withhold from payments due to the Contractor the amount of any defence costs plus reasonable security. The Contractor shall maintain comprehensive general liability insurance of not less than Five Million Dollars ($5,000,000.00 CDN) combined single limit, deliver a certificate on request (30 days\' notice of change or termination, the Company named as additional insured, waiver of subrogation).',
'8. Term. The term begins on the date of signing and ends on its one (1) year anniversary, with automatic annual renewal unless terminated under this Agreement.',
'9. Termination. (1) The Company may terminate at its convenience on seven (7) days\' prior written notice, or immediately on the Contractor\'s material breach. (2) The Contractor may terminate at its convenience on seven (7) days\' prior written notice, or immediately on the Company\'s material breach. (3) Non-interference: during and for one (1) year after termination, the Company agrees not to solicit or induce any employee of the Contractor to terminate or breach their relationship with the Contractor.',
'10. General Provisions. (1) Governing law: Prince Edward Island and the applicable laws of Canada; courts of Prince Edward Island. (2) Severability. (3) No assignment by the Contractor without the Company\'s prior written consent. (4) Notices in writing (registered mail, hand delivery, electronic transfer or courier); mailed notice is given five (5) business days after mailing. (5) Injunctive relief. (6) Waiver. (7) Entire agreement; amendments only in writing signed by both parties; in a conflict, the Project Assignment governs only for the services it describes.','',
FIRM_AGR_NOTE,'',
'APPENDIX "A" – PROJECT ASSIGNMENT','Services: The Contractor will provide workers and a manager (contact person) to the Company as requested with one day\'s notice. The workers will perform tasks as requested by the Company; the manager oversees the workers, training and any certifications requested.',
'Schedule of labour charges: [agreed hourly rate – set per farm in the Project Assignment] per hour. Rates include applicable Workers\' Compensation premiums and associated costs; no further labour charges unless agreed in writing in advance.',
'Annual fee: $[___] per year (or waived by [UnScramble representative]).',
'This Project Assignment is covered by the Independent Contractor Services Agreement in effect between the Company and the Contractor; where inconsistent, the Project Assignment governs only for the services it describes.'].join('\n');}
function firmAgr(){return DB.settings.firmAgreement;}
function firmSig(firm){if(!firm||!firm.id)return null;var s=(DB.firmSigs||[]).filter(function(x){return x.firmId===firm.id;});return s[s.length-1]||null;}
function firmSignedCurrent(firm){var s=firmSig(firm);return !!(s&&s.version===firmAgr().version);}
function firmSignedEver(firm){return !!firmSig(firm);}
function firmOfSite(code){var s=DB.sites.filter(function(x){return x.code===code;})[0];return s&&s.firmId?user(s.firmId):null;}

/* booking rule: no shift at a farm can be booked until that farm has signed (any version). A newer version re-prompts the farm but does not cancel existing bookings. */
(function(){var ob=blockers;blockers=function(u,date,shift){var b=ob(u,date,shift);if(shift&&!shift.test){var f=firmOfSite(shift.site);if(f&&!firmSignedEver(f))b.push({m:'This farm or client has not signed the '+FIRM_AGR_NAME+' yet – shifts there cannot be booked until it does.',fix:''});}return b;};})();

function firmAgrCard(firm,forOffice){var a=firmAgr(),s=firmSig(firm),cur=firmSignedCurrent(firm);
  if(cur&&!forOffice)return '<div class="card"><b>'+esc(FIRM_AGR_NAME)+'</b> '+'<span class="pill s-ok">Signed v'+esc(s.version)+'</span><div class="small">Signed by '+esc(s.signerName)+' ('+esc(s.title)+') on '+fmtStamp(s.at)+' '+esc(s.tz)+'.</div><button class="small sec" data-act="firmagrprint" data-id="'+s.id+'">Print / save as PDF</button> <button class="small sec" data-act="firmagrdl" data-id="'+s.id+'">Download copy</button></div>';
  return '<div class="card hl" id="firmagr"><h2 style="margin-top:0">'+esc(FIRM_AGR_NAME)+' <span class="small muted">'+esc(a.label)+' · app version '+esc(a.version)+'</span></h2>'+(s?'<div class="alert warn small">A new version was published. You signed v'+esc(s.version)+' on '+fmtStamp(s.at)+'. Please review and sign again.</div>':'<div class="alert warn small">Please sign before your first shift can be booked.</div>')+
  '<div class="terms-text">'+esc(firmAgreementText(firm.name))+'</div><form data-form="firmsign"><div class="grid2">'+inp('signerName','Your full name',(firm.firm||{}).signerName||'',{req:true})+inp('title','Your title (e.g. Owner, Farm Manager)','',{req:true})+'</div>'+chk('authorized','<b>I\'m authorized to sign for this farm</b> ('+esc(firm.name)+').',false,{req:true})+inp('signature','Type your name as your signature','',{req:true,ph:'Typed signature'})+'<div class="hint">Your name, title, the version, and the date, time and time zone are recorded. You can print or save a PDF copy afterwards.</div><button>Sign agreement</button></form></div>';}
FORMS.firmsign=function(f,d){var firm=ME;if(firm.type!=='firm'){toast('Not allowed.');return;}if(!d.authorized){toast('Please tick "I\'m authorized to sign for this farm".');return;}
  if(!d.signerName||!d.title||!d.signature){toast('Enter your name, title and typed signature.');return;}
  if(d.signature.trim().toLowerCase()!==d.signerName.trim().toLowerCase()){toast('The typed signature must match your full name.');return;}
  var a=firmAgr();var s={id:uid('fs'),firmId:firm.id,firmName:firm.name,version:a.version,label:a.label,signerName:d.signerName.trim(),title:d.title.trim(),signature:d.signature.trim(),authorized:true,at:new Date().toISOString(),tz:tz(),device:deviceInfo(),text:firmAgreementText(firm.name)};
  (DB.firmSigs=DB.firmSigs||[]).push(s);audit('Farm signed '+FIRM_AGR_NAME,firm.name,'v'+a.version+' by '+s.signerName+' ('+s.title+') '+s.tz);notify('admin',firm.name+' signed the '+FIRM_AGR_NAME+' (v'+a.version+') – '+s.signerName+', '+s.title+'.');save();toast('Signed – thank you. You can print or save a copy.');render();};
function firmSigHtml(s){return '<!DOCTYPE html><html><head><meta charset="utf-8"><title>'+esc(FIRM_AGR_NAME)+' – '+esc(s.firmName)+'</title><style>body{font:14px/1.5 Arial,sans-serif;max-width:760px;margin:24px auto;color:#111}h1{color:#332E57;font-size:20px;border-bottom:3px solid #D9A03C;padding-bottom:6px}pre{white-space:pre-wrap;font:inherit}.sig{border:1px solid #ccc;padding:12px;margin-top:16px}.t{color:#a33;font-weight:bold}</style></head><body><div class="t">TEST VERSION – sample only, not a real agreement</div><h1>'+esc(FIRM_AGR_NAME)+'</h1><p>'+esc(s.label)+' · app version '+esc(s.version)+'</p><pre>'+esc(s.text)+'</pre><div class="sig"><b>Signed for the Company ('+esc(s.firmName)+')</b><br>Signature (typed): <i>'+esc(s.signature)+'</i><br>Name: '+esc(s.signerName)+' · Title: '+esc(s.title)+'<br>Authorized to sign for this farm: yes<br>Date/time: '+esc(fmtStamp(s.at))+' · Time zone: '+esc(s.tz)+'<br>Device: '+esc(s.device)+'</div></body></html>';}
ACT.firmagrdl=function(el){var s=(DB.firmSigs||[]).filter(function(x){return x.id===el.dataset.id;})[0];if(!s)return;if(ME.type!=='admin'&&ME.id!==s.firmId){toast('Not allowed.');return;}downloadText('Independent-Contractor-Service-Agreement-'+s.firmName.replace(/[^A-Za-z0-9]+/g,'-')+'-v'+s.version+'.html',firmSigHtml(s),'text/html');audit('Downloaded signed farm agreement',s.firmName,'v'+s.version);save();};
ACT.firmagrprint=function(el){var s=(DB.firmSigs||[]).filter(function(x){return x.id===el.dataset.id;})[0];if(!s)return;if(ME.type!=='admin'&&ME.id!==s.firmId){toast('Not allowed.');return;}var w=window.open('','_blank');if(!w){toast('Pop-up blocked – use Download copy instead.');return;}w.document.write(firmSigHtml(s));w.document.close();w.focus();setTimeout(function(){try{w.print();}catch(e){}},300);};

/* farm home: agreement card first */
(function(){var oh=VIEWS['firm:home'];VIEWS['firm:home']=function(){return firmAgrCard(ME,false)+oh();};})();

/* office: signed status per farm + publish a new version (re-prompt) */
(function(){var of=VIEWS['admin:firms'];VIEWS['admin:firms']=function(){var a=firmAgr();
  var x='<div class="card hl" id="firmagradmin"><h2 style="margin-top:0">'+esc(FIRM_AGR_NAME)+' – signed status</h2><p class="small">Current: <b>app version '+esc(a.version)+'</b> ('+esc(a.label)+'). Farms must sign before their first shift can be booked. '+esc(FIRM_AGR_NOTE)+'</p><div class="tw"><table><tr><th>Farm</th><th>Status</th><th>Signed by</th><th>When (time zone)</th><th></th></tr>'+users('firm').map(function(f){var s=firmSig(f),cur=firmSignedCurrent(f);
    return '<tr><td>'+esc(f.name)+'</td><td>'+(cur?'<span class="pill s-ok">Signed – current v'+esc(s.version)+'</span>':s?'<span class="pill s-warn">Signed old v'+esc(s.version)+' – re-prompted</span>':'<span class="pill s-bad">Not signed – shifts cannot be booked</span>')+'</td><td class="small">'+(s?esc(s.signerName)+', '+esc(s.title):'–')+'</td><td class="small">'+(s?fmtStamp(s.at)+' '+esc(s.tz):'–')+'</td><td>'+(s?'<button class="small sec" data-act="firmagrdl" data-id="'+s.id+'">Copy</button>':'')+'</td></tr>';}).join('')+'</table></div>'+
    '<form data-form="firmagrpub" class="row"><input type="text" name="label" value="'+esc(a.label)+'" style="max-width:340px" required><input type="text" name="reason" placeholder="What changed (required)" style="max-width:240px" required><button class="small">Publish new version (farms sign again)</button></form></div>';
  return x+of();};})();
FORMS.firmagrpub=function(f,d){if(!d.reason){toast('Say what changed.');return;}var a=firmAgr();var nv=((Math.round((parseFloat(a.version)||1)*10)+1)/10).toFixed(1);(a.history=a.history||[]).push({version:a.version,label:a.label,at:new Date().toISOString()});a.version=nv;a.label=d.label||a.label;a.publishedAt=today();
  users('firm').forEach(function(fm){notify(fm.id,'A new version ('+nv+') of the '+FIRM_AGR_NAME+' is ready. Please sign in and sign it: '+d.reason);});audit('Published farm agreement version',nv,d.reason);save();toast('Version '+nv+' published – farms will be asked to sign again.');render();};
