/* v2-icsa.js – client agreement text from the farm-first master of the Independent Contractor Services Agreement
   (Version: 2026-10; conversion fee 6(e) from Office > Settings, default $0 – see v2-icsa-master.js). Other blanks stay blank; no real names or street address in the test app.
   Appendix "A" shows the client's industry ticked (farm first) and its Rate Schedule. Also enforces the 7-day window for client time-change proposals. TEST ONLY. */
'use strict';
FIRM_AGR_LABEL='Version: 2026-10';
FIRM_AGR_NOTE='No-hire 6(d): from day one until 12 months after the last work – covers UnScramble\'s own workers, subcontractor firms and their workers. Conversion fee 6(e): $0 per worker or subcontractor firm + HST.';
var ICSA_CHANGE_DAYS=7;
firmAgreementText=function(name,industry){var F=name||'__________ (legal name of the client business)';var firm=(name&&DB)?users('firm').filter(function(u){return u.name===name;})[0]:null;var ind=industry||clientTypeOf(firm);
  var box=clientTypes().map(function(t){return '['+(t===ind?'x':' ')+'] '+t;}).join('  ');
  return ['INDEPENDENT CONTRACTOR SERVICES AGREEMENT','MASTER TEMPLATE (farm-first). '+FIRM_AGR_LABEL+'. Blanks are placeholders in this test app.','',
'BETWEEN: '+F+', a body corporate duly incorporated in accordance with the laws of Prince Edward Island (the "Company" or the "Client");',
'AND: UnScramble The HR Company Inc., a body corporate duly incorporated in accordance with the laws of Prince Edward Island (the "Contractor").','',
'WHEREAS the Company operates a farm or other business (including, without limitation, potato and other crop farming, grading and packing, construction, bakery, painting or cleaning) and intends to retain the Contractor to provide workers for the Company (the "Project"); AND WHEREAS the parties wish to set out the terms and conditions upon which the Contractor will be retained by the Company for the purposes of the Project; NOW THEREFORE in consideration of the premises and the mutual agreements and covenants contained in this Agreement, the parties agree as follows:','',
'1. Engagement of Services. The Company will issue Project Assignments to the Contractor, in the form set out in Appendix "A" (the "Project Assignments"), which will be subject to the terms of this Agreement. Project Assignments may also be issued as shift bookings through the Contractor\'s online app, and each booking forms part of the applicable Project Assignment. The Contractor will, to the best of its ability, render the services set out in any such Project Assignment. The Contractor shall: (a) perform all services in a timely and professional manner; (b) provide updates to the Company as set out in the Project Assignments; (c) follow all legal requirements when it subcontracts or otherwise delegates any of its obligations under this Agreement, including to subcontractor firms engaged by the Contractor; and (d) abide by the Company\'s confidentiality policies and non-disclosure principles at all material times.',
'2. Rights Granted. The Company grants to the Contractor, and the Contractor accepts, the exclusive right to provide workers for the Company in the territory of Prince Edward Island, Canada (the "Territory"), and the Company shall not appoint any other company of a similar nature in the Territory, except as provided in this Agreement. The Company may directly hire its own employees, subject to Section 6(d).',
'3. Compensation. (1) Hourly Fee. The Company will pay the Contractor an hourly fee for each worker provided to the Company under this Agreement, whether employed by the Contractor or by a subcontractor firm engaged by the Contractor (the "Workers"), at the rates set out in the Project Assignments (the "Hourly Fee"), plus applicable HST (currently 15%). (2) Invoicing and payment. The Contractor will invoice the Company monthly (the "Invoice"). Each Invoice is payable within thirty (30) days of the Company receiving it (the "Payment Deadline"). Interest of two percent (2%) per month (24% per year) is payable on any amount not paid on or before the Payment Deadline. (3) Breaks. The Company may deduct a maximum of thirty (30) minutes for an unpaid break per Worker per day, only where the Worker actually received the break in accordance with the Employment Standards Act (PEI). A break that is missed or interrupted is billable. (4) Minimum hours. The Company will pay the Hourly Fee for at least five (5) hours per day (the "Minimum Hours") for each Worker on any day the Worker works for the Company, even if the Worker is scheduled or used for fewer hours. (5) Annual Fee. In addition, the Company will pay an annual fee of $__________ (the "Annual Fee") as set out in the Project Assignments; the Annual Fee is not payable if the total hours worked by the Workers for the Company in that year exceed __________ hours. (6) Time records. Worker hours are recorded in the Contractor\'s app. The Company may propose changes to recorded shift times with a comment within seven (7) days of the shift; the Contractor will approve, adjust or reject the proposed change, and the approved hours are final for invoicing.',
'4. Independent Contractor Relationship. The Contractor\'s relationship with the Company is that of an independent contractor; nothing in this Agreement creates a partnership, joint venture or employer-employee relationship. The Contractor may make representations, contracts or commitments on behalf of the Company solely within the scope of this Agreement and the Project. The Contractor accepts exclusive liability for complying with all applicable federal, provincial and municipal laws as they relate to fees paid to it, and will indemnify the Company against any such taxes or contributions, including penalties and interest.',
'5. Contractor Representations and Warranties. The Contractor represents and warrants that: (a) it, or a subcontractor firm engaged by it, is responsible for the recruiting, hiring, compensation, human resources and payroll of the Workers; the Workers are employed by the Contractor or its subcontractor, not by the Company; (b) it has full right and power to enter into and perform this Agreement without the consent of any third party; and (c) if the Company permits the Workers to use its equipment, tools or facilities, such permission is gratuitous and the Contractor is responsible for any injury to any person (including death) or damage to property arising out of that use.',
'6. Company Representations and Warranties. The Company represents and warrants that: (a) it will take all necessary precautions to prevent injury to any person or damage to property; it is responsible for the health and safety of the Workers while they work at any of the Company\'s farms, sites or facilities, including site-specific safety orientation, and will provide appropriate personal protective equipment as required under the Occupational Health and Safety Act (PEI); (b) it will not discuss compensation with the Workers, any of its employees, or anyone else provided to it by the Contractor; (c) it will abide by all government legislation, including the Employment Standards Act, RSPEI 1988, c E-6.2, regarding breaks (meal and rest); (d) No hiring of Workers or subcontractors. From the first day a Worker or subcontractor firm provides services to the Company through the Contractor, and until twelve (12) months after that Worker or subcontractor firm last provides services to the Company through the Contractor, the Company will not, directly or indirectly, hire, engage or use the services of (i) any Worker, whether employed by the Contractor or by a subcontractor firm engaged by the Contractor, or (ii) any such subcontractor firm, other than through the Contractor. This includes engaging them through another staffing agency, a related company, or as a direct employee or contractor of the Company. (e) Conversion fee. If the Company breaches Section 6(d), the Company will pay the Contractor a conversion fee of $'+(typeof icsaFeeText==='function'?icsaFeeText():'0')+' per Worker or subcontractor firm engaged (the "Conversion Fee"), plus applicable HST, within thirty (30) days of the Contractor\'s invoice. The Conversion Fee is a genuine pre-estimate of the Contractor\'s recruiting, training and onboarding costs and lost revenue, and does not limit the Contractor\'s right to injunctive relief under Section 10(5).',
'7. Indemnification and Insurance. The Contractor will indemnify and hold harmless the Company, its officers, directors, employees, sublicensees, customers and agents from all claims, losses, liabilities, damages, expenses and costs (including legal fees and court costs) resulting from a breach or alleged breach of any representation or warranty of the Contractor. The Company may withhold from any payment due to the Contractor the amount of any defence costs, plus reasonable security. The Contractor shall maintain appropriate insurance, including comprehensive general liability insurance of not less than Five Million Dollars ($5,000,000.00 CDN) combined single limit; a certificate will be delivered on request (30 days\' notice of change or termination, the Company named as additional insured, insurer\'s subrogation rights waived).',
'8. Term. This Agreement begins on the date it is signed and continues with no fixed end date, renewing automatically each year, until terminated by either party under Section 9.',
'9. Termination. (1) The Company may terminate at its convenience upon seven (7) days\' prior written notice, and immediately upon the Contractor\'s material breach. (2) The Contractor may terminate at its convenience upon seven (7) days\' prior written notice, and immediately upon the Company\'s material breach, including non-payment of any Invoice more than thirty (30) days past the Payment Deadline. (3) Non-interference: during this Agreement and for one (1) year after its termination, the Company will not solicit or induce any employee of the Contractor, or any subcontractor firm engaged by the Contractor or its workers, to terminate or breach any relationship with the Contractor. (4) Survival: Sections 3 (amounts owing), 6(b), 6(d), 6(e), 7, 9(3) and 10 survive termination.',
'10. General Provisions. (1) Governing law: Prince Edward Island and the federal laws of Canada applicable there; courts located in Prince Edward Island. (2) Severability; provisions held excessively broad are reduced to be enforceable. (3) No assignment without the other party\'s prior written consent, except that the Contractor may use subcontractor firms to supply Workers (Section 1(c)). (4) Notices in writing by hand, registered or certified mail, courier or email; mailed notices are given five (5) business days after mailing; others when received. (5) Injunctive relief. (6) Waiver. (7) Electronic signature: this Agreement may be signed electronically, including through the Contractor\'s app by typing the signer\'s name and title and confirming authority to sign; together with the recorded agreement version and date and time, it has the same effect as an original signature. (8) Entire agreement; amendments only in writing signed (including electronically) by both parties; a conflicting Project Assignment governs only for the services set out in it.','',
'APPENDIX "A" – PROJECT ASSIGNMENT','Client: '+F+'   Industry: '+box+'   Site address(es): __________   Client contact: __________   Start date: __________   Expected end date (if seasonal): __________',
'Safety gear (PPE) supplied by: [ ] Client  [ ] UnScramble  [ ] Subcontractor (chosen on each shift booking in the app).',
'Services: The Contractor will provide Workers and a crew lead (contact person) as requested by the Company, with at least one (1) day\'s notice. The crew lead oversees the Workers, coordinates training and any required certifications, and helps ensure tasks are completed efficiently and safely.',
'Schedule of Labour Charges: per Worker per hour, plus HST, including Workers\' Compensation premiums and related costs – see the Rate Schedule (farm roles first: general labour / harvest crew; grader / packer; forklift / bin piler operator – forklift certificate and years of experience on file; truck driver – driver\'s abstract on file; then construction labourer, baker, painter, cleaner, other). No other labour-related charges unless agreed in writing in advance.',
'Annual Fee Payable: $__________ per year (or "Waived", initialled by the Contractor).',
'This Project Assignment is covered by the Independent Contractor Services Agreement between the Company and the Contractor; where inconsistent, this Project Assignment governs only for the services set out in it.'].join('\n');};
if(DB&&DB.settings&&DB.settings.firmAgreement&&/Sep 2025/.test(DB.settings.firmAgreement.label||''))DB.settings.firmAgreement.label=FIRM_AGR_LABEL;
(function(){var ol=load;load=function(){ol();var a=DB&&DB.settings&&DB.settings.firmAgreement;if(a&&/Sep 2025/.test(a.label||'')){a.label=FIRM_AGR_LABEL;save();}};})();
/* client-facing wording: leave the agreement text itself untouched (it is the farm-first master) */
clientWord=(function(o){return function(html,f){if(isFarm(f))return html;var keep=[];html=html.replace(/<div class="terms-text">[\s\S]*?<\/div>|<pre>[\s\S]*?<\/pre>/g,function(m){keep.push(m);return '\u0000'+(keep.length-1)+'\u0000';});return o(html,f).replace(/\u0000(\d+)\u0000/g,function(m,i){return keep[+i];});};})(clientWord);
/* sign card hint: app bookings are Project Assignments */
(function(){var oc=firmAgrCard;firmAgrCard=function(firm,forOffice){return oc(firm,forOffice).replace('<button>Sign agreement + Rate Schedule</button>','<div class="hint">Shifts booked in the app count as Project Assignments (s. 1). You can propose time changes within 7 days of a shift; office-approved hours are final (s. 3(6)). No end date – renews automatically; either side can end it on 7 days\' notice (ss. 8–9).</div><button>Sign agreement + Rate Schedule</button>');};})();
/* 7-day window for client time-change proposals */
function changeWindowOk(date){return daysBetween(date,today())<=ICSA_CHANGE_DAYS;}
(function(){var oe=ACT.firmedit;ACT.firmedit=function(el){var r=(PAGE_STATE.frRows||{})[el.dataset.key];if(r&&!changeWindowOk(r.date)){toast('Time changes can be proposed within '+ICSA_CHANGE_DAYS+' days of the shift (agreement s. 3(6)). This shift is final.');return;}return oe(el);};
  var oc=FORMS.firmchg;FORMS.firmchg=function(f,d){var r=(PAGE_STATE.frRows||{})[d.key];if(r&&!changeWindowOk(r.date)){toast('Time changes can be proposed within '+ICSA_CHANGE_DAYS+' days of the shift (agreement s. 3(6)).');return;}return oc(f,d);};})();
(function(){var ot=firmShiftTable;firmShiftTable=function(firm,R,canEdit){var x=ot(firm,R,canEdit);return x.replace('You can propose a different start or end time; the office reviews it.','You can propose a different start or end time within '+ICSA_CHANGE_DAYS+' days of the shift; the office reviews it and approved hours are final.');};})();
